create table omrs_obs (
  obs_id int not null,
  uuid char(38) not null,
  patient_id int not null,
  encounter_id int,
  obs_date date,
  obs_time time,
  age_years_at_obs int,
  age_months_at_obs int,
  encounter_type varchar(255),
  form varchar(255),
  location varchar(255),
  concept varchar(255) not null,
  value_coded varchar(255),
  value_date date default null,
  value_numeric float default null,
  value_text text,
  comments varchar(255),
  obs_group_id int,
  date_created date
);