create table omrs_patient (
  patient_id int not null,
  patient_uuid char(38) not null,
  identifier varchar(50),
  first_name varchar(50),
  middle_name varchar(50),
  last_name varchar(50),
  gender char(1),
  birthdate date,
  birthdate_estimated boolean,
  phone_number varchar(50),
  country varchar(50),
  state_province varchar(255),
  county_district varchar(255),
  city_village varchar(255),
  postal_code varchar(50),
  address1 varchar(255),
  address2 varchar(255),
  address3 varchar(255),
  address4 varchar(255),
  address5 varchar(255),
  address6 varchar(255),
  latitude varchar(50),
  longitude varchar(50),
  dead boolean,
  death_date date,
  age_years_at_death int,
  age_months_at_death int,
  cause_of_death varchar(255),
  mothers_name varchar(50),
  fathers_name varchar(50),
  health_center varchar(255),
  date_created date
);