-- Derivation script for mw_asthma_followup
-- Generated from Pentaho transform: import-into-mw-asthma-followup.ktr

DROP TABLE IF EXISTS mw_asthma_followup;
CREATE TABLE mw_asthma_followup (
  asthma_followup_visit_id 		int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  planned_visit 			varchar(255) DEFAULT NULL,
  height 				int DEFAULT NULL,
  weight 				int DEFAULT NULL,
  day_symptoms 			int DEFAULT NULL,
  night_symptoms 			int DEFAULT NULL,
  inhaler_use_frequency_daily 	int DEFAULT NULL,
  inhaler_use_frequency_weekly 	int DEFAULT NULL,
  inhaler_use_frequency_monthly 	int DEFAULT NULL,
  inhaler_use_frequency_yearly 	int DEFAULT NULL,
  steroid_inhaler_daily 		varchar(255) DEFAULT NULL,
  number_of_cigarettes_per_day 	int DEFAULT NULL,
  passive_smoking 			varchar(255) DEFAULT NULL,
  cooking_indoor 			varchar(255) DEFAULT NULL,
  exacerbation_today 			varchar(255) DEFAULT NULL,
  asthma_severity 			varchar(255) DEFAULT NULL,
  copd 				varchar(255) DEFAULT NULL,
  other_diagnosis 			varchar(255) DEFAULT NULL,
  treatment_inhaled_b_agonist 	varchar(255) DEFAULT NULL,
  treatment_inhaled_b_agonist_dose		INT,
  treatment_inhaled_b_agonist_dosing_unit VARCHAR(50),
  treatment_inhaled_b_agonist_route		VARCHAR(50),
  treatment_inhaled_b_agonist_frequency		VARCHAR(50),
  treatment_inhaled_b_agonist_duration   INT,
  treatment_inhaled_b_agonist_duration_units  VARCHAR(50),
  treatment_inhaled_steriod 		varchar(255) DEFAULT NULL,
  treatment_inhaled_steriod_dose		INT,
  treatment_inhaled_steriod_dosing_unit VARCHAR(50),
  treatment_inhaled_steriod_route		VARCHAR(50),
  treatment_inhaled_steriod_frequency		VARCHAR(50),
  treatment_inhaled_steriod_duration   INT,
  treatment_inhaled_steriod_duration_units  VARCHAR(50),
  treatment_oral_steroid 		varchar(255) DEFAULT NULL,
  treatment_oral_steroid_dose		INT,
  treatment_oral_steroid_dosing_unit VARCHAR(50),
  treatment_oral_steroid_route		VARCHAR(50),
  treatment_oral_steroid_frequency		VARCHAR(50),
  treatment_oral_steroid_duration   INT,
  treatment_oral_steroid_duration_units  VARCHAR(50),
  other_treatment 			varchar(255) DEFAULT NULL,
  other_treatment_dose		INT,
  other_treatment_dosing_unit VARCHAR(50),
  other_treatment_route		VARCHAR(50),
  other_treatment_frequency		VARCHAR(50),
  other_treatment_duration   INT,
  other_treatment_duration_units  VARCHAR(50),
  comments 				varchar(255) DEFAULT NULL,
  next_appointment_date		date,
  PRIMARY KEY (asthma_followup_visit_id)
);

INSERT INTO mw_asthma_followup
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Asthma classification' THEN o.value_coded END) as asthma_severity,
    MAX(CASE WHEN o.concept = 'Location of cooking' THEN o.value_coded END) as cooking_indoor,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Chronic obstructive pulmonary disease' THEN o.value_coded END) as copd,
    MAX(CASE WHEN o.concept = 'Daytime symptom frequency' THEN o.value_numeric END) as day_symptoms,
    MAX(CASE WHEN o.concept = 'Asthma exacerbation today' THEN o.value_coded END) as exacerbation_today,
    MAX(CASE WHEN o.concept = 'Height (cm)' THEN o.value_numeric END) as height,
    MAX(CASE WHEN o.concept = 'Inhaler use per day' THEN o.value_numeric END) as inhaler_use_frequency_daily,
    MAX(CASE WHEN o.concept = 'Inhaler use per month' THEN o.value_numeric END) as inhaler_use_frequency_monthly,
    MAX(CASE WHEN o.concept = 'Inhaler use per week' THEN o.value_numeric END) as inhaler_use_frequency_weekly,
    MAX(CASE WHEN o.concept = 'Number of times inhaler is used in a year' THEN o.value_numeric END) as inhaler_use_frequency_yearly,
    MAX(CASE WHEN o.concept = 'Nighttime symptom frequency' THEN o.value_numeric END) as night_symptoms,
    MAX(CASE WHEN o.concept = 'Number of cigarettes smoked per day' THEN o.value_numeric END) as number_of_cigarettes_per_day,
    MAX(CASE WHEN o.concept = 'Other diagnosis' THEN o.value_text END) as other_diagnosis,
    MAX(CASE WHEN o.concept = 'Exposed to second hand smoke?' THEN o.value_coded END) as passive_smoking,
    MAX(CASE WHEN o.concept = 'Scheduled visit' THEN o.value_coded END) as planned_visit,
    MAX(CASE WHEN o.concept = 'Daily inhaled steroid use' THEN o.value_coded END) as steroid_inhaler_daily,
    MAX(CASE WHEN o.concept = 'Chronic lung disease treatment' AND o.value_coded = 'Beta-agonists (inhaled)' THEN o.value_coded END) as treatment_inhaled_b_agonist,
    MAX(CASE WHEN o.concept = 'Weight (kg)' THEN o.value_numeric END) as weight,
    MAX(CASE WHEN o.concept = 'Clinical impression comments' THEN o.value_text END) as comments,
    MAX(CASE WHEN o.concept = 'Appointment date' THEN o.value_date END) as next_appointment_date,
    MAX(CASE WHEN o.concept = 'Chronic lung disease treatment' AND o.value_coded = 'Other non-coded' THEN o.value_coded END) as other_treatment,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as treatment_inhaled_b_agonist_frequency,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as treatment_inhaled_b_agonist_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as treatment_inhaled_b_agonist_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as treatment_inhaled_b_agonist_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as treatment_inhaled_b_agonist_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as treatment_inhaled_b_agonist_route,
    MAX(CASE WHEN o.concept = 'Chronic lung disease treatment' AND o.value_coded = 'Inhaled steroid' THEN o.value_coded END) as treatment_inhaled_steriod,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as treatment_inhaled_steriod_frequency,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as treatment_inhaled_steriod_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as treatment_inhaled_steriod_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as treatment_inhaled_steriod_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as treatment_inhaled_steriod_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as treatment_inhaled_steriod_route,
    MAX(CASE WHEN o.concept = 'Chronic lung disease treatment' AND o.value_coded = 'Oral steroid' THEN o.value_coded END) as treatment_oral_steroid,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as treatment_oral_steroid_frequency,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as treatment_oral_steroid_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as treatment_oral_steroid_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as treatment_oral_steroid_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as treatment_oral_steroid_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as treatment_oral_steroid_route,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as other_treatment_frequency,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as other_treatment_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as other_treatment_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as other_treatment_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as other_treatment_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as other_treatment_route
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('ASTHMA_FOLLOWUP')
GROUP BY e.patient_id, e.encounter_date, e.location;