-- Derivation script for mw_art_initial
-- Generated from Pentaho transform: import-into-mw-art-initial.ktr

drop table if exists mw_art_initial;
create table mw_art_initial (
  art_initial_visit_id 			int not null auto_increment,
  patient_id    				int not null,
  visit_date            			date,
  location              			varchar(255),
  who_clinical_conditions 			varchar(255),
  clinical_stage 				varchar(255),
  presumed_hiv_severe_present			varchar(255),
  tb_status 					varchar(255),
  cd4_count					int,
  cd4_percentage				decimal(6,2),
  ks_side_effects_worsening_on_arvs  		varchar(255),
  cd4_date					date,
  link_id                                       varchar(255),
  tb_xpert                                      varchar(255),
  tb_xpert_date                                 date,
  urine_lam                                     varchar(255),
  urine_lam_date                                date,
  crag_results                                  varchar(255),
  crag_test_date                                date,
  pregnant_or_lactating			varchar(255),
  height					decimal(10,2),
  weight					decimal(10,2),
  ever_taken_arvs				varchar(255),
  age_at_initiation				int,
  last_arvs_taken				varchar(255),
  last_arvs_taken_date				varchar(255),
  confirmatory_test_location   		varchar(255),
  confirmatory_test_date			date,
  confirmatory_test_type 			varchar(255),
  art_education_done				varchar(255),
  art_education_date				date,
  tb_registration_number			varchar(255),
  tb_treatment_start_date			date,
  art_first_line_regimen			varchar(255),
  art_first_line_regimen_start_date		date,
  art_alternative_first_line_regimen		varchar(255),
  art_alternative_first_line_regimen_date	date,
  art_second_line_regimen			varchar(255),
  art_second_line_regimen_start_date		date,
  transfer_in_date				date,
  child_hcc_no					varchar(255),
     primary key (art_initial_visit_id)
);

insert into mw_art_initial
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Date of starting 2nd line ARV regimen' then o.value_date end) as art_second_line_regimen_start_date,
    max(case when o.concept = 'Date of starting alternative 1st line ARV regimen' then o.value_date end) as art_alternative_first_line_regimen_date,
    max(case when o.concept = 'Malawi Antiretroviral drugs change 2' then o.value_coded end) as art_alternative_first_line_regimen,
    max(case when o.concept = 'Malawi Antiretroviral drugs change 1' then o.value_coded end) as art_first_line_regimen,
    max(case when o.concept = 'Start date 1st line ARV' then o.value_date end) as art_first_line_regimen_start_date,
    max(case when o.concept = 'Malawi Antiretroviral drugs change 3' then o.value_coded end) as art_second_line_regimen,
    max(case when o.concept = 'ART education date' then o.value_date end) as art_education_date,
    max(case when o.concept = 'ARV education done' then o.value_coded end) as art_education_done,
    max(case when o.concept = 'Age' then o.value_numeric end) as age_at_initiation,
    max(case when o.concept = 'CD4 count' then o.value_numeric end) as cd4_count,
    max(case when o.concept = 'Date of CD4 count' then o.value_date end) as cd4_date,
    max(case when o.concept = 'Cd4%' then o.value_numeric end) as cd4_percentage,
    max(case when o.concept = 'Child HCC Registration Number' then o.value_text end) as child_hcc_no,
    max(case when o.concept = 'WHO stage' then o.value_coded end) as clinical_stage,
    max(case when o.concept = 'Date of HIV diagnosis' then o.value_date end) as confirmatory_test_date,
    max(case when o.concept = 'Confirmatory HIV test location' then o.value_text end) as confirmatory_test_location,
    max(case when o.concept = 'First positive HIV test type' then o.value_coded end) as confirmatory_test_type,
    max(case when o.concept = 'CrAg Results' then o.value_coded end) as crag_results,
    max(case when o.concept = 'Date of CrAg test' then o.value_date end) as crag_test_date,
    max(case when o.concept = 'Ever received ART?' then o.value_coded end) as ever_taken_arvs,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = 'Kaposis sarcoma side effects worsening while on ARVs?' then o.value_coded end) as ks_side_effects_worsening_on_arvs,
    max(case when o.concept = 'Last antiretroviral drugs taken' then o.value_text end) as last_arvs_taken,
    max(case when o.concept = 'Date ART last taken' then o.value_date end) as last_arvs_taken_date,
    max(case when o.concept = 'Linkage to Care ID' then o.value_text end) as link_id,
    max(case when o.concept = 'Pregnant/Lactating' then o.value_coded end) as pregnant_or_lactating,
    max(case when o.concept = 'Presumed severe HIV criteria present' then o.value_coded end) as presumed_hiv_severe_present,
    max(case when o.concept = 'TB registration number' then o.value_text end) as tb_registration_number,
    max(case when o.concept = 'Tuberculosis treatment status' then o.value_coded end) as tb_status,
    max(case when o.concept = 'Tuberculosis drug treatment start date' then o.value_date end) as tb_treatment_start_date,
    max(case when o.concept = 'TB Xpert' then o.value_coded end) as tb_xpert,
    max(case when o.concept = 'Date of TB Xpert test' then o.value_date end) as tb_xpert_date,
    max(case when o.concept = 'Transfer in date' then o.value_date end) as transfer_in_date,
    max(case when o.concept = 'Urine LAM / CrAg Result' then o.value_coded end) as urine_lam,
    max(case when o.concept = 'Date of Urine Lam' then o.value_date end) as urine_lam_date,
    max(case when o.concept = 'Clinical Conditions Text' then o.value_text end) as who_clinical_conditions,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('ART_INITIAL')
group by e.patient_id, e.encounter_date, e.location;