-- Derivation script for mw_asthma_followup
-- Generated from Pentaho transform: import-into-mw-asthma-followup.ktr

drop table if exists mw_asthma_followup;
create table mw_asthma_followup (
  asthma_followup_visit_id 		int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  planned_visit 			varchar(255) default null,
  height 				int default null,
  weight 				int default null,
  day_symptoms 			int default null,
  night_symptoms 			int default null,
  inhaler_use_frequency_daily 	int default null,
  inhaler_use_frequency_weekly 	int default null,
  inhaler_use_frequency_monthly 	int default null,
  inhaler_use_frequency_yearly 	int default null,
  steroid_inhaler_daily 		varchar(255) default null,
  number_of_cigarettes_per_day 	int default null,
  passive_smoking 			varchar(255) default null,
  cooking_indoor 			varchar(255) default null,
  exacerbation_today 			varchar(255) default null,
  asthma_severity 			varchar(255) default null,
  copd 				varchar(255) default null,
  other_diagnosis 			varchar(255) default null,
  treatment_inhaled_b_agonist 	varchar(255) default null,
  treatment_inhaled_b_agonist_dose		int,
  treatment_inhaled_b_agonist_dosing_unit varchar(50),
  treatment_inhaled_b_agonist_route		varchar(50),
  treatment_inhaled_b_agonist_frequency		varchar(50),
  treatment_inhaled_b_agonist_duration   int,
  treatment_inhaled_b_agonist_duration_units  varchar(50),
  treatment_inhaled_steriod 		varchar(255) default null,
  treatment_inhaled_steriod_dose		int,
  treatment_inhaled_steriod_dosing_unit varchar(50),
  treatment_inhaled_steriod_route		varchar(50),
  treatment_inhaled_steriod_frequency		varchar(50),
  treatment_inhaled_steriod_duration   int,
  treatment_inhaled_steriod_duration_units  varchar(50),
  treatment_oral_steroid 		varchar(255) default null,
  treatment_oral_steroid_dose		int,
  treatment_oral_steroid_dosing_unit varchar(50),
  treatment_oral_steroid_route		varchar(50),
  treatment_oral_steroid_frequency		varchar(50),
  treatment_oral_steroid_duration   int,
  treatment_oral_steroid_duration_units  varchar(50),
  other_treatment 			varchar(255) default null,
  other_treatment_dose		int,
  other_treatment_dosing_unit varchar(50),
  other_treatment_route		varchar(50),
  other_treatment_frequency		varchar(50),
  other_treatment_duration   int,
  other_treatment_duration_units  varchar(50),
  comments 				varchar(255) default null,
  next_appointment_date		date,
  primary key (asthma_followup_visit_id)
);

insert into mw_asthma_followup
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Asthma classification' then o.value_coded end) as asthma_severity,
    max(case when o.concept = 'Location of cooking' then o.value_coded end) as cooking_indoor,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Chronic obstructive pulmonary disease' then o.value_coded end) as copd,
    max(case when o.concept = 'Daytime symptom frequency' then o.value_numeric end) as day_symptoms,
    max(case when o.concept = 'Asthma exacerbation today' then o.value_coded end) as exacerbation_today,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = 'Inhaler use per day' then o.value_numeric end) as inhaler_use_frequency_daily,
    max(case when o.concept = 'Inhaler use per month' then o.value_numeric end) as inhaler_use_frequency_monthly,
    max(case when o.concept = 'Inhaler use per week' then o.value_numeric end) as inhaler_use_frequency_weekly,
    max(case when o.concept = 'Number of times inhaler is used in a year' then o.value_numeric end) as inhaler_use_frequency_yearly,
    max(case when o.concept = 'Nighttime symptom frequency' then o.value_numeric end) as night_symptoms,
    max(case when o.concept = 'Number of cigarettes smoked per day' then o.value_numeric end) as number_of_cigarettes_per_day,
    max(case when o.concept = 'Other diagnosis' then o.value_text end) as other_diagnosis,
    max(case when o.concept = 'Exposed to second hand smoke?' then o.value_coded end) as passive_smoking,
    max(case when o.concept = 'Scheduled visit' then o.value_coded end) as planned_visit,
    max(case when o.concept = 'Daily inhaled steroid use' then o.value_coded end) as steroid_inhaler_daily,
    max(case when o.concept = 'Chronic lung disease treatment' and o.value_coded = 'Beta-agonists (inhaled)' then o.value_coded end) as treatment_inhaled_b_agonist,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight,
    max(case when o.concept = 'Clinical impression comments' then o.value_text end) as comments,
    max(case when o.concept = 'Appointment date' then o.value_date end) as next_appointment_date,
    max(case when o.concept = 'Chronic lung disease treatment' and o.value_coded = 'Other non-coded' then o.value_coded end) as other_treatment,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as treatment_inhaled_b_agonist_frequency,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as treatment_inhaled_b_agonist_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as treatment_inhaled_b_agonist_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as treatment_inhaled_b_agonist_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as treatment_inhaled_b_agonist_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as treatment_inhaled_b_agonist_route,
    max(case when o.concept = 'Chronic lung disease treatment' and o.value_coded = 'Inhaled steroid' then o.value_coded end) as treatment_inhaled_steriod,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as treatment_inhaled_steriod_frequency,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as treatment_inhaled_steriod_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as treatment_inhaled_steriod_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as treatment_inhaled_steriod_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as treatment_inhaled_steriod_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as treatment_inhaled_steriod_route,
    max(case when o.concept = 'Chronic lung disease treatment' and o.value_coded = 'Oral steroid' then o.value_coded end) as treatment_oral_steroid,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as treatment_oral_steroid_frequency,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as treatment_oral_steroid_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as treatment_oral_steroid_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as treatment_oral_steroid_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as treatment_oral_steroid_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as treatment_oral_steroid_route,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as other_treatment_frequency,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as other_treatment_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as other_treatment_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as other_treatment_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as other_treatment_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as other_treatment_route
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('ASTHMA_FOLLOWUP')
group by e.patient_id, e.encounter_date, e.location;