-- Derivation script for mw_art_initial
-- Generated from Pentaho transform: import-into-mw-art-initial.ktr

DROP TABLE IF EXISTS mw_art_initial;
CREATE TABLE mw_art_initial (
  art_initial_visit_id 			INT NOT NULL AUTO_INCREMENT,
  patient_id    				INT NOT NULL,
  visit_date            			DATE,
  location              			VARCHAR(255),
  who_clinical_conditions 			VARCHAR(255),
  clinical_stage 				VARCHAR(255),
  presumed_hiv_severe_present			VARCHAR(255),
  tb_status 					VARCHAR(255),
  cd4_count					INT,
  cd4_percentage				DECIMAL(6,2),
  ks_side_effects_worsening_on_arvs  		VARCHAR(255),
  cd4_date					DATE,
  link_id                                       VARCHAR(255),
  tb_xpert                                      VARCHAR(255),
  tb_xpert_date                                 DATE,
  urine_lam                                     VARCHAR(255),
  urine_lam_date                                DATE,
  crag_results                                  VARCHAR(255),
  crag_test_date                                DATE,
  pregnant_or_lactating			VARCHAR(255),
  height					DECIMAL(10,2),
  weight					DECIMAL(10,2),
  ever_taken_arvs				VARCHAR(255),
  age_at_initiation				INT,
  last_arvs_taken				VARCHAR(255),
  last_arvs_taken_date				VARCHAR(255),
  confirmatory_test_location   		VARCHAR(255),
  confirmatory_test_date			DATE,
  confirmatory_test_type 			VARCHAR(255),
  art_education_done				VARCHAR(255),
  art_education_date				DATE,
  tb_registration_number			VARCHAR(255),
  tb_treatment_start_date			DATE,
  art_first_line_regimen			VARCHAR(255),
  art_first_line_regimen_start_date		DATE,
  art_alternative_first_line_regimen		VARCHAR(255),
  art_alternative_first_line_regimen_date	DATE,
  art_second_line_regimen			VARCHAR(255),
  art_second_line_regimen_start_date		DATE,
  transfer_in_date				DATE,
  child_hcc_no					VARCHAR(255),
     PRIMARY KEY (art_initial_visit_id)
);

INSERT INTO mw_art_initial
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Date of starting 2nd line ARV regimen' THEN o.value_date END) as art_second_line_regimen_start_date,
    MAX(CASE WHEN o.concept = 'Date of starting alternative 1st line ARV regimen' THEN o.value_date END) as art_alternative_first_line_regimen_date,
    MAX(CASE WHEN o.concept = 'Malawi Antiretroviral drugs change 2' THEN o.value_coded END) as art_alternative_first_line_regimen,
    MAX(CASE WHEN o.concept = 'Malawi Antiretroviral drugs change 1' THEN o.value_coded END) as art_first_line_regimen,
    MAX(CASE WHEN o.concept = 'Start date 1st line ARV' THEN o.value_date END) as art_first_line_regimen_start_date,
    MAX(CASE WHEN o.concept = 'Malawi Antiretroviral drugs change 3' THEN o.value_coded END) as art_second_line_regimen,
    MAX(CASE WHEN o.concept = 'ART education date' THEN o.value_date END) as art_education_date,
    MAX(CASE WHEN o.concept = 'ARV education done' THEN o.value_coded END) as art_education_done,
    MAX(CASE WHEN o.concept = 'Age' THEN o.value_numeric END) as age_at_initiation,
    MAX(CASE WHEN o.concept = 'CD4 count' THEN o.value_numeric END) as cd4_count,
    MAX(CASE WHEN o.concept = 'Date of CD4 count' THEN o.value_date END) as cd4_date,
    MAX(CASE WHEN o.concept = 'Cd4%' THEN o.value_numeric END) as cd4_percentage,
    MAX(CASE WHEN o.concept = 'Child HCC Registration Number' THEN o.value_text END) as child_hcc_no,
    MAX(CASE WHEN o.concept = 'WHO stage' THEN o.value_coded END) as clinical_stage,
    MAX(CASE WHEN o.concept = 'Date of HIV diagnosis' THEN o.value_date END) as confirmatory_test_date,
    MAX(CASE WHEN o.concept = 'Confirmatory HIV test location' THEN o.value_text END) as confirmatory_test_location,
    MAX(CASE WHEN o.concept = 'First positive HIV test type' THEN o.value_coded END) as confirmatory_test_type,
    MAX(CASE WHEN o.concept = 'CrAg Results' THEN o.value_coded END) as crag_results,
    MAX(CASE WHEN o.concept = 'Date of CrAg test' THEN o.value_date END) as crag_test_date,
    MAX(CASE WHEN o.concept = 'Ever received ART?' THEN o.value_coded END) as ever_taken_arvs,
    MAX(CASE WHEN o.concept = 'Height (cm)' THEN o.value_numeric END) as height,
    MAX(CASE WHEN o.concept = 'Kaposis sarcoma side effects worsening while on ARVs?' THEN o.value_coded END) as ks_side_effects_worsening_on_arvs,
    MAX(CASE WHEN o.concept = 'Last antiretroviral drugs taken' THEN o.value_text END) as last_arvs_taken,
    MAX(CASE WHEN o.concept = 'Date ART last taken' THEN o.value_date END) as last_arvs_taken_date,
    MAX(CASE WHEN o.concept = 'Linkage to Care ID' THEN o.value_text END) as link_id,
    MAX(CASE WHEN o.concept = 'Pregnant/Lactating' THEN o.value_coded END) as pregnant_or_lactating,
    MAX(CASE WHEN o.concept = 'Presumed severe HIV criteria present' THEN o.value_coded END) as presumed_hiv_severe_present,
    MAX(CASE WHEN o.concept = 'TB registration number' THEN o.value_text END) as tb_registration_number,
    MAX(CASE WHEN o.concept = 'Tuberculosis treatment status' THEN o.value_coded END) as tb_status,
    MAX(CASE WHEN o.concept = 'Tuberculosis drug treatment start date' THEN o.value_date END) as tb_treatment_start_date,
    MAX(CASE WHEN o.concept = 'TB Xpert' THEN o.value_coded END) as tb_xpert,
    MAX(CASE WHEN o.concept = 'Date of TB Xpert test' THEN o.value_date END) as tb_xpert_date,
    MAX(CASE WHEN o.concept = 'Transfer in date' THEN o.value_date END) as transfer_in_date,
    MAX(CASE WHEN o.concept = 'Urine LAM / CrAg Result' THEN o.value_coded END) as urine_lam,
    MAX(CASE WHEN o.concept = 'Date of Urine Lam' THEN o.value_date END) as urine_lam_date,
    MAX(CASE WHEN o.concept = 'Clinical Conditions Text' THEN o.value_text END) as who_clinical_conditions,
    MAX(CASE WHEN o.concept = 'Weight (kg)' THEN o.value_numeric END) as weight
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('ART_INITIAL')
GROUP BY e.patient_id, e.encounter_date, e.location;