-- Derivation script for mw_art_followup
-- Generated from Pentaho transform: import-into-mw-art-followup.ktr

drop table if exists mw_art_followup;
create table mw_art_followup (
  art_followup_visit_id 			int not null auto_increment,
  patient_id    				int not null,
  visit_date            			date,
  location              			varchar(255),
  next_appointment_date 			date,
  art_drugs_received 				varchar(255),
  pregnant_or_lactating			varchar(255),
  tb_status 					varchar(255),
  doses_missed					decimal(10,2),
  pill_count					int,
  no_side_effect				varchar(255),
  peripheral_neuropathy_side_effect		varchar(255),
  hepatitis_side_effect			varchar(255),
  skin_rash_side_effect			varchar(255),
  lipodystrophy_side_effect			varchar(255),
  other_side_effect				varchar(255),
  art_regimen					varchar(255),
  height					decimal(10,2),
  weight					decimal(10,2),
  arvs_given					int,
  arvs_given_to				varchar(255),
  ctx_960					varchar(255),
  ctx_960_pills		     		decimal(10,2),
  inh_300					varchar(255),
  inh_300_pills		     		decimal(10,2),
  rfp_150					varchar(255),
  rfp_150_pills		     		decimal(10,2),
  rfp_inh					varchar(255),
  rfp_inh_pills				decimal(10,2),
  pyridoxine					varchar(255),
  pyridoxine_pills		     		decimal(10,2),
  depo_given					varchar(255),
  systolic_bp		 			varchar(255),
  diastolic_bp					varchar(255),
  condoms_given				varchar(255),
     primary key (art_followup_visit_id)
);

insert into mw_art_followup
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Malawi Antiretroviral drugs received' then o.value_coded end) as art_regimen,
    max(case when o.concept = 'Responsible person present' then o.value_coded end) as arvs_given_to,
    max(case when o.concept = 'Appointment date' then o.value_date end) as next_appointment_date,
    max(case when o.concept = 'HIV Preventive Therapy' and o.value_coded = 'Trimethoprim and sulfamethoxazole' then o.value_coded end) as ctx_960,
    max(case when o.concept = 'Amount Dispensed' then o.value_numeric end) as ctx_960_pills,
    max(case when o.concept = 'Number of Condoms dispensed' then o.value_numeric end) as condoms_given,
    max(case when o.concept = 'Depo-Provera given' then o.value_coded end) as depo_given,
    max(case when o.concept = 'Diastolic blood pressure' then o.value_numeric end) as diastolic_bp,
    max(case when o.concept = 'Number of HIV drug doses missed' then o.value_numeric end) as doses_missed,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = 'HIV Preventive Therapy' and o.value_coded = 'Isoniazid' then o.value_coded end) as inh_300,
    max(case when o.concept = 'Amount Dispensed' then o.value_numeric end) as inh_300_pills,
    max(case when o.concept = 'Malawi Antiretroviral drugs received' then o.value_coded end) as art_drugs_received,
    max(case when o.concept = 'Number of antiretrovirals given' then o.value_numeric end) as arvs_given,
    max(case when o.concept = 'Amount of drug brought to clinic' then o.value_numeric end) as pill_count,
    max(case when o.concept = 'Pregnant/Lactating' then o.value_coded end) as pregnant_or_lactating,
    max(case when o.concept = 'HIV Preventive Therapy' and o.value_coded = 'Pyridoxine' then o.value_coded end) as pyridoxine,
    max(case when o.concept = 'Amount Dispensed' then o.value_numeric end) as pyridoxine_pills,
    max(case when o.concept = 'HIV Preventive Therapy' and o.value_coded = 'Rifapentine' then o.value_coded end) as rfp_150,
    max(case when o.concept = 'Amount Dispensed' then o.value_numeric end) as rfp_150_pills,
    max(case when o.concept = 'HIV Preventive Therapy' and o.value_coded = '3HP (Rifapentine and Isoniazid)' then o.value_coded end) as rfp_inh,
    max(case when o.concept = 'Amount Dispensed' then o.value_numeric end) as rfp_inh_pills,
    max(case when o.concept = 'Malawi ART side effects' and o.value_coded = 'No' then o.value_coded end) as no_side_effect,
    max(case when o.concept = 'Malawi ART side effects' and o.value_coded = 'Peripheral neuropathy' then o.value_coded end) as peripheral_neuropathy_side_effect,
    max(case when o.concept = 'Malawi ART side effects' and o.value_coded = 'Hepatitis' then o.value_coded end) as hepatitis_side_effect,
    max(case when o.concept = 'Malawi ART side effects' and o.value_coded = 'Skin rash' then o.value_coded end) as skin_rash_side_effect,
    max(case when o.concept = 'Malawi ART side effects' and o.value_coded = 'Lipodystrophy' then o.value_coded end) as lipodystrophy_side_effect,
    max(case when o.concept = 'Malawi ART side effects' and o.value_coded = 'Other' then o.value_coded end) as other_side_effect,
    max(case when o.concept = 'Systolic blood pressure' then o.value_numeric end) as systolic_bp,
    max(case when o.concept = 'TB status' then o.value_coded end) as tb_status,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('ART_FOLLOWUP')
group by e.patient_id, e.encounter_date, e.location;