-- Derivation script for mw_chf_followup
-- Generated from Pentaho transform: import-into-mw-chf-followup.ktr

drop table if exists mw_chf_followup;
create table mw_chf_followup (
  chf_followup_visit_id 			int not null auto_increment,
  patient_id 					int not null,
  visit_date 					date default null,
  location 					varchar(50) default null,
  height 					int default null,
  weight 					int default null,
  weight_change 				varchar(50) default null,
  bp_systolic 					int default null,
  bp_diastolic 				int default null,
  heart_rate 					int default null,
  spo2 					int default null,
  orthopnea 					varchar(50) default null,
  dyspnea_on_exertion 				varchar(50) default null,
  dry_cough 					varchar(50) default null,
  fatigue			 		varchar(50) default null,
  hospitalized_since_last_visit_for_ncd 	varchar(50) default null,
  oedema 					varchar(50) default null,
  bibasilar_crackles 				varchar(50) default null,
  jvp_elevated 				varchar(50) default null,
  volume_status 				varchar(50) default null,
  nyha_stage 					varchar(50) default null,
  alcohol 					varchar(50) default null,
  tobacco 					varchar(50) default null,
  salt_or_fluid_restricted 			varchar(50) default null,
  concern_for_depression_or_anxiety 		varchar(50) default null,
  aspirin 					varchar(50) default null,
  asprin_asa_dose		int,
  asprin_asa_dosing_unit varchar(50),
  asprin_asa_route		varchar(50),
  asprin_asa_frequency		varchar(50),
  asprin_asa_duration   int,
  asprin_asa_duration_units  varchar(50),
  diuretic_hctz 				varchar(50) default null,
  diuretic_hctz_dose		int,
  diuretic_hctz_dosing_unit varchar(50),
  diuretic_hctz_route		varchar(50),
  diuretic_hctz_frequency		varchar(50),
  diuretic_hctz_duration   int,
  diuretic_hctz_duration_units  varchar(50),
  diuretic_furo 				varchar(50) default null,
  diuretic_furp_dose		int,
  diuretic_furp_dosing_unit varchar(50),
  diuretic_furp_route		varchar(50),
  diuretic_furp_frequency		varchar(50),
  diuretic_furp_duration   int,
  diuretic_furp_duration_units  varchar(50),
  diuretic_spiro			 			varchar(50),
  diuretic_spiro_dose		int,
  diuretic_spiro_dosing_unit varchar(50),
  diuretic_spiro_route		varchar(50),
  diuretic_spiro_frequency		varchar(50),
  diuretic_spiro_duration   int,
  diuretic_spiro_duration_units  varchar(50),
  ace_i_enal				 			varchar(50),
  ace_i_enal_dose		int,
  ace_i_enal_dosing_unit varchar(50),
  ace_i_enal_route		varchar(50),
  ace_i_enal_frequency		varchar(50),
  ace_i_enal_duration   int,
  ace_i_enal_duration_units  varchar(50),
  ace_i_capt				 			varchar(50),
  ace_i_capt_dose		int,
  ace_i_capt_dosing_unit varchar(50),
  ace_i_capt_route		varchar(50),
  ace_i_capt_frequency		varchar(50),
  ace_i_capt_duration   int,
  ace_i_capt_duration_units  varchar(50),
  ace_i_lisin			 				varchar(50),
  ace_i_lisin_dose		int,
  ace_i_lisin_dosing_unit varchar(50),
  ace_i_lisin_route		varchar(50),
  ace_i_lisin_frequency		varchar(50),
  ace_i_lisin_duration   int,
  ace_i_lisin_duration_units  varchar(50),
  bb_aten				 			varchar(50),
  bb_aten_dose		int,
  bb_aten_dosing_unit varchar(50),
  bb_aten_route		varchar(50),
  bb_aten_frequency		varchar(50),
  bb_aten_duration   int,
  bb_aten_duration_units  varchar(50),
  bb_bis				 			varchar(50),
  bb_bis_dose		int,
  bb_bis_dosing_unit varchar(50),
  bb_bis_route		varchar(50),
  bb_bis_frequency		varchar(50),
  bb_bis_duration   int,
  bb_bis_duration_units  varchar(50),
  bb_prop				 			varchar(50),
  bb_prop_dose		int,
  bb_prop_dosing_unit varchar(50),
  bb_prop_route		varchar(50),
  bb_prop_frequency		varchar(50),
  bb_prop_duration   int,
  bb_prop_duration_units  varchar(50),
  ccb_aml				 			varchar(50),
  ccb_aml_dose		int,
  ccb_aml_dosing_unit varchar(50),
  ccb_aml_route		varchar(50),
  ccb_aml_frequency		varchar(50),
  ccb_aml_duration   int,
  ccb_aml_duration_units  varchar(50),
  ccb_nif				 			varchar(50),
  ccb_nif_dose		int,
  ccb_nif_dosing_unit varchar(50),
  ccb_nif_route		varchar(50),
  ccb_nif_frequency		varchar(50),
  ccb_nif_duration   int,
  ccb_nif_duration_units  varchar(50),
  benzathine 					varchar(50) default null,
  benzathine_dose		int,
  benzathine_dosing_unit varchar(50),
  benzathine_route		varchar(50),
  benzathine_frequency		varchar(50),
  benzathine_duration   int,
  benzathine_duration_units  varchar(50),
  other_medications 				varchar(50) default null,
  took_medications_today 			varchar(50) default null,
  diet_salt_or_fluid 				varchar(50) default null,
  mental_health_referral 			varchar(50) default null,
  palliative_referral 				varchar(50) default null,
  request_chw_f_u 				varchar(50) default null,
  next_appointment_date 			date default null,
  primary key (chf_followup_visit_id)
) ;

drop temporary table if exists temp_chf_followup_obs;
create temporary table temp_chf_followup_obs as
select encounter_id, obs_group_id, concept, value_coded, value_numeric, value_date, value_text
from omrs_obs
where encounter_type = 'CHF_FOLLOWUP';
alter table temp_chf_followup_obs add index temp_chf_followup_obs_concept_idx (concept);
alter table temp_chf_followup_obs add index temp_chf_followup_obs_encounter_idx (encounter_id);
alter table temp_chf_followup_obs add index temp_chf_followup_obs_group_idx (obs_group_id);

-- Build temp_medications in three steps to avoid a full scan of the ~20M-row omrs_obs table.
-- Step 1: pull only the drug-name obs for this encounter type (~20M rows → small set).
-- Step 2: pull only the detail obs whose obs_group_id appears in step 1 (indexed lookup).
-- Step 3: join the two small tables to produce one row per drug per encounter.
drop temporary table if exists temp_drug_name_obs;
create temporary table temp_drug_name_obs as
select obs_id, encounter_id, obs_group_id, value_coded as drug_name
from temp_chf_followup_obs
where concept = 'Current drugs used';
alter table temp_drug_name_obs add index temp_drug_name_obs_group_idx (obs_group_id);
alter table temp_drug_name_obs add index temp_drug_name_obs_encounter_idx (encounter_id);

drop temporary table if exists temp_drug_detail_obs;
create temporary table temp_drug_detail_obs as
select obs_group_id, concept, value_coded, value_numeric
from temp_chf_followup_obs
where obs_group_id in (select obs_group_id from temp_drug_name_obs)
  and concept in ('Drug frequency coded', 'Quantity of medication prescribed per dose',
                  'Dosing unit', 'Routes of administration (coded)',
                  'Medication duration', 'Time units');
alter table temp_drug_detail_obs add index temp_drug_detail_obs_group_idx (obs_group_id);

drop temporary table if exists temp_medications;
create temporary table temp_medications as
select
    t.encounter_id,
    t.drug_name,
    max(case when d.concept = 'Drug frequency coded' then d.value_coded end)                         as frequency,
    max(case when d.concept = 'Quantity of medication prescribed per dose' then d.value_numeric end) as dose,
    max(case when d.concept = 'Dosing unit' then d.value_coded end)                                  as dosing_unit,
    max(case when d.concept = 'Routes of administration (coded)' then d.value_coded end)             as route,
    max(case when d.concept = 'Medication duration' then d.value_numeric end)                        as duration,
    max(case when d.concept = 'Time units' then d.value_coded end)                                   as duration_units
from temp_drug_name_obs t
join temp_drug_detail_obs d on d.obs_group_id = t.obs_group_id
group by t.encounter_id, t.obs_group_id, t.drug_name;
alter table temp_medications add index temp_medications_encounter_idx (encounter_id);
alter table temp_medications add index temp_medications_drug_idx (drug_name);

drop temporary table if exists temp_med_values;
create temporary table temp_med_values as
select
    encounter_id,
    max(case when drug_name = 'Aspirin'              then dose         end) as asprin_asa_dose,
    max(case when drug_name = 'Aspirin'              then dosing_unit  end) as asprin_asa_dosing_unit,
    max(case when drug_name = 'Aspirin'              then route        end) as asprin_asa_route,
    max(case when drug_name = 'Aspirin'              then frequency    end) as asprin_asa_frequency,
    max(case when drug_name = 'Aspirin'              then duration     end) as asprin_asa_duration,
    max(case when drug_name = 'Aspirin'              then duration_units end) as asprin_asa_duration_units,
    max(case when drug_name = 'Hydrochlorothiazide'  then dose         end) as diuretic_hctz_dose,
    max(case when drug_name = 'Hydrochlorothiazide'  then dosing_unit  end) as diuretic_hctz_dosing_unit,
    max(case when drug_name = 'Hydrochlorothiazide'  then route        end) as diuretic_hctz_route,
    max(case when drug_name = 'Hydrochlorothiazide'  then frequency    end) as diuretic_hctz_frequency,
    max(case when drug_name = 'Hydrochlorothiazide'  then duration     end) as diuretic_hctz_duration,
    max(case when drug_name = 'Hydrochlorothiazide'  then duration_units end) as diuretic_hctz_duration_units,
    max(case when drug_name = 'Furosemide'           then dose         end) as diuretic_furp_dose,
    max(case when drug_name = 'Furosemide'           then dosing_unit  end) as diuretic_furp_dosing_unit,
    max(case when drug_name = 'Furosemide'           then route        end) as diuretic_furp_route,
    max(case when drug_name = 'Furosemide'           then frequency    end) as diuretic_furp_frequency,
    max(case when drug_name = 'Furosemide'           then duration     end) as diuretic_furp_duration,
    max(case when drug_name = 'Furosemide'           then duration_units end) as diuretic_furp_duration_units,
    max(case when drug_name = 'Spironolactone'       then dose         end) as diuretic_spiro_dose,
    max(case when drug_name = 'Spironolactone'       then dosing_unit  end) as diuretic_spiro_dosing_unit,
    max(case when drug_name = 'Spironolactone'       then route        end) as diuretic_spiro_route,
    max(case when drug_name = 'Spironolactone'       then frequency    end) as diuretic_spiro_frequency,
    max(case when drug_name = 'Spironolactone'       then duration     end) as diuretic_spiro_duration,
    max(case when drug_name = 'Spironolactone'       then duration_units end) as diuretic_spiro_duration_units,
    max(case when drug_name = 'Enalapril'            then dose         end) as ace_i_enal_dose,
    max(case when drug_name = 'Enalapril'            then dosing_unit  end) as ace_i_enal_dosing_unit,
    max(case when drug_name = 'Enalapril'            then route        end) as ace_i_enal_route,
    max(case when drug_name = 'Enalapril'            then frequency    end) as ace_i_enal_frequency,
    max(case when drug_name = 'Enalapril'            then duration     end) as ace_i_enal_duration,
    max(case when drug_name = 'Enalapril'            then duration_units end) as ace_i_enal_duration_units,
    max(case when drug_name = 'Captopril'            then dose         end) as ace_i_capt_dose,
    max(case when drug_name = 'Captopril'            then dosing_unit  end) as ace_i_capt_dosing_unit,
    max(case when drug_name = 'Captopril'            then route        end) as ace_i_capt_route,
    max(case when drug_name = 'Captopril'            then frequency    end) as ace_i_capt_frequency,
    max(case when drug_name = 'Captopril'            then duration     end) as ace_i_capt_duration,
    max(case when drug_name = 'Captopril'            then duration_units end) as ace_i_capt_duration_units,
    max(case when drug_name = 'Lisinopril'           then dose         end) as ace_i_lisin_dose,
    max(case when drug_name = 'Lisinopril'           then dosing_unit  end) as ace_i_lisin_dosing_unit,
    max(case when drug_name = 'Lisinopril'           then route        end) as ace_i_lisin_route,
    max(case when drug_name = 'Lisinopril'           then frequency    end) as ace_i_lisin_frequency,
    max(case when drug_name = 'Lisinopril'           then duration     end) as ace_i_lisin_duration,
    max(case when drug_name = 'Lisinopril'           then duration_units end) as ace_i_lisin_duration_units,
    max(case when drug_name = 'Atenolol'             then dose         end) as bb_aten_dose,
    max(case when drug_name = 'Atenolol'             then dosing_unit  end) as bb_aten_dosing_unit,
    max(case when drug_name = 'Atenolol'             then route        end) as bb_aten_route,
    max(case when drug_name = 'Atenolol'             then frequency    end) as bb_aten_frequency,
    max(case when drug_name = 'Atenolol'             then duration     end) as bb_aten_duration,
    max(case when drug_name = 'Atenolol'             then duration_units end) as bb_aten_duration_units,
    max(case when drug_name = 'Bisoprolol'           then dose         end) as bb_bis_dose,
    max(case when drug_name = 'Bisoprolol'           then dosing_unit  end) as bb_bis_dosing_unit,
    max(case when drug_name = 'Bisoprolol'           then route        end) as bb_bis_route,
    max(case when drug_name = 'Bisoprolol'           then frequency    end) as bb_bis_frequency,
    max(case when drug_name = 'Bisoprolol'           then duration     end) as bb_bis_duration,
    max(case when drug_name = 'Bisoprolol'           then duration_units end) as bb_bis_duration_units,
    max(case when drug_name = 'Propranolol'          then dose         end) as bb_prop_dose,
    max(case when drug_name = 'Propranolol'          then dosing_unit  end) as bb_prop_dosing_unit,
    max(case when drug_name = 'Propranolol'          then route        end) as bb_prop_route,
    max(case when drug_name = 'Propranolol'          then frequency    end) as bb_prop_frequency,
    max(case when drug_name = 'Propranolol'          then duration     end) as bb_prop_duration,
    max(case when drug_name = 'Propranolol'          then duration_units end) as bb_prop_duration_units,
    max(case when drug_name = 'Amlodipine'           then dose         end) as ccb_aml_dose,
    max(case when drug_name = 'Amlodipine'           then dosing_unit  end) as ccb_aml_dosing_unit,
    max(case when drug_name = 'Amlodipine'           then route        end) as ccb_aml_route,
    max(case when drug_name = 'Amlodipine'           then frequency    end) as ccb_aml_frequency,
    max(case when drug_name = 'Amlodipine'           then duration     end) as ccb_aml_duration,
    max(case when drug_name = 'Amlodipine'           then duration_units end) as ccb_aml_duration_units,
    max(case when drug_name = 'Nifedipine'           then dose         end) as ccb_nif_dose,
    max(case when drug_name = 'Nifedipine'           then dosing_unit  end) as ccb_nif_dosing_unit,
    max(case when drug_name = 'Nifedipine'           then route        end) as ccb_nif_route,
    max(case when drug_name = 'Nifedipine'           then frequency    end) as ccb_nif_frequency,
    max(case when drug_name = 'Nifedipine'           then duration     end) as ccb_nif_duration,
    max(case when drug_name = 'Nifedipine'           then duration_units end) as ccb_nif_duration_units,
    max(case when drug_name = 'Benzathine penicillin' then dose        end) as benzathine_dose,
    max(case when drug_name = 'Benzathine penicillin' then dosing_unit end) as benzathine_dosing_unit,
    max(case when drug_name = 'Benzathine penicillin' then route       end) as benzathine_route,
    max(case when drug_name = 'Benzathine penicillin' then frequency   end) as benzathine_frequency,
    max(case when drug_name = 'Benzathine penicillin' then duration    end) as benzathine_duration,
    max(case when drug_name = 'Benzathine penicillin' then duration_units end) as benzathine_duration_units
from temp_medications
group by encounter_id;
alter table temp_med_values add index temp_med_values_encounter_idx (encounter_id);

drop temporary table if exists temp_single_values;
create temporary table temp_single_values as
select
    encounter_id,
    max(case when concept = 'Current drugs used' and value_coded = 'Captopril'           then value_coded end) as ace_i_capt,
    max(case when concept = 'Current drugs used' and value_coded = 'Enalapril'           then value_coded end) as ace_i_enal,
    max(case when concept = 'Current drugs used' and value_coded = 'Lisinopril'          then value_coded end) as ace_i_lisin,
    max(case when concept = 'History of alcohol use'                                     then value_coded end) as alcohol,
    max(case when concept = 'Current drugs used' and value_coded = 'Aspirin'             then value_coded end) as aspirin,
    max(case when concept = 'Current drugs used' and value_coded = 'Atenolol'            then value_coded end) as bb_aten,
    max(case when concept = 'Current drugs used' and value_coded = 'Bisoprolol'          then value_coded end) as bb_bis,
    max(case when concept = 'Current drugs used' and value_coded = 'Propranolol'         then value_coded end) as bb_prop,
    max(case when concept = 'Current drugs used' and value_coded = 'Benzathine penicillin' then value_coded end) as benzathine,
    max(case when concept = 'Bibasilar crackles'                                         then value_coded end) as bibasilar_crackles,
    max(case when concept = 'Diastolic blood pressure'                                   then value_numeric end) as bp_diastolic,
    max(case when concept = 'Systolic blood pressure'                                    then value_numeric end) as bp_systolic,
    max(case when concept = 'Current drugs used' and value_coded = 'Amlodipine'          then value_coded end) as ccb_aml,
    max(case when concept = 'Current drugs used' and value_coded = 'Nifedipine'          then value_coded end) as ccb_nif,
    max(case when concept = 'Concern for depression or anxiety'                          then value_coded end) as concern_for_depression_or_anxiety,
    max(case when concept = 'Low salt diet recommended'                                  then value_coded end) as diet_salt_or_fluid,
    max(case when concept = 'Current drugs used' and value_coded = 'Furosemide'          then value_coded end) as diuretic_furo,
    max(case when concept = 'Current drugs used' and value_coded = 'Hydrochlorothiazide' then value_coded end) as diuretic_hctz,
    max(case when concept = 'Current drugs used' and value_coded = 'Spironolactone'      then value_coded end) as diuretic_spiro,
    max(case when concept = 'Level of dry cough'                                         then value_coded end) as dry_cough,
    max(case when concept = 'Dyspnea on extertion'                                       then value_coded end) as dyspnea_on_exertion,
    max(case when concept = 'Level of fatigue'                                           then value_coded end) as fatigue,
    max(case when concept = 'Pulse'                                                      then value_numeric end) as heart_rate,
    max(case when concept = 'Height (cm)'                                                then value_numeric end) as height,
    max(case when concept = 'Hospitalized for non-communicable disease since last visit' then value_coded end) as hospitalized_since_last_visit_for_ncd,
    max(case when concept = 'Jugular venous pressure elevated'                           then value_coded end) as jvp_elevated,
    max(case when concept = 'Mental health referral'                                     then value_coded end) as mental_health_referral,
    max(case when concept = 'Appointment date'                                           then value_date  end) as next_appointment_date,
    max(case when concept = 'Nyha class'                                                 then value_coded end) as nyha_stage,
    max(case when concept = 'Oedema'                                                     then value_coded end) as oedema,
    max(case when concept = 'Level of orthopnea'                                         then value_coded end) as orthopnea,
    max(case when concept = 'Other chronic heart failure drugs'                          then value_text  end) as other_medications,
    max(case when concept = 'Palliative care referral'                                   then value_coded end) as palliative_referral,
    max(case when concept = 'Follow up agreement'                                        then value_coded end) as request_chw_f_u,
    max(case when concept = 'Salt or fluid restricted'                                   then value_coded end) as salt_or_fluid_restricted,
    max(case when concept = 'Blood oxygen saturation'                                    then value_numeric end) as spo2,
    max(case when concept = 'Smoking history'                                            then value_coded end) as tobacco,
    max(case when concept = 'Took medications today'                                     then value_coded end) as took_medications_today,
    max(case when concept = 'Patients fluid management'                                  then value_coded end) as volume_status,
    max(case when concept = 'Weight (kg)'                                                then value_numeric end) as weight,
    max(case when concept = 'Weight change'                                              then value_text  end) as weight_change
from temp_chf_followup_obs
group by encounter_id;
alter table temp_single_values add index temp_single_values_encounter_idx (encounter_id);

insert into mw_chf_followup (patient_id, visit_date, location, benzathine_dose, ace_i_enal_dose, diuretic_furp_dose, ccb_nif_dose, diuretic_spiro_dose, ccb_aml_dose, ccb_aml_dosing_unit, ccb_aml_duration, ccb_aml_duration_units, ccb_aml_frequency, ccb_aml_route, asprin_asa_dose, asprin_asa_dosing_unit, asprin_asa_duration, asprin_asa_duration_units, asprin_asa_frequency, asprin_asa_route, bb_aten_dose, bb_aten_dosing_unit, bb_aten_duration, bb_aten_duration_units, bb_aten_frequency, bb_aten_route, benzathine_dosing_unit, benzathine_duration, benzathine_duration_units, benzathine_frequency, benzathine_route, bb_bis_dose, bb_bis_dosing_unit, bb_bis_duration, bb_bis_duration_units, bb_bis_frequency, bb_bis_route, ace_i_capt_dose, ace_i_capt_dosing_unit, ace_i_capt_duration, ace_i_capt_duration_units, ace_i_capt_frequency, ace_i_capt_route, ace_i_enal_dosing_unit, ace_i_enal_duration, ace_i_enal_duration_units, ace_i_enal_frequency, ace_i_enal_route, diuretic_furp_dosing_unit, diuretic_furp_duration, diuretic_furp_duration_units, diuretic_furp_frequency, diuretic_furp_route, diuretic_hctz_dose, diuretic_hctz_dosing_unit, diuretic_hctz_duration, diuretic_hctz_duration_units, diuretic_hctz_frequency, diuretic_hctz_route, ace_i_lisin_dose, ace_i_lisin_dosing_unit, ace_i_lisin_duration, ace_i_lisin_duration_units, ace_i_lisin_frequency, ace_i_lisin_route, ccb_nif_dosing_unit, ccb_nif_duration, ccb_nif_frequency, ccb_nif_route, ccb_nif_duration_units, bb_prop_dose, bb_prop_dosing_unit, bb_prop_duration, bb_prop_duration_units, bb_prop_frequency, bb_prop_route, diuretic_spiro_dosing_unit, diuretic_spiro_duration, diuretic_spiro_duration_units, diuretic_spiro_frequency, diuretic_spiro_route, ace_i_capt, ace_i_enal, ace_i_lisin, alcohol, aspirin, bb_aten, bb_bis, bb_prop, benzathine, bibasilar_crackles, bp_diastolic, bp_systolic, ccb_aml, ccb_nif, concern_for_depression_or_anxiety, diet_salt_or_fluid, diuretic_furo, diuretic_hctz, diuretic_spiro, dry_cough, dyspnea_on_exertion, fatigue, heart_rate, height, hospitalized_since_last_visit_for_ncd, jvp_elevated, mental_health_referral, next_appointment_date, nyha_stage, oedema, orthopnea, other_medications, palliative_referral, request_chw_f_u, salt_or_fluid_restricted, spo2, tobacco, took_medications_today, volume_status, weight, weight_change)
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    mv.benzathine_dose,
    mv.ace_i_enal_dose,
    mv.diuretic_furp_dose,
    mv.ccb_nif_dose,
    mv.diuretic_spiro_dose,
    mv.ccb_aml_dose,
    mv.ccb_aml_dosing_unit,
    mv.ccb_aml_duration,
    mv.ccb_aml_duration_units,
    mv.ccb_aml_frequency,
    mv.ccb_aml_route,
    mv.asprin_asa_dose,
    mv.asprin_asa_dosing_unit,
    mv.asprin_asa_duration,
    mv.asprin_asa_duration_units,
    mv.asprin_asa_frequency,
    mv.asprin_asa_route,
    mv.bb_aten_dose,
    mv.bb_aten_dosing_unit,
    mv.bb_aten_duration,
    mv.bb_aten_duration_units,
    mv.bb_aten_frequency,
    mv.bb_aten_route,
    mv.benzathine_dosing_unit,
    mv.benzathine_duration,
    mv.benzathine_duration_units,
    mv.benzathine_frequency,
    mv.benzathine_route,
    mv.bb_bis_dose,
    mv.bb_bis_dosing_unit,
    mv.bb_bis_duration,
    mv.bb_bis_duration_units,
    mv.bb_bis_frequency,
    mv.bb_bis_route,
    mv.ace_i_capt_dose,
    mv.ace_i_capt_dosing_unit,
    mv.ace_i_capt_duration,
    mv.ace_i_capt_duration_units,
    mv.ace_i_capt_frequency,
    mv.ace_i_capt_route,
    mv.ace_i_enal_dosing_unit,
    mv.ace_i_enal_duration,
    mv.ace_i_enal_duration_units,
    mv.ace_i_enal_frequency,
    mv.ace_i_enal_route,
    mv.diuretic_furp_dosing_unit,
    mv.diuretic_furp_duration,
    mv.diuretic_furp_duration_units,
    mv.diuretic_furp_frequency,
    mv.diuretic_furp_route,
    mv.diuretic_hctz_dose,
    mv.diuretic_hctz_dosing_unit,
    mv.diuretic_hctz_duration,
    mv.diuretic_hctz_duration_units,
    mv.diuretic_hctz_frequency,
    mv.diuretic_hctz_route,
    mv.ace_i_lisin_dose,
    mv.ace_i_lisin_dosing_unit,
    mv.ace_i_lisin_duration,
    mv.ace_i_lisin_duration_units,
    mv.ace_i_lisin_frequency,
    mv.ace_i_lisin_route,
    mv.ccb_nif_dosing_unit,
    mv.ccb_nif_duration,
    mv.ccb_nif_frequency,
    mv.ccb_nif_route,
    mv.ccb_nif_duration_units,
    mv.bb_prop_dose,
    mv.bb_prop_dosing_unit,
    mv.bb_prop_duration,
    mv.bb_prop_duration_units,
    mv.bb_prop_frequency,
    mv.bb_prop_route,
    mv.diuretic_spiro_dosing_unit,
    mv.diuretic_spiro_duration,
    mv.diuretic_spiro_duration_units,
    mv.diuretic_spiro_frequency,
    mv.diuretic_spiro_route,
    sv.ace_i_capt,
    sv.ace_i_enal,
    sv.ace_i_lisin,
    sv.alcohol,
    sv.aspirin,
    sv.bb_aten,
    sv.bb_bis,
    sv.bb_prop,
    sv.benzathine,
    sv.bibasilar_crackles,
    sv.bp_diastolic,
    sv.bp_systolic,
    sv.ccb_aml,
    sv.ccb_nif,
    sv.concern_for_depression_or_anxiety,
    sv.diet_salt_or_fluid,
    sv.diuretic_furo,
    sv.diuretic_hctz,
    sv.diuretic_spiro,
    sv.dry_cough,
    sv.dyspnea_on_exertion,
    sv.fatigue,
    sv.heart_rate,
    sv.height,
    sv.hospitalized_since_last_visit_for_ncd,
    sv.jvp_elevated,
    sv.mental_health_referral,
    sv.next_appointment_date,
    sv.nyha_stage,
    sv.oedema,
    sv.orthopnea,
    sv.other_medications,
    sv.palliative_referral,
    sv.request_chw_f_u,
    sv.salt_or_fluid_restricted,
    sv.spo2,
    sv.tobacco,
    sv.took_medications_today,
    sv.volume_status,
    sv.weight,
    sv.weight_change
from omrs_encounter e
left join temp_med_values mv on mv.encounter_id = e.encounter_id
left join temp_single_values sv on sv.encounter_id = e.encounter_id
where e.encounter_type in ('CHF_FOLLOWUP')
group by e.patient_id, e.encounter_date, e.location;

drop temporary table if exists temp_chf_followup_obs;
drop temporary table if exists temp_drug_name_obs;
drop temporary table if exists temp_drug_detail_obs;
drop temporary table if exists temp_medications;
drop temporary table if exists temp_med_values;
drop temporary table if exists temp_single_values;
