-- Derivation script for mw_chf_initial
-- Generated from Pentaho transform: import-into-mw-chf-initial.ktr

drop table if exists mw_chf_initial;
create table mw_chf_initial (
  chf_initial_visit_id 		int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  diagnosis_dilated 			varchar(255) default null,
  diagnosis_date_dilated 		date default null,
  diagnosis_restricitive 		varchar(255) default null,
  diagnosis_date_restricitive 	date default null,
  diagnosis_valvular 			varchar(255) default null,
  diagnosis_date_valvular 		date default null,
  diagnosis_right_ventricular_failure 	varchar(255) default null,
  diagnosis_date_right_ventricular_failure date default null,
  diagnosis_unknown 			varchar(255) default null,
  diagnosis_date_unknown 		date default null,
  diagnosis_rheumatic 			varchar(255) default null,
  diagnosis_date_rheumatic 		date default null,
  diagnosis_congenital 		varchar(255) default null,
  diagnosis_date_congenital 		date default null,
  diagnosis_cad 			varchar(255) default null,
  diagnosis_date_cad 			date default null,
  diagnosis_stroke 			varchar(255) default null,
  diagnosis_date_stroke 		date default null,
  diagnosis_afib 			varchar(255) default null,
  diagnosis_date_afib 			date default null,
  diagnosis_pe 			varchar(255) default null,
  diagnosis_date_pe 			date default null,
  diagnosis_dvt 			varchar(255) default null,
  diagnosis_date_dvt			date default null,
  diagnosis_other 			varchar(255) default null,
  diagnosis_date_other 		date default null,
  hiv_status 				varchar(255) default null,
  hiv_test_date 			date default null,
  art_start_date 			date default null,
  tb_status 				varchar(255) default null,
  tb_year 				int default null,
  comorbidities_hypertension 		varchar(255) default null,
  comorbidities_diabetes 		varchar(255) default null,
  comorbidities_chronic_kidney_disease varchar(255) default null,
  comorbidities_other 			varchar(255) default null,
  echo_test_result 			varchar(255) default null,
  echo_test_date 			date default null,
  ecg_test_result 			varchar(255) default null,
  ecg_test_date 			date default null,
  primary key (chf_initial_visit_id)
);

insert into mw_chf_initial
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Date antiretrovirals started' then o.value_date end) as art_start_date,
    max(case when o.concept = 'Current opportunistic infection or comorbidity, confirmed or presumed' and o.value_coded = 'Chronic kidney disease' then o.value_coded end) as comorbidities_chronic_kidney_disease,
    max(case when o.concept = 'Current opportunistic infection or comorbidity, confirmed or presumed' and o.value_coded = 'Diabetes' then o.value_coded end) as comorbidities_diabetes,
    max(case when o.concept = 'Current opportunistic infection or comorbidity, confirmed or presumed' and o.value_coded = 'Hypertension' then o.value_coded end) as comorbidities_hypertension,
    max(case when o.concept = 'Other diagnosis' then o.value_text end) as comorbidities_other,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Irregular rhythm' then o.value_coded end) as diagnosis_afib,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Coronary artery disease' then o.value_coded end) as diagnosis_cad,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Congenital heart disease' then o.value_coded end) as diagnosis_congenital,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_rheumatic,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_afib,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_cad,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_congenital,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_dilated,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_dvt,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_other,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_pe,
    max(case when o.concept = 'Diagnosis date' then o.value_numeric end) as diagnosis_date_restricitive,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_stroke,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_unknown,
    max(case when o.concept = 'Diagnosis date' then o.value_numeric end) as diagnosis_date_valvular,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Dilated cardiomyopathy' then o.value_coded end) as diagnosis_dilated,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Deep vein thrombosis' then o.value_coded end) as diagnosis_dvt,
    max(case when o.concept = 'Chronic care diagnosis' then o.value_coded end) as diagnosis_other,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Pulmonary embolism' then o.value_coded end) as diagnosis_pe,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Restrictive cardiomyopathy' then o.value_coded end) as diagnosis_restricitive,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Rheumatic heart disease' then o.value_coded end) as diagnosis_rheumatic,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Acute cerebrovascular attack' then o.value_coded end) as diagnosis_stroke,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Unknown' then o.value_coded end) as diagnosis_unknown,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Valvular heart disease' then o.value_coded end) as diagnosis_valvular,
    max(case when o.concept = 'Date of general test' then o.value_date end) as ecg_test_date,
    max(case when o.concept = 'Electrocardiogram diagnosis' then o.value_coded end) as ecg_test_result,
    max(case when o.concept = 'Date of general test' then o.value_date end) as echo_test_date,
    max(case when o.concept = 'ECHO imaging result' then o.value_text end) as echo_test_result,
    max(case when o.concept = 'HIV status' then o.value_coded end) as hiv_status,
    max(case when o.concept = 'HIV test date' then o.value_date end) as hiv_test_date,
    max(case when o.concept = 'TB status' then o.value_coded end) as tb_status,
    max(case when o.concept = 'Year of Tuberculosis diagnosis' then o.value_numeric end) as tb_year,
    max(case when o.concept = 'Diagnosis date' then o.value_numeric end) as diagnosis_date_right_ventricular_failure,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Right ventricular failure' then o.value_coded end) as diagnosis_right_ventricular_failure
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('CHF_INITIAL')
group by e.patient_id, e.encounter_date, e.location;