-- Derivation script for mw_chf_initial
-- Generated from Pentaho transform: import-into-mw-chf-initial.ktr

DROP TABLE IF EXISTS mw_chf_initial;
CREATE TABLE mw_chf_initial (
  chf_initial_visit_id 		int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  diagnosis_dilated 			varchar(255) DEFAULT NULL,
  diagnosis_date_dilated 		date DEFAULT NULL,
  diagnosis_restricitive 		varchar(255) DEFAULT NULL,
  diagnosis_date_restricitive 	date DEFAULT NULL,
  diagnosis_valvular 			varchar(255) DEFAULT NULL,
  diagnosis_date_valvular 		date DEFAULT NULL,
  diagnosis_right_ventricular_failure 	varchar(255) DEFAULT NULL,
  diagnosis_date_right_ventricular_failure date DEFAULT NULL,
  diagnosis_unknown 			varchar(255) DEFAULT NULL,
  diagnosis_date_unknown 		date DEFAULT NULL,
  diagnosis_rheumatic 			varchar(255) DEFAULT NULL,
  diagnosis_date_rheumatic 		date DEFAULT NULL,
  diagnosis_congenital 		varchar(255) DEFAULT NULL,
  diagnosis_date_congenital 		date DEFAULT NULL,
  diagnosis_cad 			varchar(255) DEFAULT NULL,
  diagnosis_date_cad 			date DEFAULT NULL,
  diagnosis_stroke 			varchar(255) DEFAULT NULL,
  diagnosis_date_stroke 		date DEFAULT NULL,
  diagnosis_afib 			varchar(255) DEFAULT NULL,
  diagnosis_date_afib 			date DEFAULT NULL,
  diagnosis_pe 			varchar(255) DEFAULT NULL,
  diagnosis_date_pe 			date DEFAULT NULL,
  diagnosis_dvt 			varchar(255) DEFAULT NULL,
  diagnosis_date_dvt			date DEFAULT NULL,
  diagnosis_other 			varchar(255) DEFAULT NULL,
  diagnosis_date_other 		date DEFAULT NULL,
  hiv_status 				varchar(255) DEFAULT NULL,
  hiv_test_date 			date DEFAULT NULL,
  art_start_date 			date DEFAULT NULL,
  tb_status 				varchar(255) DEFAULT NULL,
  tb_year 				int DEFAULT NULL,
  comorbidities_hypertension 		varchar(255) DEFAULT NULL,
  comorbidities_diabetes 		varchar(255) DEFAULT NULL,
  comorbidities_chronic_kidney_disease varchar(255) DEFAULT NULL,
  comorbidities_other 			varchar(255) DEFAULT NULL,
  echo_test_result 			varchar(255) DEFAULT NULL,
  echo_test_date 			date DEFAULT NULL,
  ecg_test_result 			varchar(255) DEFAULT NULL,
  ecg_test_date 			date DEFAULT NULL,
  PRIMARY KEY (chf_initial_visit_id)
);

INSERT INTO mw_chf_initial
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Date antiretrovirals started' THEN o.value_date END) as art_start_date,
    MAX(CASE WHEN o.concept = 'Current opportunistic infection or comorbidity, confirmed or presumed' AND o.value_coded = 'Chronic kidney disease' THEN o.value_coded END) as comorbidities_chronic_kidney_disease,
    MAX(CASE WHEN o.concept = 'Current opportunistic infection or comorbidity, confirmed or presumed' AND o.value_coded = 'Diabetes' THEN o.value_coded END) as comorbidities_diabetes,
    MAX(CASE WHEN o.concept = 'Current opportunistic infection or comorbidity, confirmed or presumed' AND o.value_coded = 'Hypertension' THEN o.value_coded END) as comorbidities_hypertension,
    MAX(CASE WHEN o.concept = 'Other diagnosis' THEN o.value_text END) as comorbidities_other,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Irregular rhythm' THEN o.value_coded END) as diagnosis_afib,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Coronary artery disease' THEN o.value_coded END) as diagnosis_cad,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Congenital heart disease' THEN o.value_coded END) as diagnosis_congenital,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_rheumatic,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_afib,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_cad,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_congenital,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_dilated,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_dvt,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_other,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_pe,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_numeric END) as diagnosis_date_restricitive,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_stroke,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_unknown,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_numeric END) as diagnosis_date_valvular,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Dilated cardiomyopathy' THEN o.value_coded END) as diagnosis_dilated,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Deep vein thrombosis' THEN o.value_coded END) as diagnosis_dvt,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' THEN o.value_coded END) as diagnosis_other,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Pulmonary embolism' THEN o.value_coded END) as diagnosis_pe,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Restrictive cardiomyopathy' THEN o.value_coded END) as diagnosis_restricitive,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Rheumatic heart disease' THEN o.value_coded END) as diagnosis_rheumatic,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Acute cerebrovascular attack' THEN o.value_coded END) as diagnosis_stroke,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Unknown' THEN o.value_coded END) as diagnosis_unknown,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Valvular heart disease' THEN o.value_coded END) as diagnosis_valvular,
    MAX(CASE WHEN o.concept = 'Date of general test' THEN o.value_date END) as ecg_test_date,
    MAX(CASE WHEN o.concept = 'Electrocardiogram diagnosis' THEN o.value_coded END) as ecg_test_result,
    MAX(CASE WHEN o.concept = 'Date of general test' THEN o.value_date END) as echo_test_date,
    MAX(CASE WHEN o.concept = 'ECHO imaging result' THEN o.value_text END) as echo_test_result,
    MAX(CASE WHEN o.concept = 'HIV status' THEN o.value_coded END) as hiv_status,
    MAX(CASE WHEN o.concept = 'HIV test date' THEN o.value_date END) as hiv_test_date,
    MAX(CASE WHEN o.concept = 'TB status' THEN o.value_coded END) as tb_status,
    MAX(CASE WHEN o.concept = 'Year of Tuberculosis diagnosis' THEN o.value_numeric END) as tb_year,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_numeric END) as diagnosis_date_right_ventricular_failure,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Right ventricular failure' THEN o.value_coded END) as diagnosis_right_ventricular_failure
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('CHF_INITIAL')
GROUP BY e.patient_id, e.encounter_date, e.location;