-- Derivation script for mw_ckd_followup
-- Generated from Pentaho transform: import-into-mw-ckd-followup.ktr

DROP TABLE IF EXISTS mw_ckd_followup;
CREATE TABLE mw_ckd_followup (
  ckd_followup_visit_id 	int NOT NULL AUTO_INCREMENT,
  patient_id 			int NOT NULL,
  visit_date 			date DEFAULT NULL,
  location 			varchar(255) DEFAULT NULL,
  height 			int DEFAULT NULL,
  weight 			int DEFAULT NULL,
  bp_systolic 			int DEFAULT NULL,
  bp_diastolic 		int DEFAULT NULL,
  heart_rate 			int DEFAULT NULL,
  creatinine 			int DEFAULT NULL,
  gfr 				int DEFAULT NULL,
  urine_protein 		varchar(255) DEFAULT NULL,
  confusion 			varchar(255) DEFAULT NULL,
  fatigue 			varchar(255) DEFAULT NULL,
  nausea 			varchar(255) DEFAULT NULL,
  anorexia 			varchar(255) DEFAULT NULL,
  pruritus 			varchar(255) DEFAULT NULL,
  conjunctiva			varchar(255) DEFAULT NULL,
  ascites 			varchar(255) DEFAULT NULL,
  oedema 			varchar(255) DEFAULT NULL,
  other_symptoms 		varchar(255) DEFAULT NULL,
  ckd_stage 			varchar(255) DEFAULT NULL,
  nsaid_use 			varchar(255) DEFAULT NULL,
  alcohol 			varchar(255) DEFAULT NULL,
  tobacco 			varchar(255) DEFAULT NULL,
  diuretic_hctz 		varchar(255) DEFAULT NULL,
  diuretic_hctz_dose		INT,
  diuretic_hctz_dosing_unit VARCHAR(50),
  diuretic_hctz_route		VARCHAR(50),
  diuretic_hctz_frequency		VARCHAR(50),
  diuretic_hctz_duration   INT,
  diuretic_hctz_duration_units  VARCHAR(50),
  diuretic_furo 		varchar(255) DEFAULT NULL,
  diuretic_furp_dose		INT,
  diuretic_furp_dosing_unit VARCHAR(50),
  diuretic_furp_route		VARCHAR(50),
  diuretic_furp_frequency		VARCHAR(50),
  diuretic_furp_duration   INT,
  diuretic_furp_duration_units  VARCHAR(50),
  diuretic_spiro 		varchar(255) DEFAULT NULL,
  diuretic_spiro_dose		INT,
  diuretic_spiro_dosing_unit VARCHAR(50),
  diuretic_spiro_route		VARCHAR(50),
  diuretic_spiro_frequency		VARCHAR(50),
  diuretic_spiro_duration   INT,
  diuretic_spiro_duration_units  VARCHAR(50),
  ace_i_enal				 			VARCHAR(50),
  ace_i_enal_dose		INT,
  ace_i_enal_dosing_unit VARCHAR(50),
  ace_i_enal_route		VARCHAR(50),
  ace_i_enal_frequency		VARCHAR(50),
  ace_i_enal_duration   INT,
  ace_i_enal_duration_units  VARCHAR(50),
  ace_i_capt				 			VARCHAR(50),
  ace_i_capt_dose		INT,
  ace_i_capt_dosing_unit VARCHAR(50),
  ace_i_capt_route		VARCHAR(50),
  ace_i_capt_frequency		VARCHAR(50),
  ace_i_capt_duration   INT,
  ace_i_capt_duration_units  VARCHAR(50),
  ace_i_lisin			 				VARCHAR(50),
  ace_i_lisin_dose		INT,
  ace_i_lisin_dosing_unit VARCHAR(50),
  ace_i_lisin_route		VARCHAR(50),
  ace_i_lisin_frequency		VARCHAR(50),
  ace_i_lisin_duration   INT,
  ace_i_lisin_duration_units  VARCHAR(50),
  bb_aten				 			VARCHAR(50),
  bb_aten_dose		INT,
  bb_aten_dosing_unit VARCHAR(50),
  bb_aten_route		VARCHAR(50),
  bb_aten_frequency		VARCHAR(50),
  bb_aten_duration   INT,
  bb_aten_duration_units  VARCHAR(50),
  bb_bis				 			VARCHAR(50),
  bb_bis_dose		INT,
  bb_bis_dosing_unit VARCHAR(50),
  bb_bis_route		VARCHAR(50),
  bb_bis_frequency		VARCHAR(50),
  bb_bis_duration   INT,
  bb_bis_duration_units  VARCHAR(50),
  bb_prop				 			VARCHAR(50),
  bb_prop_dose		INT,
  bb_prop_dosing_unit VARCHAR(50),
  bb_prop_route		VARCHAR(50),
  bb_prop_frequency		VARCHAR(50),
  bb_prop_duration   INT,
  bb_prop_duration_units  VARCHAR(50),
  ccb_aml				 			VARCHAR(50),
  ccb_aml_dose		INT,
  ccb_aml_dosing_unit VARCHAR(50),
  ccb_aml_route		VARCHAR(50),
  ccb_aml_frequency		VARCHAR(50),
  ccb_aml_duration   INT,
  ccb_aml_duration_units  VARCHAR(50),
  ccb_nif				 			VARCHAR(50),
  ccb_nif_dose		INT,
  ccb_nif_dosing_unit VARCHAR(50),
  ccb_nif_route		VARCHAR(50),
  ccb_nif_frequency		VARCHAR(50),
  ccb_nif_duration   INT,
  ccb_nif_duration_units  VARCHAR(50),
  other_medications 		varchar(255) DEFAULT NULL,
  took_medications_today 	varchar(255) DEFAULT NULL,
  diet_recommendations 	varchar(255) DEFAULT NULL,
  next_appointment_date	date DEFAULT NULL,
  PRIMARY KEY (ckd_followup_visit_id)
);

INSERT INTO mw_ckd_followup
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ace_i_enal_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as diuretic_furp_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ccb_nif_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as diuretic_spiro_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ccb_aml_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ccb_aml_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ccb_aml_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ccb_aml_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ccb_aml_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ccb_aml_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as bb_aten_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as bb_aten_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as bb_aten_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as bb_aten_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as bb_aten_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as bb_aten_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as bb_bis_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as bb_bis_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as bb_bis_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as bb_bis_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as bb_bis_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as bb_bis_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ace_i_capt_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ace_i_capt_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ace_i_capt_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ace_i_capt_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ace_i_capt_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ace_i_capt_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ace_i_enal_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ace_i_enal_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ace_i_enal_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ace_i_enal_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ace_i_enal_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as diuretic_furp_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as diuretic_furp_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as diuretic_furp_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as diuretic_furp_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as diuretic_furp_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as diuretic_hctz_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as diuretic_hctz_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as diuretic_hctz_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as diuretic_hctz_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as diuretic_hctz_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as diuretic_hctz_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ace_i_lisin_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ace_i_lisin_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ace_i_lisin_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ace_i_lisin_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ace_i_lisin_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ace_i_lisin_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ccb_nif_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ccb_nif_duration,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ccb_nif_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ccb_nif_route,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ccb_nif_duration_units,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as bb_prop_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as bb_prop_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as bb_prop_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as bb_prop_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as bb_prop_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as bb_prop_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as diuretic_spiro_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as diuretic_spiro_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as diuretic_spiro_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as diuretic_spiro_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as diuretic_spiro_route,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Captopril' THEN o.value_coded END) as ace_i_capt,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Enalapril' THEN o.value_coded END) as ace_i_enal,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Lisinopril' THEN o.value_coded END) as ace_i_lisin,
    MAX(CASE WHEN o.concept = 'History of alcohol use' THEN o.value_coded END) as alcohol,
    MAX(CASE WHEN o.concept = 'Patient has anorexia' THEN o.value_coded END) as anorexia,
    MAX(CASE WHEN o.concept = 'Patient has ascites' THEN o.value_coded END) as ascites,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Atenolol' THEN o.value_coded END) as bb_aten,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Bisoprolol' THEN o.value_coded END) as bb_bis,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Propranolol' THEN o.value_coded END) as bb_prop,
    MAX(CASE WHEN o.concept = 'Diastolic blood pressure' THEN o.value_numeric END) as bp_diastolic,
    MAX(CASE WHEN o.concept = 'Systolic blood pressure' THEN o.value_numeric END) as bp_systolic,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Amlodipine' THEN o.value_coded END) as ccb_aml,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Nifedipine' THEN o.value_coded END) as ccb_nif,
    MAX(CASE WHEN o.concept = 'CKD stage' THEN o.value_coded END) as ckd_stage,
    MAX(CASE WHEN o.concept = 'Patient confused (newly disoriented in place, person or time)' THEN o.value_coded END) as confusion,
    MAX(CASE WHEN o.concept = 'Conjunctiva' THEN o.value_coded END) as conjunctiva,
    MAX(CASE WHEN o.concept = 'Creatinine' THEN o.value_numeric END) as creatinine,
    MAX(CASE WHEN o.concept = 'Diet recommendations' THEN o.value_coded END) as diet_recommendations,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Furosemide' THEN o.value_coded END) as diuretic_furo,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Hydrochlorothiazide' THEN o.value_coded END) as diuretic_hctz,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Spironolactone' THEN o.value_coded END) as diuretic_spiro,
    MAX(CASE WHEN o.concept = 'Patient has fatigue' THEN o.value_coded END) as fatigue,
    MAX(CASE WHEN o.concept = 'Glomerular filtration rate' THEN o.value_numeric END) as gfr,
    MAX(CASE WHEN o.concept = 'Pulse' THEN o.value_numeric END) as heart_rate,
    MAX(CASE WHEN o.concept = 'Height (cm)' THEN o.value_numeric END) as height,
    MAX(CASE WHEN o.concept = 'Patient has nausea' THEN o.value_coded END) as nausea,
    MAX(CASE WHEN o.concept = 'Appointment date' THEN o.value_date END) as next_appointment_date,
    MAX(CASE WHEN o.concept = 'Nonsteroidal anti-inflammatory drug use' THEN o.value_coded END) as nsaid_use,
    MAX(CASE WHEN o.concept = 'Oedema' THEN o.value_coded END) as oedema,
    MAX(CASE WHEN o.concept = 'Other chronic heart failure drugs' THEN o.value_text END) as other_medications,
    MAX(CASE WHEN o.concept = 'Review of symptoms other' THEN o.value_text END) as other_symptoms,
    MAX(CASE WHEN o.concept = 'Patient has pruritus' THEN o.value_coded END) as pruritus,
    MAX(CASE WHEN o.concept = 'Smoking history' THEN o.value_coded END) as tobacco,
    MAX(CASE WHEN o.concept = 'Took medications today' THEN o.value_coded END) as took_medications_today,
    MAX(CASE WHEN o.concept = 'Urine protein' THEN o.value_coded END) as urine_protein,
    MAX(CASE WHEN o.concept = 'Weight (kg)' THEN o.value_numeric END) as weight,
    MAX(CASE WHEN o.concept = 'Weight change' THEN o.value_text END) as weight_change
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('CKD_FOLLOWUP')
GROUP BY e.patient_id, e.encounter_date, e.location;