-- Derivation script for mw_chf_followup
-- Generated from Pentaho transform: import-into-mw-chf-followup.ktr

DROP TABLE IF EXISTS mw_chf_followup;
CREATE TABLE mw_chf_followup (
  chf_followup_visit_id 			int NOT NULL AUTO_INCREMENT,
  patient_id 					int NOT NULL,
  visit_date 					date DEFAULT NULL,
  location 					varchar(50) DEFAULT NULL,
  height 					int DEFAULT NULL,	
  weight 					int DEFAULT NULL,
  weight_change 				varchar(50) DEFAULT NULL,
  bp_systolic 					int DEFAULT NULL,
  bp_diastolic 				int DEFAULT NULL,
  heart_rate 					int DEFAULT NULL,
  spo2 					int DEFAULT NULL,
  orthopnea 					varchar(50) DEFAULT NULL,
  dyspnea_on_exertion 				varchar(50) DEFAULT NULL,
  dry_cough 					varchar(50) DEFAULT NULL,
  fatigue			 		varchar(50) DEFAULT NULL,
  hospitalized_since_last_visit_for_ncd 	varchar(50) DEFAULT NULL,
  oedema 					varchar(50) DEFAULT NULL,
  bibasilar_crackles 				varchar(50) DEFAULT NULL,
  jvp_elevated 				varchar(50) DEFAULT NULL,
  volume_status 				varchar(50) DEFAULT NULL,
  nyha_stage 					varchar(50) DEFAULT NULL,
  alcohol 					varchar(50) DEFAULT NULL,
  tobacco 					varchar(50) DEFAULT NULL,
  salt_or_fluid_restricted 			varchar(50) DEFAULT NULL,
  concern_for_depression_or_anxiety 		varchar(50) DEFAULT NULL,
  aspirin 					varchar(50) DEFAULT NULL,
  asprin_asa_dose		INT,
  asprin_asa_dosing_unit varchar(50),
  asprin_asa_route		varchar(50),
  asprin_asa_frequency		varchar(50),
  asprin_asa_duration   INT,
  asprin_asa_duration_units  varchar(50),
  diuretic_hctz 				varchar(50) DEFAULT NULL,
  diuretic_hctz_dose		INT,
  diuretic_hctz_dosing_unit varchar(50),
  diuretic_hctz_route		varchar(50),
  diuretic_hctz_frequency		varchar(50),
  diuretic_hctz_duration   INT,
  diuretic_hctz_duration_units  varchar(50),
  diuretic_furo 				varchar(50) DEFAULT NULL,
  diuretic_furp_dose		INT,
  diuretic_furp_dosing_unit varchar(50),
  diuretic_furp_route		varchar(50),
  diuretic_furp_frequency		varchar(50),
  diuretic_furp_duration   INT,
  diuretic_furp_duration_units  varchar(50),
  diuretic_spiro			 			varchar(50),
  diuretic_spiro_dose		INT,
  diuretic_spiro_dosing_unit varchar(50),
  diuretic_spiro_route		varchar(50),
  diuretic_spiro_frequency		varchar(50),
  diuretic_spiro_duration   INT,
  diuretic_spiro_duration_units  varchar(50),
  ace_i_enal				 			varchar(50),
  ace_i_enal_dose		INT,
  ace_i_enal_dosing_unit varchar(50),
  ace_i_enal_route		varchar(50),
  ace_i_enal_frequency		varchar(50),
  ace_i_enal_duration   INT,
  ace_i_enal_duration_units  varchar(50),
  ace_i_capt				 			varchar(50),
  ace_i_capt_dose		INT,
  ace_i_capt_dosing_unit varchar(50),
  ace_i_capt_route		varchar(50),
  ace_i_capt_frequency		varchar(50),
  ace_i_capt_duration   INT,
  ace_i_capt_duration_units  varchar(50),
  ace_i_lisin			 				varchar(50),
  ace_i_lisin_dose		INT,
  ace_i_lisin_dosing_unit varchar(50),
  ace_i_lisin_route		varchar(50),
  ace_i_lisin_frequency		varchar(50),
  ace_i_lisin_duration   INT,
  ace_i_lisin_duration_units  varchar(50),
  bb_aten				 			varchar(50),
  bb_aten_dose		INT,
  bb_aten_dosing_unit varchar(50),
  bb_aten_route		varchar(50),
  bb_aten_frequency		varchar(50),
  bb_aten_duration   INT,
  bb_aten_duration_units  varchar(50),
  bb_bis				 			varchar(50),
  bb_bis_dose		INT,
  bb_bis_dosing_unit varchar(50),
  bb_bis_route		varchar(50),
  bb_bis_frequency		varchar(50),
  bb_bis_duration   INT,
  bb_bis_duration_units  varchar(50),
  bb_prop				 			varchar(50),
  bb_prop_dose		INT,
  bb_prop_dosing_unit varchar(50),
  bb_prop_route		varchar(50),
  bb_prop_frequency		varchar(50),
  bb_prop_duration   INT,
  bb_prop_duration_units  varchar(50),
  ccb_aml				 			varchar(50),
  ccb_aml_dose		INT,
  ccb_aml_dosing_unit varchar(50),
  ccb_aml_route		varchar(50),
  ccb_aml_frequency		varchar(50),
  ccb_aml_duration   INT,
  ccb_aml_duration_units  varchar(50),
  ccb_nif				 			varchar(50),
  ccb_nif_dose		INT,
  ccb_nif_dosing_unit varchar(50),
  ccb_nif_route		varchar(50),
  ccb_nif_frequency		varchar(50),
  ccb_nif_duration   INT,
  ccb_nif_duration_units  varchar(50),
  benzathine 					varchar(50) DEFAULT NULL,
  benzathine_dose		INT,
  benzathine_dosing_unit varchar(50),
  benzathine_route		varchar(50),
  benzathine_frequency		varchar(50),
  benzathine_duration   INT,
  benzathine_duration_units  varchar(50),
  other_medications 				varchar(50) DEFAULT NULL,
  took_medications_today 			varchar(50) DEFAULT NULL,
  diet_salt_or_fluid 				varchar(50) DEFAULT NULL,
  mental_health_referral 			varchar(50) DEFAULT NULL,
  palliative_referral 				varchar(50) DEFAULT NULL,
  request_chw_f_u 				varchar(50) DEFAULT NULL,
  next_appointment_date 			date DEFAULT NULL,
  PRIMARY KEY (chf_followup_visit_id)
) ;

INSERT INTO mw_chf_followup
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as benzathine_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ace_i_enal_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as diuretic_furp_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ccb_nif_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as diuretic_spiro_dose,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ccb_aml_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ccb_aml_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ccb_aml_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ccb_aml_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ccb_aml_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ccb_aml_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as asprin_asa_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as asprin_asa_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as asprin_asa_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as asprin_asa_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as asprin_asa_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as asprin_asa_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as bb_aten_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as bb_aten_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as bb_aten_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as bb_aten_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as bb_aten_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as bb_aten_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as benzathine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as benzathine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as benzathine_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as benzathine_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as benzathine_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as bb_bis_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as bb_bis_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as bb_bis_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as bb_bis_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as bb_bis_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as bb_bis_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ace_i_capt_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ace_i_capt_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ace_i_capt_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ace_i_capt_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ace_i_capt_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ace_i_capt_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ace_i_enal_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ace_i_enal_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ace_i_enal_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ace_i_enal_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ace_i_enal_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as diuretic_furp_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as diuretic_furp_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as diuretic_furp_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as diuretic_furp_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as diuretic_furp_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as diuretic_hctz_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as diuretic_hctz_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as diuretic_hctz_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as diuretic_hctz_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as diuretic_hctz_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as diuretic_hctz_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as ace_i_lisin_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ace_i_lisin_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ace_i_lisin_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ace_i_lisin_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ace_i_lisin_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ace_i_lisin_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as ccb_nif_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as ccb_nif_duration,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as ccb_nif_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as ccb_nif_route,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as ccb_nif_duration_units,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as bb_prop_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as bb_prop_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as bb_prop_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as bb_prop_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as bb_prop_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as bb_prop_route,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as diuretic_spiro_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as diuretic_spiro_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as diuretic_spiro_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as diuretic_spiro_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as diuretic_spiro_route,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Captopril' THEN o.value_coded END) as ace_i_capt,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Enalapril' THEN o.value_coded END) as ace_i_enal,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Lisinopril' THEN o.value_coded END) as ace_i_lisin,
    MAX(CASE WHEN o.concept = 'History of alcohol use' THEN o.value_coded END) as alcohol,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Aspirin' THEN o.value_coded END) as aspirin,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Atenolol' THEN o.value_coded END) as bb_aten,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Bisoprolol' THEN o.value_coded END) as bb_bis,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Propranolol' THEN o.value_coded END) as bb_prop,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Benzathine penicillin' THEN o.value_coded END) as benzathine,
    MAX(CASE WHEN o.concept = 'Bibasilar crackles' THEN o.value_coded END) as bibasilar_crackles,
    MAX(CASE WHEN o.concept = 'Diastolic blood pressure' THEN o.value_numeric END) as bp_diastolic,
    MAX(CASE WHEN o.concept = 'Systolic blood pressure' THEN o.value_numeric END) as bp_systolic,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Amlodipine' THEN o.value_coded END) as ccb_aml,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Nifedipine' THEN o.value_coded END) as ccb_nif,
    MAX(CASE WHEN o.concept = 'Concern for depression or anxiety' THEN o.value_coded END) as concern_for_depression_or_anxiety,
    MAX(CASE WHEN o.concept = 'Low salt diet recommended' THEN o.value_coded END) as diet_salt_or_fluid,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Furosemide' THEN o.value_coded END) as diuretic_furo,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Hydrochlorothiazide' THEN o.value_coded END) as diuretic_hctz,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Spironolactone' THEN o.value_coded END) as diuretic_spiro,
    MAX(CASE WHEN o.concept = 'Level of dry cough' THEN o.value_coded END) as dry_cough,
    MAX(CASE WHEN o.concept = 'Dyspnea on extertion' THEN o.value_coded END) as dyspnea_on_exertion,
    MAX(CASE WHEN o.concept = 'Level of fatigue' THEN o.value_coded END) as fatigue,
    MAX(CASE WHEN o.concept = 'Pulse' THEN o.value_numeric END) as heart_rate,
    MAX(CASE WHEN o.concept = 'Height (cm)' THEN o.value_numeric END) as height,
    MAX(CASE WHEN o.concept = 'Hospitalized for non-communicable disease since last visit' THEN o.value_coded END) as hospitalized_since_last_visit_for_ncd,
    MAX(CASE WHEN o.concept = 'Jugular venous pressure elevated' THEN o.value_coded END) as jvp_elevated,
    MAX(CASE WHEN o.concept = 'Mental health referral' THEN o.value_coded END) as mental_health_referral,
    MAX(CASE WHEN o.concept = 'Appointment date' THEN o.value_date END) as next_appointment_date,
    MAX(CASE WHEN o.concept = 'Nyha class' THEN o.value_coded END) as nyha_stage,
    MAX(CASE WHEN o.concept = 'Oedema' THEN o.value_coded END) as oedema,
    MAX(CASE WHEN o.concept = 'Level of orthopnea' THEN o.value_coded END) as orthopnea,
    MAX(CASE WHEN o.concept = 'Other chronic heart failure drugs' THEN o.value_text END) as other_medications,
    MAX(CASE WHEN o.concept = 'Palliative care referral' THEN o.value_coded END) as palliative_referral,
    MAX(CASE WHEN o.concept = 'Follow up agreement' THEN o.value_coded END) as request_chw_f_u,
    MAX(CASE WHEN o.concept = 'Salt or fluid restricted' THEN o.value_coded END) as salt_or_fluid_restricted,
    MAX(CASE WHEN o.concept = 'Blood oxygen saturation' THEN o.value_numeric END) as spo2,
    MAX(CASE WHEN o.concept = 'Smoking history' THEN o.value_coded END) as tobacco,
    MAX(CASE WHEN o.concept = 'Took medications today' THEN o.value_coded END) as took_medications_today,
    MAX(CASE WHEN o.concept = 'Patients fluid management' THEN o.value_coded END) as volume_status,
    MAX(CASE WHEN o.concept = 'Weight (kg)' THEN o.value_numeric END) as weight,
    MAX(CASE WHEN o.concept = 'Weight change' THEN o.value_text END) as weight_change
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('CHF_FOLLOWUP')
GROUP BY e.patient_id, e.encounter_date, e.location;