-- Derivation script for mw_chf_followup
-- Generated from Pentaho transform: import-into-mw-chf-followup.ktr

drop table if exists mw_chf_followup;
create table mw_chf_followup (
  chf_followup_visit_id 			int not null auto_increment,
  patient_id 					int not null,
  visit_date 					date default null,
  location 					varchar(50) default null,
  height 					int default null,	
  weight 					int default null,
  weight_change 				varchar(50) default null,
  bp_systolic 					int default null,
  bp_diastolic 				int default null,
  heart_rate 					int default null,
  spo2 					int default null,
  orthopnea 					varchar(50) default null,
  dyspnea_on_exertion 				varchar(50) default null,
  dry_cough 					varchar(50) default null,
  fatigue			 		varchar(50) default null,
  hospitalized_since_last_visit_for_ncd 	varchar(50) default null,
  oedema 					varchar(50) default null,
  bibasilar_crackles 				varchar(50) default null,
  jvp_elevated 				varchar(50) default null,
  volume_status 				varchar(50) default null,
  nyha_stage 					varchar(50) default null,
  alcohol 					varchar(50) default null,
  tobacco 					varchar(50) default null,
  salt_or_fluid_restricted 			varchar(50) default null,
  concern_for_depression_or_anxiety 		varchar(50) default null,
  aspirin 					varchar(50) default null,
  asprin_asa_dose		int,
  asprin_asa_dosing_unit varchar(50),
  asprin_asa_route		varchar(50),
  asprin_asa_frequency		varchar(50),
  asprin_asa_duration   int,
  asprin_asa_duration_units  varchar(50),
  diuretic_hctz 				varchar(50) default null,
  diuretic_hctz_dose		int,
  diuretic_hctz_dosing_unit varchar(50),
  diuretic_hctz_route		varchar(50),
  diuretic_hctz_frequency		varchar(50),
  diuretic_hctz_duration   int,
  diuretic_hctz_duration_units  varchar(50),
  diuretic_furo 				varchar(50) default null,
  diuretic_furp_dose		int,
  diuretic_furp_dosing_unit varchar(50),
  diuretic_furp_route		varchar(50),
  diuretic_furp_frequency		varchar(50),
  diuretic_furp_duration   int,
  diuretic_furp_duration_units  varchar(50),
  diuretic_spiro			 			varchar(50),
  diuretic_spiro_dose		int,
  diuretic_spiro_dosing_unit varchar(50),
  diuretic_spiro_route		varchar(50),
  diuretic_spiro_frequency		varchar(50),
  diuretic_spiro_duration   int,
  diuretic_spiro_duration_units  varchar(50),
  ace_i_enal				 			varchar(50),
  ace_i_enal_dose		int,
  ace_i_enal_dosing_unit varchar(50),
  ace_i_enal_route		varchar(50),
  ace_i_enal_frequency		varchar(50),
  ace_i_enal_duration   int,
  ace_i_enal_duration_units  varchar(50),
  ace_i_capt				 			varchar(50),
  ace_i_capt_dose		int,
  ace_i_capt_dosing_unit varchar(50),
  ace_i_capt_route		varchar(50),
  ace_i_capt_frequency		varchar(50),
  ace_i_capt_duration   int,
  ace_i_capt_duration_units  varchar(50),
  ace_i_lisin			 				varchar(50),
  ace_i_lisin_dose		int,
  ace_i_lisin_dosing_unit varchar(50),
  ace_i_lisin_route		varchar(50),
  ace_i_lisin_frequency		varchar(50),
  ace_i_lisin_duration   int,
  ace_i_lisin_duration_units  varchar(50),
  bb_aten				 			varchar(50),
  bb_aten_dose		int,
  bb_aten_dosing_unit varchar(50),
  bb_aten_route		varchar(50),
  bb_aten_frequency		varchar(50),
  bb_aten_duration   int,
  bb_aten_duration_units  varchar(50),
  bb_bis				 			varchar(50),
  bb_bis_dose		int,
  bb_bis_dosing_unit varchar(50),
  bb_bis_route		varchar(50),
  bb_bis_frequency		varchar(50),
  bb_bis_duration   int,
  bb_bis_duration_units  varchar(50),
  bb_prop				 			varchar(50),
  bb_prop_dose		int,
  bb_prop_dosing_unit varchar(50),
  bb_prop_route		varchar(50),
  bb_prop_frequency		varchar(50),
  bb_prop_duration   int,
  bb_prop_duration_units  varchar(50),
  ccb_aml				 			varchar(50),
  ccb_aml_dose		int,
  ccb_aml_dosing_unit varchar(50),
  ccb_aml_route		varchar(50),
  ccb_aml_frequency		varchar(50),
  ccb_aml_duration   int,
  ccb_aml_duration_units  varchar(50),
  ccb_nif				 			varchar(50),
  ccb_nif_dose		int,
  ccb_nif_dosing_unit varchar(50),
  ccb_nif_route		varchar(50),
  ccb_nif_frequency		varchar(50),
  ccb_nif_duration   int,
  ccb_nif_duration_units  varchar(50),
  benzathine 					varchar(50) default null,
  benzathine_dose		int,
  benzathine_dosing_unit varchar(50),
  benzathine_route		varchar(50),
  benzathine_frequency		varchar(50),
  benzathine_duration   int,
  benzathine_duration_units  varchar(50),
  other_medications 				varchar(50) default null,
  took_medications_today 			varchar(50) default null,
  diet_salt_or_fluid 				varchar(50) default null,
  mental_health_referral 			varchar(50) default null,
  palliative_referral 				varchar(50) default null,
  request_chw_f_u 				varchar(50) default null,
  next_appointment_date 			date default null,
  primary key (chf_followup_visit_id)
) ;

insert into mw_chf_followup
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as benzathine_dose,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as ace_i_enal_dose,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as diuretic_furp_dose,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as ccb_nif_dose,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as diuretic_spiro_dose,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as ccb_aml_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as ccb_aml_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as ccb_aml_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as ccb_aml_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as ccb_aml_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as ccb_aml_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as asprin_asa_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as asprin_asa_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as asprin_asa_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as asprin_asa_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as asprin_asa_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as asprin_asa_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as bb_aten_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as bb_aten_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as bb_aten_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as bb_aten_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as bb_aten_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as bb_aten_route,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as benzathine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as benzathine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as benzathine_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as benzathine_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as benzathine_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as bb_bis_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as bb_bis_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as bb_bis_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as bb_bis_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as bb_bis_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as bb_bis_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as ace_i_capt_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as ace_i_capt_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as ace_i_capt_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as ace_i_capt_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as ace_i_capt_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as ace_i_capt_route,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as ace_i_enal_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as ace_i_enal_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as ace_i_enal_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as ace_i_enal_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as ace_i_enal_route,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as diuretic_furp_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as diuretic_furp_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as diuretic_furp_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as diuretic_furp_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as diuretic_furp_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as diuretic_hctz_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as diuretic_hctz_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as diuretic_hctz_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as diuretic_hctz_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as diuretic_hctz_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as diuretic_hctz_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as ace_i_lisin_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as ace_i_lisin_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as ace_i_lisin_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as ace_i_lisin_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as ace_i_lisin_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as ace_i_lisin_route,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as ccb_nif_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as ccb_nif_duration,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as ccb_nif_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as ccb_nif_route,
    max(case when o.concept = 'Time units' then o.value_coded end) as ccb_nif_duration_units,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as bb_prop_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as bb_prop_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as bb_prop_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as bb_prop_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as bb_prop_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as bb_prop_route,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as diuretic_spiro_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as diuretic_spiro_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as diuretic_spiro_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as diuretic_spiro_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as diuretic_spiro_route,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Captopril' then o.value_coded end) as ace_i_capt,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Enalapril' then o.value_coded end) as ace_i_enal,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Lisinopril' then o.value_coded end) as ace_i_lisin,
    max(case when o.concept = 'History of alcohol use' then o.value_coded end) as alcohol,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Aspirin' then o.value_coded end) as aspirin,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Atenolol' then o.value_coded end) as bb_aten,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Bisoprolol' then o.value_coded end) as bb_bis,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Propranolol' then o.value_coded end) as bb_prop,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Benzathine penicillin' then o.value_coded end) as benzathine,
    max(case when o.concept = 'Bibasilar crackles' then o.value_coded end) as bibasilar_crackles,
    max(case when o.concept = 'Diastolic blood pressure' then o.value_numeric end) as bp_diastolic,
    max(case when o.concept = 'Systolic blood pressure' then o.value_numeric end) as bp_systolic,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Amlodipine' then o.value_coded end) as ccb_aml,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Nifedipine' then o.value_coded end) as ccb_nif,
    max(case when o.concept = 'Concern for depression or anxiety' then o.value_coded end) as concern_for_depression_or_anxiety,
    max(case when o.concept = 'Low salt diet recommended' then o.value_coded end) as diet_salt_or_fluid,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Furosemide' then o.value_coded end) as diuretic_furo,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Hydrochlorothiazide' then o.value_coded end) as diuretic_hctz,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Spironolactone' then o.value_coded end) as diuretic_spiro,
    max(case when o.concept = 'Level of dry cough' then o.value_coded end) as dry_cough,
    max(case when o.concept = 'Dyspnea on extertion' then o.value_coded end) as dyspnea_on_exertion,
    max(case when o.concept = 'Level of fatigue' then o.value_coded end) as fatigue,
    max(case when o.concept = 'Pulse' then o.value_numeric end) as heart_rate,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = 'Hospitalized for non-communicable disease since last visit' then o.value_coded end) as hospitalized_since_last_visit_for_ncd,
    max(case when o.concept = 'Jugular venous pressure elevated' then o.value_coded end) as jvp_elevated,
    max(case when o.concept = 'Mental health referral' then o.value_coded end) as mental_health_referral,
    max(case when o.concept = 'Appointment date' then o.value_date end) as next_appointment_date,
    max(case when o.concept = 'Nyha class' then o.value_coded end) as nyha_stage,
    max(case when o.concept = 'Oedema' then o.value_coded end) as oedema,
    max(case when o.concept = 'Level of orthopnea' then o.value_coded end) as orthopnea,
    max(case when o.concept = 'Other chronic heart failure drugs' then o.value_text end) as other_medications,
    max(case when o.concept = 'Palliative care referral' then o.value_coded end) as palliative_referral,
    max(case when o.concept = 'Follow up agreement' then o.value_coded end) as request_chw_f_u,
    max(case when o.concept = 'Salt or fluid restricted' then o.value_coded end) as salt_or_fluid_restricted,
    max(case when o.concept = 'Blood oxygen saturation' then o.value_numeric end) as spo2,
    max(case when o.concept = 'Smoking history' then o.value_coded end) as tobacco,
    max(case when o.concept = 'Took medications today' then o.value_coded end) as took_medications_today,
    max(case when o.concept = 'Patients fluid management' then o.value_coded end) as volume_status,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight,
    max(case when o.concept = 'Weight change' then o.value_text end) as weight_change
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('CHF_FOLLOWUP')
group by e.patient_id, e.encounter_date, e.location;