-- Derivation script for mw_diabetes_hypertension_initial
-- Generated from Pentaho transform: import-into-mw-diabetes-hypertension-initial.ktr

drop table if exists mw_diabetes_hypertension_initial;
create table mw_diabetes_hypertension_initial (
  initial_visit_id 				int not null auto_increment,
  patient_id    				int not null,
  visit_date            			date,
  location              			varchar(255),
  diagnosis_type_1_diabetes 			varchar(255),
  diagnosis_type_1_diabetes_date		date, 
  diagnosis_type_2_diabetes 			varchar(255),
  diagnosis_type_2_diabetes_date		date, 
  diagnosis_hypertension 			varchar(255),
  diagnosis_hypertension_date			date, 
  hiv_status		 			varchar(255),
  hiv_test_date				date, 
  art_start_date				date, 
  cardiovascular_disease			varchar(255),
  cardiovascular_disease_date			date,
  retinopathy					varchar(255),
  retinopathy_date				date,
  renal_disease				varchar(255),
  renal_disease_date				date,
  family_history_diabetes_mellitus		varchar(255),
  family_history_hypertension   		varchar(255),
  tb_status					varchar(255),
  tb_status_year		   		varchar(255),
  stroke_and_tia				varchar(255),
  stroke_and_tia_date				date,
  peripheral_vascular_disease			varchar(255),
  peripheral_vascular_disease_date		date,
  neuropathy					varchar(255),
  neuropathy_date				date,
  sexual_disorder				varchar(255),
  sexual_disorder_date				date,
     primary key (initial_visit_id)
);

insert into mw_diabetes_hypertension_initial
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Date antiretrovirals started' then o.value_date end) as art_start_date,
    max(case when o.concept = '' and o.value_coded = 'Cardiovascular disease' then o.value_coded end) as cardiovascular_disease,
    max(case when o.concept = '' and o.value_coded = 'Cardiovascular disease' then o.obs_group_id end) as cardiovascular_disease_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as cardiovascular_disease_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as cardiovascular_disease_obs_group_id,
    max(case when o.concept = 'Family History of Diabetes Mellitus' then o.value_coded end) as family_history_diabetes_mellitus,
    max(case when o.concept = 'Family history of hypertension' then o.value_coded end) as family_history_hypertension,
    max(case when o.concept = 'HIV status' then o.value_coded end) as hiv_status,
    max(case when o.concept = 'HIV test date' then o.value_date end) as hiv_test_date,
    max(case when o.concept = '' and o.value_coded = 'Hypertension' then o.value_coded end) as diagnosis_hypertension,
    max(case when o.concept = '' and o.value_coded = 'Hypertension' then o.obs_group_id end) as hypertension_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_hypertension_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as hypertension_obs_group_id,
    max(case when o.concept = '' and o.value_coded = 'Neuropathy' then o.value_coded end) as neuropathy,
    max(case when o.concept = '' and o.value_coded = 'Neuropathy' then o.obs_group_id end) as neuropathy_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as neuropathy_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as neuropathy_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as peripheral_vascular_disease_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as peripheral_vascular_disease_obs_group_id,
    max(case when o.concept = '' and o.value_coded = 'Peripheral vascular disease' then o.value_coded end) as peripheral_vascular_disease,
    max(case when o.concept = '' and o.value_coded = 'Peripheral vascular disease' then o.obs_group_id end) as peripheral_vascular_disease_obs_group_id,
    max(case when o.concept = '' and o.value_coded = 'Renal disease' then o.value_coded end) as renal_disease,
    max(case when o.concept = '' and o.value_coded = 'Renal disease' then o.obs_group_id end) as renal_disease_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as renal_disease_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as renal_disease_obs_group_id,
    max(case when o.concept = '' and o.value_coded = 'Retinopathy' then o.value_coded end) as retinopathy,
    max(case when o.concept = '' and o.value_coded = 'Retinopathy' then o.obs_group_id end) as retinopathy_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as retinopathy_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as retinopathy_obs_group_id,
    max(case when o.concept = '' and o.value_coded = 'Sexual Disorder' then o.value_coded end) as sexual_disorder,
    max(case when o.concept = '' and o.value_coded = 'Sexual Disorder' then o.obs_group_id end) as sexual_disorder_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as sexual_disorder_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as sexual_disorder_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as stroke_and_tia_date,
    max(case when o.concept = '' and o.value_coded = 'Stroke and Transient Ischemic Attack' then o.value_coded end) as stroke_and_tia,
    max(case when o.concept = 'TB status' then o.value_coded end) as tb_status,
    max(case when o.concept = 'Year of Tuberculosis diagnosis' then o.value_numeric end) as tb_status_year,
    max(case when o.concept = '' and o.value_coded = 'Type 1 diabetes' then o.value_coded end) as diagnosis_type_1_diabetes,
    max(case when o.concept = '' and o.value_coded = 'Type 1 diabetes' then o.obs_group_id end) as type_1_diabetes_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_type_1_diabetes_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as type_1_diabetes_obs_group_id,
    max(case when o.concept = '' and o.value_coded = 'Type 2 diabetes' then o.value_coded end) as diagnosis_type_2_diabetes,
    max(case when o.concept = '' and o.value_coded = 'Type 2 diabetes' then o.obs_group_id end) as type_2_diabetes_obs_group_id,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_type_2_diabetes_date,
    max(case when o.concept = 'Diagnosis date' then o.obs_group_id end) as type_2_diabetes_obs_group_id
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('DIABETES HYPERTENSION INITIAL VISIT')
group by e.patient_id, e.encounter_date, e.location;