-- Derivation script for mw_diabetes_hypertension_followup
-- Generated from Pentaho transform: import-into-mw-diabetes-hypertension-followup.ktr

DROP TABLE IF EXISTS mw_diabetes_hypertension_followup;
CREATE TABLE mw_diabetes_hypertension_followup (
  followup_visit_id 						INT NOT NULL AUTO_INCREMENT,
  patient_id    						INT NOT NULL,
  visit_date            					DATE,
  location              					VARCHAR(255),
  height							DECIMAL(10,2),
  weight							DECIMAL(10,2),
  body_mass_index 						VARCHAR(255),
  bp_stystolic							INT,
  bp_diastolic 						INT,
  pulse_rate							INT,
  hba1c							DECIMAL(10,2),
  fasting_blood_sugar						DECIMAL(10,2),
  blood_sugar_test_type					VARCHAR(255),
  tobbacco							VARCHAR(255),
  alcohol							VARCHAR(255),
  number_of_fruit_and_vegetable_portions			VARCHAR(255),
  days_per_week_with_30_min_of_exercise			INT,
  cardiovascular_risk						VARCHAR(255),
  visual_acuity						VARCHAR(255),
  neuropathy_or_pvd						VARCHAR(255),
  deformities							VARCHAR(255),
  ulcers					     		VARCHAR(255),
  hospitalized_since_last_visit				VARCHAR(255),
  diabetes_med_long_acting		 			VARCHAR(255),
  diabetes_med_short_acting		 			VARCHAR(255),
  diabetes_med_metformin		 			VARCHAR(255),
  diabetes_med_gilbenclamide		 			VARCHAR(255),
  diuretic_hctz			 			VARCHAR(255),
  diuretic_furp			 			VARCHAR(255),
  diuretic_spiro			 			VARCHAR(255),
  ccb_aml				 			VARCHAR(255),
  ccb_nif				 			VARCHAR(255),
  ace_i_enal				 			VARCHAR(255),
  ace_i_capt				 			VARCHAR(255),
  ace_i_lisin			 				VARCHAR(255),
  bb_aten				 			VARCHAR(255),
  bb_bis				 			VARCHAR(255),
  bb_prop				 			VARCHAR(255),
  asprin_asa				 			VARCHAR(255),
  statin_simva			 				VARCHAR(255),
  statin_prava				 			VARCHAR(255),
  statin_atorva			 			VARCHAR(255),
  other_hyd				 			VARCHAR(255),
  other_issmn				 			VARCHAR(255),
  next_appointment_date 					DATE,
     PRIMARY KEY (followup_visit_id)
);

INSERT INTO mw_diabetes_hypertension_followup
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'History of alcohol use' THEN o.value_coded END) as alcohol,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Amlodipine' THEN o.value_coded END) as ccb_aml,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Aspirin' THEN o.value_coded END) as asprin_asa,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Atenolol' THEN o.value_coded END) as bb_aten,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Atorvastatin' THEN o.value_coded END) as statin_atorva,
    MAX(CASE WHEN o.concept = 'Systolic blood pressure' THEN o.value_numeric END) as bp_stystolic,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Bisoprolol' THEN o.value_coded END) as bb_bis,
    MAX(CASE WHEN o.concept = 'Blood sugar test type' THEN o.value_coded END) as blood_sugar_test_type,
    MAX(CASE WHEN o.concept = 'Body Mass Index, coded' THEN o.value_coded END) as body_mass_index,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Captopril' THEN o.value_coded END) as ace_i_capt,
    MAX(CASE WHEN o.concept = 'Cardiovascular risk score' THEN o.value_numeric END) as cardiovascular_risk,
    MAX(CASE WHEN o.concept = 'Days per week of moderate exercise' THEN o.value_numeric END) as days_per_week_with_30_min_of_exercise,
    MAX(CASE WHEN o.concept = 'Deformity of foot' THEN o.value_coded END) as deformities,
    MAX(CASE WHEN o.concept = 'Diastolic blood pressure' THEN o.value_numeric END) as bp_diastolic,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Enalapril' THEN o.value_coded END) as ace_i_enal,
    MAX(CASE WHEN o.concept = 'Serum glucose' THEN o.value_numeric END) as fasting_blood_sugar,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Furosemide' THEN o.value_coded END) as diuretic_furp,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Glibenclamide' THEN o.value_coded END) as diabetes_med_gilbenclamide,
    MAX(CASE WHEN o.concept = 'Glycated hemoglobin' THEN o.value_numeric END) as hba1c,
    MAX(CASE WHEN o.concept = 'Height (cm)' THEN o.value_numeric END) as height,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Hydralazine' THEN o.value_coded END) as other_hyd,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Hydrochlorothiazide' THEN o.value_coded END) as diuretic_hctz,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Isosorbide mononitrate' THEN o.value_coded END) as other_issmn,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Lisinopril' THEN o.value_coded END) as ace_i_lisin,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Long acting insulin' THEN o.value_coded END) as diabetes_med_long_acting,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Metformin' THEN o.value_coded END) as diabetes_med_metformin,
    MAX(CASE WHEN o.concept = 'Neuropathy and Peripheral Vascular Disease' THEN o.value_coded END) as neuropathy_or_pvd,
    MAX(CASE WHEN o.concept = 'Appointment date' THEN o.value_date END) as next_appointment_date,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Nifedipine' THEN o.value_coded END) as ccb_nif,
    MAX(CASE WHEN o.concept = 'Number of servings of fruits and vegetables consumed per day' THEN o.value_numeric END) as number_of_fruit_and_vegetable_portions,
    MAX(CASE WHEN o.concept = 'Patient hospitalized since last visit' THEN o.value_coded END) as hospitalized_since_last_visit,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Pravastatin' THEN o.value_coded END) as statin_prava,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Propranolol' THEN o.value_coded END) as bb_prop,
    MAX(CASE WHEN o.concept = 'Pulse' THEN o.value_numeric END) as pulse_rate,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Insulin, soluble' THEN o.value_coded END) as diabetes_med_short_acting,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Simvastatin' THEN o.value_coded END) as statin_simva,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Spironolactone' THEN o.value_coded END) as diuretic_spiro,
    MAX(CASE WHEN o.concept = 'Smoking history' THEN o.value_coded END) as tobbacco,
    MAX(CASE WHEN o.concept = 'Foot ulcer or infection' THEN o.value_coded END) as ulcers,
    MAX(CASE WHEN o.concept = 'Visual acuity (text)' THEN o.value_text END) as visual_acuity,
    MAX(CASE WHEN o.concept = 'Weight (kg)' THEN o.value_numeric END) as weight
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('DIABETES HYPERTENSION FOLLOWUP')
GROUP BY e.patient_id, e.encounter_date, e.location;