-- Derivation script for mw_diabetes_hypertension_initial
-- Generated from Pentaho transform: import-into-mw-diabetes-hypertension-initial.ktr

DROP TABLE IF EXISTS mw_diabetes_hypertension_initial;
CREATE TABLE mw_diabetes_hypertension_initial (
  initial_visit_id 				INT NOT NULL AUTO_INCREMENT,
  patient_id    				INT NOT NULL,
  visit_date            			DATE,
  location              			VARCHAR(255),
  diagnosis_type_1_diabetes 			VARCHAR(255),
  diagnosis_type_1_diabetes_date		DATE, 
  diagnosis_type_2_diabetes 			VARCHAR(255),
  diagnosis_type_2_diabetes_date		DATE, 
  diagnosis_hypertension 			VARCHAR(255),
  diagnosis_hypertension_date			DATE, 
  hiv_status		 			VARCHAR(255),
  hiv_test_date				DATE, 
  art_start_date				DATE, 
  cardiovascular_disease			VARCHAR(255),
  cardiovascular_disease_date			DATE,
  retinopathy					VARCHAR(255),
  retinopathy_date				DATE,
  renal_disease				VARCHAR(255),
  renal_disease_date				DATE,
  family_history_diabetes_mellitus		VARCHAR(255),
  family_history_hypertension   		VARCHAR(255),
  tb_status					VARCHAR(255),
  tb_status_year		   		VARCHAR(255),
  stroke_and_tia				VARCHAR(255),
  stroke_and_tia_date				DATE,
  peripheral_vascular_disease			VARCHAR(255),
  peripheral_vascular_disease_date		DATE,
  neuropathy					VARCHAR(255),
  neuropathy_date				DATE,
  sexual_disorder				VARCHAR(255),
  sexual_disorder_date				DATE,
     PRIMARY KEY (initial_visit_id)
);

INSERT INTO mw_diabetes_hypertension_initial
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Date antiretrovirals started' THEN o.value_date END) as art_start_date,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Cardiovascular disease' THEN o.value_coded END) as cardiovascular_disease,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Cardiovascular disease' THEN o.obs_group_id END) as cardiovascular_disease_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as cardiovascular_disease_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as cardiovascular_disease_obs_group_id,
    MAX(CASE WHEN o.concept = 'Family History of Diabetes Mellitus' THEN o.value_coded END) as family_history_diabetes_mellitus,
    MAX(CASE WHEN o.concept = 'Family history of hypertension' THEN o.value_coded END) as family_history_hypertension,
    MAX(CASE WHEN o.concept = 'HIV status' THEN o.value_coded END) as hiv_status,
    MAX(CASE WHEN o.concept = 'HIV test date' THEN o.value_date END) as hiv_test_date,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Hypertension' THEN o.value_coded END) as diagnosis_hypertension,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Hypertension' THEN o.obs_group_id END) as hypertension_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_hypertension_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as hypertension_obs_group_id,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Neuropathy' THEN o.value_coded END) as neuropathy,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Neuropathy' THEN o.obs_group_id END) as neuropathy_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as neuropathy_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as neuropathy_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as peripheral_vascular_disease_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as peripheral_vascular_disease_obs_group_id,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Peripheral vascular disease' THEN o.value_coded END) as peripheral_vascular_disease,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Peripheral vascular disease' THEN o.obs_group_id END) as peripheral_vascular_disease_obs_group_id,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Renal disease' THEN o.value_coded END) as renal_disease,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Renal disease' THEN o.obs_group_id END) as renal_disease_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as renal_disease_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as renal_disease_obs_group_id,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Retinopathy' THEN o.value_coded END) as retinopathy,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Retinopathy' THEN o.obs_group_id END) as retinopathy_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as retinopathy_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as retinopathy_obs_group_id,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Sexual Disorder' THEN o.value_coded END) as sexual_disorder,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Sexual Disorder' THEN o.obs_group_id END) as sexual_disorder_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as sexual_disorder_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as sexual_disorder_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as stroke_and_tia_date,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Stroke and Transient Ischemic Attack' THEN o.value_coded END) as stroke_and_tia,
    MAX(CASE WHEN o.concept = 'TB status' THEN o.value_coded END) as tb_status,
    MAX(CASE WHEN o.concept = 'Year of Tuberculosis diagnosis' THEN o.value_numeric END) as tb_status_year,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Type 1 diabetes' THEN o.value_coded END) as diagnosis_type_1_diabetes,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Type 1 diabetes' THEN o.obs_group_id END) as type_1_diabetes_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_type_1_diabetes_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as type_1_diabetes_obs_group_id,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Type 2 diabetes' THEN o.value_coded END) as diagnosis_type_2_diabetes,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Type 2 diabetes' THEN o.obs_group_id END) as type_2_diabetes_obs_group_id,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_type_2_diabetes_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.obs_group_id END) as type_2_diabetes_obs_group_id
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('DIABETES HYPERTENSION INITIAL VISIT')
GROUP BY e.patient_id, e.encounter_date, e.location;