-- Derivation script for mw_diabetes_hypertension_followup
-- Generated from Pentaho transform: import-into-mw-diabetes-hypertension-followup.ktr

drop table if exists mw_diabetes_hypertension_followup;
create table mw_diabetes_hypertension_followup (
  followup_visit_id 						int not null auto_increment,
  patient_id    						int not null,
  visit_date            					date,
  location              					varchar(255),
  height							decimal(10,2),
  weight							decimal(10,2),
  body_mass_index 						varchar(255),
  bp_stystolic							int,
  bp_diastolic 						int,
  pulse_rate							int,
  hba1c							decimal(10,2),
  fasting_blood_sugar						decimal(10,2),
  blood_sugar_test_type					varchar(255),
  tobbacco							varchar(255),
  alcohol							varchar(255),
  number_of_fruit_and_vegetable_portions			varchar(255),
  days_per_week_with_30_min_of_exercise			int,
  cardiovascular_risk						varchar(255),
  visual_acuity						varchar(255),
  neuropathy_or_pvd						varchar(255),
  deformities							varchar(255),
  ulcers					     		varchar(255),
  hospitalized_since_last_visit				varchar(255),
  diabetes_med_long_acting		 			varchar(255),
  diabetes_med_short_acting		 			varchar(255),
  diabetes_med_metformin		 			varchar(255),
  diabetes_med_gilbenclamide		 			varchar(255),
  diuretic_hctz			 			varchar(255),
  diuretic_furp			 			varchar(255),
  diuretic_spiro			 			varchar(255),
  ccb_aml				 			varchar(255),
  ccb_nif				 			varchar(255),
  ace_i_enal				 			varchar(255),
  ace_i_capt				 			varchar(255),
  ace_i_lisin			 				varchar(255),
  bb_aten				 			varchar(255),
  bb_bis				 			varchar(255),
  bb_prop				 			varchar(255),
  asprin_asa				 			varchar(255),
  statin_simva			 				varchar(255),
  statin_prava				 			varchar(255),
  statin_atorva			 			varchar(255),
  other_hyd				 			varchar(255),
  other_issmn				 			varchar(255),
  next_appointment_date 					date,
     primary key (followup_visit_id)
);

insert into mw_diabetes_hypertension_followup
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'History of alcohol use' then o.value_coded end) as alcohol,
    max(case when o.concept = '' and o.value_coded = 'Amlodipine' then o.value_coded end) as ccb_aml,
    max(case when o.concept = '' and o.value_coded = 'Aspirin' then o.value_coded end) as asprin_asa,
    max(case when o.concept = '' and o.value_coded = 'Atenolol' then o.value_coded end) as bb_aten,
    max(case when o.concept = '' and o.value_coded = 'Atorvastatin' then o.value_coded end) as statin_atorva,
    max(case when o.concept = 'Systolic blood pressure' then o.value_numeric end) as bp_stystolic,
    max(case when o.concept = '' and o.value_coded = 'Bisoprolol' then o.value_coded end) as bb_bis,
    max(case when o.concept = 'Blood sugar test type' then o.value_coded end) as blood_sugar_test_type,
    max(case when o.concept = 'Body Mass Index, coded' then o.value_coded end) as body_mass_index,
    max(case when o.concept = '' and o.value_coded = 'Captopril' then o.value_coded end) as ace_i_capt,
    max(case when o.concept = 'Cardiovascular risk score' then o.value_numeric end) as cardiovascular_risk,
    max(case when o.concept = 'Days per week of moderate exercise' then o.value_numeric end) as days_per_week_with_30_min_of_exercise,
    max(case when o.concept = 'Deformity of foot' then o.value_coded end) as deformities,
    max(case when o.concept = 'Diastolic blood pressure' then o.value_numeric end) as bp_diastolic,
    max(case when o.concept = '' and o.value_coded = 'Enalapril' then o.value_coded end) as ace_i_enal,
    max(case when o.concept = 'Serum glucose' then o.value_numeric end) as fasting_blood_sugar,
    max(case when o.concept = '' and o.value_coded = 'Furosemide' then o.value_coded end) as diuretic_furp,
    max(case when o.concept = '' and o.value_coded = 'Glibenclamide' then o.value_coded end) as diabetes_med_gilbenclamide,
    max(case when o.concept = 'Glycated hemoglobin' then o.value_numeric end) as hba1c,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = '' and o.value_coded = 'Hydralazine' then o.value_coded end) as other_hyd,
    max(case when o.concept = '' and o.value_coded = 'Hydrochlorothiazide' then o.value_coded end) as diuretic_hctz,
    max(case when o.concept = '' and o.value_coded = 'Isosorbide mononitrate' then o.value_coded end) as other_issmn,
    max(case when o.concept = '' and o.value_coded = 'Lisinopril' then o.value_coded end) as ace_i_lisin,
    max(case when o.concept = '' and o.value_coded = 'Long acting insulin' then o.value_coded end) as diabetes_med_long_acting,
    max(case when o.concept = '' and o.value_coded = 'Metformin' then o.value_coded end) as diabetes_med_metformin,
    max(case when o.concept = 'Neuropathy and Peripheral Vascular Disease' then o.value_coded end) as neuropathy_or_pvd,
    max(case when o.concept = 'Appointment date' then o.value_date end) as next_appointment_date,
    max(case when o.concept = '' and o.value_coded = 'Nifedipine' then o.value_coded end) as ccb_nif,
    max(case when o.concept = 'Number of servings of fruits and vegetables consumed per day' then o.value_numeric end) as number_of_fruit_and_vegetable_portions,
    max(case when o.concept = 'Patient hospitalized since last visit' then o.value_coded end) as hospitalized_since_last_visit,
    max(case when o.concept = '' and o.value_coded = 'Pravastatin' then o.value_coded end) as statin_prava,
    max(case when o.concept = '' and o.value_coded = 'Propranolol' then o.value_coded end) as bb_prop,
    max(case when o.concept = 'Pulse' then o.value_numeric end) as pulse_rate,
    max(case when o.concept = '' and o.value_coded = 'Insulin, soluble' then o.value_coded end) as diabetes_med_short_acting,
    max(case when o.concept = '' and o.value_coded = 'Simvastatin' then o.value_coded end) as statin_simva,
    max(case when o.concept = '' and o.value_coded = 'Spironolactone' then o.value_coded end) as diuretic_spiro,
    max(case when o.concept = 'Smoking history' then o.value_coded end) as tobbacco,
    max(case when o.concept = 'Foot ulcer or infection' then o.value_coded end) as ulcers,
    max(case when o.concept = 'Visual acuity (text)' then o.value_text end) as visual_acuity,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('DIABETES HYPERTENSION FOLLOWUP')
group by e.patient_id, e.encounter_date, e.location;