-- Derivation script for mw_epilepsy_initial
-- Generated from Pentaho transform: import-into-mw-epilepsy-initial.ktr

drop table if exists mw_epilepsy_initial;
create table mw_epilepsy_initial (
  epilepsy_initial_visit_id 			int not null auto_increment,
  patient_id 					int not null,
  visit_date 					date default null,
  location 					varchar(255) default null,
  seizure_type_tonic_clonic 			varchar(255) default null,
  seizure_type_clonic 				varchar(255) default null,
  seizure_type_simple 				varchar(255) default null,
  seizure_type_absence 			varchar(255) default null,
  seizure_type_tonic 				varchar(255) default null,
  seizure_type_complex 			varchar(255) default null,
  seizure_type_myoclonic 			varchar(255) default null,
  seizure_type_atonic 				varchar(255) default null,
  seizure_type_unclassified 			varchar(255) default null,
  epilepsy_family_history 			varchar(255) default null,
  mental_health_family_history 		varchar(255) default null,
  behavioral_family_history 			varchar(255) default null,
  hiv_status 					varchar(255) default null,
  hiv_test_date 				date default null,
  art_start_date 				date default null,
  vdrl 					varchar(255) default null,
  month_of_onset 				int(11) default null,
  year_of_onset 				int(11) default null,
  age_at_onset 				int default null,
  marital_status 				varchar(255) default null,
  occupation 					varchar(255) default null,
  education_level 				varchar(255) default null,
  medication_history 				varchar(255) default null,
  pre_ictal_warning 				varchar(255) default null,
  post_ictal_headache 				varchar(255) default null,
  post_ictal_drowsiness 			varchar(255) default null,
  post_ictal_poor_concentration 		varchar(255) default null,
  post_ictal_poor_verbal_or_cognition 	varchar(255) default null,
  post_ictal_paralysis 			varchar(255) default null,
  post_ictal_disorientation 			varchar(255) default null,
  post_ictal_nausea 				varchar(255) default null,
  post_ictal_memory_loss		 	varchar(255) default null,
  post_ictal_hyperactivity 			varchar(255) default null,
  head_trauma_injury_surgery 			varchar(255) default null,
  history_of_seizure 				varchar(255) default null,
  complications_at_birth			varchar(255) default null,
  neonatal_infection_cerebral_malaria_meningitis varchar(255) default null,
  delayed_milestones 				varchar(255) default null,
  alcohol_trigger 				varchar(255) default null,
  fever_trigger 				varchar(255) default null,
  sound_light_and_touch_trigger 		varchar(255) default null,
  emotional_stress_anger_boredom_trigger 	varchar(255) default null,
  sleep_deprivation_and_overtired_trigger 	varchar(255) default null,
  missed_medication_trigger 			varchar(255) default null,
  menstruation_trigger 			varchar(255) default null,
  smoking_exposure 				varchar(255) default null,
  smoking_date_of_exposure 			date default null,
  alcohol_exposure 				varchar(255) default null,
  alcohol_date_of_exposure	 		date default null,
  pig_exposure 				varchar(255) default null,
  pig_date_of_exposure 			date default null,
  traditional_medicine_exposure		varchar(255) default null,
  traditional_medicine_date_of_exposure 	varchar(255) default null,
  injury_complication			 	varchar(255) default null,
  date_of_injury_complication 		date default null,
  burn_complication				varchar(255) default null,
  date_of_burn_complication			date default null,
  status_epilepticus_complication 		varchar(255) default null,
  date_of_status_epilepticus_complication 	date default null,
  psychosis_complication		 	varchar(255) default null,
  date_of_psychosis_complication	 	date default null,
  drug_related_complication		 	varchar(255) default null,
  drug_related_complication_date	 	date default null,
  other_complication			 	varchar(255) default null,
  other_complication_date 			date default null,
  primary key (epilepsy_initial_visit_id)
) ;

insert into mw_epilepsy_initial
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Age of epilepsy diagnosis' then o.value_numeric end) as age_at_onset,
    max(case when o.concept = 'Date of exposure' then o.value_date end) as alcohol_date_of_exposure,
    max(case when o.concept = 'Exposure' and o.value_coded = 'Alcohol' then o.value_coded end) as alcohol_exposure,
    max(case when o.concept = 'Alcohol trigger' then o.value_coded end) as alcohol_trigger,
    max(case when o.concept = 'Date antiretrovirals started' then o.value_date end) as art_start_date,
    max(case when o.concept = 'Family history of behavioral problems' then o.value_coded end) as behavioral_family_history,
    max(case when o.concept = 'Epilepsy complications' and o.value_coded = 'Burn' then o.value_coded end) as burn_complication,
    max(case when o.concept = 'Epilepsy complications' and o.value_coded = 'Burn' then o.obs_group_id end) as obs_group_burn_complication,
    max(case when o.concept = 'Complications at birth' then o.value_coded end) as complications_at_birth,
    max(case when o.concept = 'Date of complication' then o.value_date end) as date_of_burn_complication,
    max(case when o.concept = 'Date of complication' then o.obs_group_id end) as obs_group_burn_complication,
    max(case when o.concept = 'Date of complication' then o.value_date end) as date_of_injury_complication,
    max(case when o.concept = 'Date of complication' then o.value_date end) as date_of_psychosis_complication,
    max(case when o.concept = 'Date of complication' then o.value_date end) as date_of_status_epilepticus_complication,
    max(case when o.concept = 'Date of complication' then o.obs_group_id end) as obs_group_epilepticus_complication,
    max(case when o.concept = 'Delayed milestones' then o.value_coded end) as delayed_milestones,
    max(case when o.concept = 'Epilepsy complications' and o.value_coded = 'Side effects of treatment' then o.value_coded end) as drug_related_complication,
    max(case when o.concept = 'Date of complication' then o.value_date end) as drug_related_complication_date,
    max(case when o.concept = 'Highest level of school completed' then o.value_coded end) as education_level,
    max(case when o.concept = 'Emotional stress, anger, boredom' then o.value_coded end) as emotional_stress_anger_boredom_trigger,
    max(case when o.concept = 'Family history of epilepsy' then o.value_coded end) as epilepsy_family_history,
    max(case when o.concept = 'Fever trigger' then o.value_coded end) as fever_trigger,
    max(case when o.concept = 'Injury, trauma, surgery of head' then o.value_coded end) as head_trauma_injury_surgery,
    max(case when o.concept = 'History of seizure' then o.value_coded end) as history_of_seizure,
    max(case when o.concept = 'HIV status' then o.value_coded end) as hiv_status,
    max(case when o.concept = 'HIV test date' then o.value_date end) as hiv_test_date,
    max(case when o.concept = 'Epilepsy complications' and o.value_coded = 'Injury' then o.value_coded end) as injury_complication,
    max(case when o.concept = 'Civil status' then o.value_coded end) as marital_status,
    max(case when o.concept = 'Medication history (text)' then o.value_text end) as medication_history,
    max(case when o.concept = 'Menstruation trigger' then o.value_coded end) as menstruation_trigger,
    max(case when o.concept = 'Family history of mental illness' then o.value_coded end) as mental_health_family_history,
    max(case when o.concept = 'Missed medication trigger' then o.value_coded end) as missed_medication_trigger,
    max(case when o.concept = 'Month of onset' then o.value_numeric end) as month_of_onset,
    max(case when o.concept = 'Neonatal infection, Cerebral Malaria, and/or Meningitis' then o.value_coded end) as neonatal_infection_cerebral_malaria_meningitis,
    max(case when o.concept = 'Main activity' then o.value_coded end) as occupation,
    max(case when o.concept = 'Epilepsy complications' and o.value_coded = 'Other' then o.value_coded end) as other_complication,
    max(case when o.concept = 'Date of complication' then o.value_date end) as other_complication_date,
    max(case when o.concept = 'Date of exposure' then o.value_date end) as pig_date_of_exposure,
    max(case when o.concept = 'Exposure' and o.value_coded = 'Pig' then o.value_coded end) as pig_exposure,
    max(case when o.concept = 'Post-ictal disorientation' then o.value_coded end) as post_ictal_disorientation,
    max(case when o.concept = 'Post-ictal drowsiness' then o.value_coded end) as post_ictal_drowsiness,
    max(case when o.concept = 'Post-ictal headache' then o.value_coded end) as post_ictal_headache,
    max(case when o.concept = 'Post-ictal hyperactivity' then o.value_coded end) as post_ictal_hyperactivity,
    max(case when o.concept = 'Post-ictal memory loss' then o.value_coded end) as post_ictal_memory_loss,
    max(case when o.concept = 'Post-ictal nausea' then o.value_coded end) as post_ictal_nausea,
    max(case when o.concept = 'Post-ictal paralysis' then o.value_coded end) as post_ictal_paralysis,
    max(case when o.concept = 'Post-ictal poor concentration' then o.value_coded end) as post_ictal_poor_concentration,
    max(case when o.concept = 'Post-ictal poor verbal or cognition' then o.value_coded end) as post_ictal_poor_verbal_or_cognition,
    max(case when o.concept = 'Pre-ictal warning' then o.value_coded end) as pre_ictal_warning,
    max(case when o.concept = 'Epilepsy complications' and o.value_coded = 'Injury' then o.value_coded end) as psychosis_complication,
    max(case when o.concept = 'Absence seizures' then o.value_coded end) as seizure_type_absence,
    max(case when o.concept = 'Atonic seizures' then o.value_coded end) as seizure_type_atonic,
    max(case when o.concept = 'Clonic seizures' then o.value_coded end) as seizure_type_clonic,
    max(case when o.concept = 'Complex partial seizure' then o.value_coded end) as seizure_type_complex,
    max(case when o.concept = 'Myoclonic seizures' then o.value_coded end) as seizure_type_myoclonic,
    max(case when o.concept = 'Simple partial seizure' then o.value_coded end) as seizure_type_simple,
    max(case when o.concept = 'Tonic seizures' then o.value_coded end) as seizure_type_tonic,
    max(case when o.concept = 'Seizures grandmal' then o.value_coded end) as seizure_type_tonic_clonic,
    max(case when o.concept = 'Unclassified epileptic seizures' then o.value_coded end) as seizure_type_unclassified,
    max(case when o.concept = 'Sleep deprivation and overtired' then o.value_coded end) as sleep_deprivation_and_overtired_trigger,
    max(case when o.concept = 'Date of exposure' then o.value_date end) as smoking_date_of_exposure,
    max(case when o.concept = 'Exposure' and o.value_coded = 'Smoking' then o.value_coded end) as smoking_exposure,
    max(case when o.concept = 'Sound, light, and touch' then o.value_coded end) as sound_light_and_touch_trigger,
    max(case when o.concept = 'Epilepsy complications' and o.value_coded = 'Status epilepticus' then o.value_coded end) as status_epilepticus_complication,
    max(case when o.concept = 'Epilepsy complications' and o.value_coded = 'Status epilepticus' then o.obs_group_id end) as obs_group_epilepticus_complication,
    max(case when o.concept = 'Date of exposure' then o.value_date end) as traditional_medicine_date_of_exposure,
    max(case when o.concept = 'Exposure' and o.value_coded = 'Traditional medicine' then o.value_coded end) as traditional_medicine_exposure,
    max(case when o.concept = 'Vdrl' then o.value_coded end) as vdrl,
    max(case when o.concept = 'Year of onset' then o.value_numeric end) as year_of_onset
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('EPILEPSY_INITIAL')
group by e.patient_id, e.encounter_date, e.location;