-- Derivation script for mw_epilepsy_initial
-- Generated from Pentaho transform: import-into-mw-epilepsy-initial.ktr

DROP TABLE IF EXISTS mw_epilepsy_initial;
CREATE TABLE mw_epilepsy_initial (
  epilepsy_initial_visit_id 			int NOT NULL AUTO_INCREMENT,
  patient_id 					int NOT NULL,
  visit_date 					date DEFAULT NULL,
  location 					varchar(255) DEFAULT NULL,
  seizure_type_tonic_clonic 			varchar(255) DEFAULT NULL,
  seizure_type_clonic 				varchar(255) DEFAULT NULL,
  seizure_type_simple 				varchar(255) DEFAULT NULL,
  seizure_type_absence 			varchar(255) DEFAULT NULL,
  seizure_type_tonic 				varchar(255) DEFAULT NULL,
  seizure_type_complex 			varchar(255) DEFAULT NULL,
  seizure_type_myoclonic 			varchar(255) DEFAULT NULL,
  seizure_type_atonic 				varchar(255) DEFAULT NULL,
  seizure_type_unclassified 			varchar(255) DEFAULT NULL,
  epilepsy_family_history 			varchar(255) DEFAULT NULL,
  mental_health_family_history 		varchar(255) DEFAULT NULL,
  behavioral_family_history 			varchar(255) DEFAULT NULL,
  hiv_status 					varchar(255) DEFAULT NULL,
  hiv_test_date 				date DEFAULT NULL,
  art_start_date 				date DEFAULT NULL,
  vdrl 					varchar(255) DEFAULT NULL,
  month_of_onset 				int(11) DEFAULT NULL,
  year_of_onset 				int(11) DEFAULT NULL,
  age_at_onset 				int DEFAULT NULL,
  marital_status 				varchar(255) DEFAULT NULL,
  occupation 					varchar(255) DEFAULT NULL,
  education_level 				varchar(255) DEFAULT NULL,
  medication_history 				varchar(255) DEFAULT NULL,
  pre_ictal_warning 				varchar(255) DEFAULT NULL,
  post_ictal_headache 				varchar(255) DEFAULT NULL,
  post_ictal_drowsiness 			varchar(255) DEFAULT NULL,
  post_ictal_poor_concentration 		varchar(255) DEFAULT NULL,
  post_ictal_poor_verbal_or_cognition 	varchar(255) DEFAULT NULL,
  post_ictal_paralysis 			varchar(255) DEFAULT NULL,
  post_ictal_disorientation 			varchar(255) DEFAULT NULL,
  post_ictal_nausea 				varchar(255) DEFAULT NULL,
  post_ictal_memory_loss		 	varchar(255) DEFAULT NULL,
  post_ictal_hyperactivity 			varchar(255) DEFAULT NULL,
  head_trauma_injury_surgery 			varchar(255) DEFAULT NULL,
  history_of_seizure 				varchar(255) DEFAULT NULL,
  complications_at_birth			varchar(255) DEFAULT NULL,
  neonatal_infection_cerebral_malaria_meningitis varchar(255) DEFAULT NULL,
  delayed_milestones 				varchar(255) DEFAULT NULL,
  alcohol_trigger 				varchar(255) DEFAULT NULL,
  fever_trigger 				varchar(255) DEFAULT NULL,
  sound_light_and_touch_trigger 		varchar(255) DEFAULT NULL,
  emotional_stress_anger_boredom_trigger 	varchar(255) DEFAULT NULL,
  sleep_deprivation_and_overtired_trigger 	varchar(255) DEFAULT NULL,
  missed_medication_trigger 			varchar(255) DEFAULT NULL,
  menstruation_trigger 			varchar(255) DEFAULT NULL,
  smoking_exposure 				varchar(255) DEFAULT NULL,
  smoking_date_of_exposure 			date DEFAULT NULL,
  alcohol_exposure 				varchar(255) DEFAULT NULL,
  alcohol_date_of_exposure	 		date DEFAULT NULL,
  pig_exposure 				varchar(255) DEFAULT NULL,
  pig_date_of_exposure 			date DEFAULT NULL,
  traditional_medicine_exposure		varchar(255) DEFAULT NULL,
  traditional_medicine_date_of_exposure 	varchar(255) DEFAULT NULL,
  injury_complication			 	varchar(255) DEFAULT NULL,
  date_of_injury_complication 		date DEFAULT NULL,
  burn_complication				varchar(255) DEFAULT NULL,
  date_of_burn_complication			date DEFAULT NULL,
  status_epilepticus_complication 		varchar(255) DEFAULT NULL,
  date_of_status_epilepticus_complication 	date DEFAULT NULL,
  psychosis_complication		 	varchar(255) DEFAULT NULL,
  date_of_psychosis_complication	 	date DEFAULT NULL,
  drug_related_complication		 	varchar(255) DEFAULT NULL,
  drug_related_complication_date	 	date DEFAULT NULL,
  other_complication			 	varchar(255) DEFAULT NULL,
  other_complication_date 			date DEFAULT NULL,
  PRIMARY KEY (epilepsy_initial_visit_id)
) ;

INSERT INTO mw_epilepsy_initial
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Age of epilepsy diagnosis' THEN o.value_numeric END) as age_at_onset,
    MAX(CASE WHEN o.concept = 'Date of exposure' THEN o.value_date END) as alcohol_date_of_exposure,
    MAX(CASE WHEN o.concept = 'Exposure' AND o.value_coded = 'Alcohol' THEN o.value_coded END) as alcohol_exposure,
    MAX(CASE WHEN o.concept = 'Alcohol trigger' THEN o.value_coded END) as alcohol_trigger,
    MAX(CASE WHEN o.concept = 'Date antiretrovirals started' THEN o.value_date END) as art_start_date,
    MAX(CASE WHEN o.concept = 'Family history of behavioral problems' THEN o.value_coded END) as behavioral_family_history,
    MAX(CASE WHEN o.concept = 'Epilepsy complications' AND o.value_coded = 'Burn' THEN o.value_coded END) as burn_complication,
    MAX(CASE WHEN o.concept = 'Epilepsy complications' AND o.value_coded = 'Burn' THEN o.obs_group_id END) as obs_group_burn_complication,
    MAX(CASE WHEN o.concept = 'Complications at birth' THEN o.value_coded END) as complications_at_birth,
    MAX(CASE WHEN o.concept = 'Date of complication' THEN o.value_date END) as date_of_burn_complication,
    MAX(CASE WHEN o.concept = 'Date of complication' THEN o.obs_group_id END) as obs_group_burn_complication,
    MAX(CASE WHEN o.concept = 'Date of complication' THEN o.value_date END) as date_of_injury_complication,
    MAX(CASE WHEN o.concept = 'Date of complication' THEN o.value_date END) as date_of_psychosis_complication,
    MAX(CASE WHEN o.concept = 'Date of complication' THEN o.value_date END) as date_of_status_epilepticus_complication,
    MAX(CASE WHEN o.concept = 'Date of complication' THEN o.obs_group_id END) as obs_group_epilepticus_complication,
    MAX(CASE WHEN o.concept = 'Delayed milestones' THEN o.value_coded END) as delayed_milestones,
    MAX(CASE WHEN o.concept = 'Epilepsy complications' AND o.value_coded = 'Side effects of treatment' THEN o.value_coded END) as drug_related_complication,
    MAX(CASE WHEN o.concept = 'Date of complication' THEN o.value_date END) as drug_related_complication_date,
    MAX(CASE WHEN o.concept = 'Highest level of school completed' THEN o.value_coded END) as education_level,
    MAX(CASE WHEN o.concept = 'Emotional stress, anger, boredom' THEN o.value_coded END) as emotional_stress_anger_boredom_trigger,
    MAX(CASE WHEN o.concept = 'Family history of epilepsy' THEN o.value_coded END) as epilepsy_family_history,
    MAX(CASE WHEN o.concept = 'Fever trigger' THEN o.value_coded END) as fever_trigger,
    MAX(CASE WHEN o.concept = 'Injury, trauma, surgery of head' THEN o.value_coded END) as head_trauma_injury_surgery,
    MAX(CASE WHEN o.concept = 'History of seizure' THEN o.value_coded END) as history_of_seizure,
    MAX(CASE WHEN o.concept = 'HIV status' THEN o.value_coded END) as hiv_status,
    MAX(CASE WHEN o.concept = 'HIV test date' THEN o.value_date END) as hiv_test_date,
    MAX(CASE WHEN o.concept = 'Epilepsy complications' AND o.value_coded = 'Injury' THEN o.value_coded END) as injury_complication,
    MAX(CASE WHEN o.concept = 'Civil status' THEN o.value_coded END) as marital_status,
    MAX(CASE WHEN o.concept = 'Medication history (text)' THEN o.value_text END) as medication_history,
    MAX(CASE WHEN o.concept = 'Menstruation trigger' THEN o.value_coded END) as menstruation_trigger,
    MAX(CASE WHEN o.concept = 'Family history of mental illness' THEN o.value_coded END) as mental_health_family_history,
    MAX(CASE WHEN o.concept = 'Missed medication trigger' THEN o.value_coded END) as missed_medication_trigger,
    MAX(CASE WHEN o.concept = 'Month of onset' THEN o.value_numeric END) as month_of_onset,
    MAX(CASE WHEN o.concept = 'Neonatal infection, Cerebral Malaria, and/or Meningitis' THEN o.value_coded END) as neonatal_infection_cerebral_malaria_meningitis,
    MAX(CASE WHEN o.concept = 'Main activity' THEN o.value_coded END) as occupation,
    MAX(CASE WHEN o.concept = 'Epilepsy complications' AND o.value_coded = 'Other' THEN o.value_coded END) as other_complication,
    MAX(CASE WHEN o.concept = 'Date of complication' THEN o.value_date END) as other_complication_date,
    MAX(CASE WHEN o.concept = 'Date of exposure' THEN o.value_date END) as pig_date_of_exposure,
    MAX(CASE WHEN o.concept = 'Exposure' AND o.value_coded = 'Pig' THEN o.value_coded END) as pig_exposure,
    MAX(CASE WHEN o.concept = 'Post-ictal disorientation' THEN o.value_coded END) as post_ictal_disorientation,
    MAX(CASE WHEN o.concept = 'Post-ictal drowsiness' THEN o.value_coded END) as post_ictal_drowsiness,
    MAX(CASE WHEN o.concept = 'Post-ictal headache' THEN o.value_coded END) as post_ictal_headache,
    MAX(CASE WHEN o.concept = 'Post-ictal hyperactivity' THEN o.value_coded END) as post_ictal_hyperactivity,
    MAX(CASE WHEN o.concept = 'Post-ictal memory loss' THEN o.value_coded END) as post_ictal_memory_loss,
    MAX(CASE WHEN o.concept = 'Post-ictal nausea' THEN o.value_coded END) as post_ictal_nausea,
    MAX(CASE WHEN o.concept = 'Post-ictal paralysis' THEN o.value_coded END) as post_ictal_paralysis,
    MAX(CASE WHEN o.concept = 'Post-ictal poor concentration' THEN o.value_coded END) as post_ictal_poor_concentration,
    MAX(CASE WHEN o.concept = 'Post-ictal poor verbal or cognition' THEN o.value_coded END) as post_ictal_poor_verbal_or_cognition,
    MAX(CASE WHEN o.concept = 'Pre-ictal warning' THEN o.value_coded END) as pre_ictal_warning,
    MAX(CASE WHEN o.concept = 'Epilepsy complications' AND o.value_coded = 'Injury' THEN o.value_coded END) as psychosis_complication,
    MAX(CASE WHEN o.concept = 'Absence seizures' THEN o.value_coded END) as seizure_type_absence,
    MAX(CASE WHEN o.concept = 'Atonic seizures' THEN o.value_coded END) as seizure_type_atonic,
    MAX(CASE WHEN o.concept = 'Clonic seizures' THEN o.value_coded END) as seizure_type_clonic,
    MAX(CASE WHEN o.concept = 'Complex partial seizure' THEN o.value_coded END) as seizure_type_complex,
    MAX(CASE WHEN o.concept = 'Myoclonic seizures' THEN o.value_coded END) as seizure_type_myoclonic,
    MAX(CASE WHEN o.concept = 'Simple partial seizure' THEN o.value_coded END) as seizure_type_simple,
    MAX(CASE WHEN o.concept = 'Tonic seizures' THEN o.value_coded END) as seizure_type_tonic,
    MAX(CASE WHEN o.concept = 'Seizures grandmal' THEN o.value_coded END) as seizure_type_tonic_clonic,
    MAX(CASE WHEN o.concept = 'Unclassified epileptic seizures' THEN o.value_coded END) as seizure_type_unclassified,
    MAX(CASE WHEN o.concept = 'Sleep deprivation and overtired' THEN o.value_coded END) as sleep_deprivation_and_overtired_trigger,
    MAX(CASE WHEN o.concept = 'Date of exposure' THEN o.value_date END) as smoking_date_of_exposure,
    MAX(CASE WHEN o.concept = 'Exposure' AND o.value_coded = 'Smoking' THEN o.value_coded END) as smoking_exposure,
    MAX(CASE WHEN o.concept = 'Sound, light, and touch' THEN o.value_coded END) as sound_light_and_touch_trigger,
    MAX(CASE WHEN o.concept = 'Epilepsy complications' AND o.value_coded = 'Status epilepticus' THEN o.value_coded END) as status_epilepticus_complication,
    MAX(CASE WHEN o.concept = 'Epilepsy complications' AND o.value_coded = 'Status epilepticus' THEN o.obs_group_id END) as obs_group_epilepticus_complication,
    MAX(CASE WHEN o.concept = 'Date of exposure' THEN o.value_date END) as traditional_medicine_date_of_exposure,
    MAX(CASE WHEN o.concept = 'Exposure' AND o.value_coded = 'Traditional medicine' THEN o.value_coded END) as traditional_medicine_exposure,
    MAX(CASE WHEN o.concept = 'Vdrl' THEN o.value_coded END) as vdrl,
    MAX(CASE WHEN o.concept = 'Year of onset' THEN o.value_numeric END) as year_of_onset
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('EPILEPSY_INITIAL')
GROUP BY e.patient_id, e.encounter_date, e.location;