-- Derivation script for mw_epilepsy_followup
-- Generated from Pentaho transform: import-into-mw-epilepsy-followup.ktr

drop table if exists mw_epilepsy_followup;
create table mw_epilepsy_followup (
  epilepsy_followup_visit_id 			int not null auto_increment,
  patient_id 					int not null,
  visit_date 					date not null,
  location 					varchar(255) not null,
  height 					int,
  weight 					int,
  bmi 						varchar(255),
  seizure_since_last_visit 			varchar(255),
  number_of_seizures 				int,
  any_triggers 				varchar(255),
  alcohol_trigger 				varchar(255),
  fever_trigger 				varchar(255),
  sound_light_and_touch_trigger 		varchar(255),
  emotional_stress_anger_boredom_trigger 	varchar(255),
  sleep_deprivation_and_overtired_trigger 	varchar(255),
  missed_medication_trigger 			varchar(255),
  menstruation_trigger 			varchar(255),
  silent_makers 				varchar(255),
  hospitalized_since_last_visit 		varchar(255),
  pregnant 					varchar(255),
  family_planning 				varchar(255),
  med_carbamazepine 				varchar(255),
  med_carbamazepine_dose		int,
  med_carbamazepine_dosing_unit varchar(50),
  med_carbamazepine_route		varchar(50),
  med_carbamazepine_frequency		varchar(50),
  med_carbamazepine_duration   int,
  med_carbamazepine_duration_units  varchar(50),
  med_Phenobarbital 				varchar(255),
  med_Phenobarbital_dose		int,
  med_Phenobarbital_dosing_unit varchar(50),
  med_Phenobarbital_route		varchar(50),
  med_Phenobarbital_frequency		varchar(50),
  med_Phenobarbital_duration   int,
  med_Phenobarbital_duration_units  varchar(50),
  med_Phenytoin 				varchar(255),
  med_Phenytoin_dose		int,
  med_Phenytoin_dosing_unit varchar(50),
  med_Phenytoin_route		varchar(50),
  med_Phenytoin_frequency		varchar(50),
  med_Phenytoin_duration   int,
  med_Phenytoin_duration_units  varchar(50),
  med_Sodium_Valproate 			varchar(255),
  med_Sodium_Valproate_dose		int,
  med_Sodium_Valproate_dosing_unit varchar(50),
  med_Sodium_Valproate_route		varchar(50),
  med_Sodium_Valproate_frequency		varchar(50),
  med_Sodium_Valproate_duration   int,
  med_Sodium_Valproate_duration_units  varchar(50),
  med_other 					varchar(255),
  comments 					varchar(2000) ,
  next_appointment_date 			date,
  primary key (epilepsy_followup_visit_id)
);

insert into mw_epilepsy_followup
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_carbamazepine_frequency,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_Phenobarbital_frequency,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_sodium_valproate_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_sodium_valproate_route,
    max(case when o.concept = 'Any seizure triggers present' then o.value_coded end) as any_triggers,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_carbamazepine_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_carbamazepine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_carbamazepine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_carbamazepine_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_carbamazepine_route,
    max(case when o.concept = 'Family planning' then o.value_coded end) as family_planning,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = 'Patient hospitalized since last visit' then o.value_coded end) as hospitalized_since_last_visit,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Carbamazepine' then o.value_coded end) as med_carbamazepine,
    max(case when o.concept = 'NUMBER OF SEIZURES' then o.value_numeric end) as number_of_seizures,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_Phenobarbital_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_Phenobarbital_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_Phenobarbital_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_Phenobarbital_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_Phenobarbital_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_Phenytoin_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_Phenytoin_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_Phenytoin_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_Phenytoin_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_Phenytoin_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_Phenytoin_route,
    max(case when o.concept = 'Is patient pregnant?' then o.value_coded end) as pregnant,
    max(case when o.concept = 'Symptoms during seizure' then o.value_coded end) as silent_makers,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_sodium_valproate_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_sodium_valproate_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_sodium_valproate_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_sodium_valproate_duration_units,
    max(case when o.concept = 'Epilepsy trigger' and o.value_coded = 'Alcohol trigger' then o.value_coded end) as alcohol_trigger,
    max(case when o.concept = 'Body Mass Index, coded' then o.value_coded end) as bmi,
    max(case when o.concept = 'Epilepsy trigger' and o.value_coded = 'Emotional stress, anger, boredom' then o.value_coded end) as emotional_stress_anger_boredom_trigger,
    max(case when o.concept = 'Epilepsy trigger' and o.value_coded = 'Fever trigger' then o.value_coded end) as fever_trigger,
    max(case when o.concept = 'Epilepsy trigger' and o.value_coded = 'Menstruation trigger' then o.value_coded end) as menstruation_trigger,
    max(case when o.concept = 'Epilepsy trigger' and o.value_coded = 'Missed medication trigger' then o.value_coded end) as missed_medication_trigger,
    max(case when o.concept = 'Any seizure occurred since last visit' then o.value_coded end) as seizure_since_last_visit,
    max(case when o.concept = 'Epilepsy trigger' and o.value_coded = 'Sleep deprivation and overtired' then o.value_coded end) as sleep_deprivation_and_overtired_trigger,
    max(case when o.concept = 'Epilepsy trigger' and o.value_coded = 'Sound, light, and touch' then o.value_coded end) as sound_light_and_touch_trigger,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight,
    max(case when o.concept = 'Clinical impression comments' then o.value_text end) as comments,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Phenobarbital' then o.value_coded end) as med_phenobarbital,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Phenytoin' then o.value_coded end) as med_phenytoin,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Sodium valproate' then o.value_coded end) as med_sodium_valproate,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Other' then o.value_coded end) as med_other,
    max(case when o.concept = 'Appointment date' then o.value_date end) as next_appointment_date
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('EPILEPSY_FOLLOWUP')
group by e.patient_id, e.encounter_date, e.location;