-- Derivation script for mw_epilepsy_followup
-- Generated from Pentaho transform: import-into-mw-epilepsy-followup.ktr

DROP TABLE IF EXISTS mw_epilepsy_followup;
CREATE TABLE mw_epilepsy_followup (
  epilepsy_followup_visit_id 			int NOT NULL AUTO_INCREMENT,
  patient_id 					int NOT NULL,
  visit_date 					date NOT NULL,
  location 					varchar(255) NOT NULL,
  height 					int,
  weight 					int,
  bmi 						varchar(255),
  seizure_since_last_visit 			varchar(255),
  number_of_seizures 				int,
  any_triggers 				varchar(255),
  alcohol_trigger 				varchar(255),
  fever_trigger 				varchar(255),
  sound_light_and_touch_trigger 		varchar(255),
  emotional_stress_anger_boredom_trigger 	varchar(255),
  sleep_deprivation_and_overtired_trigger 	varchar(255),
  missed_medication_trigger 			varchar(255),
  menstruation_trigger 			varchar(255),
  silent_makers 				varchar(255),
  hospitalized_since_last_visit 		varchar(255),
  pregnant 					varchar(255),
  family_planning 				varchar(255),
  med_carbamazepine 				varchar(255),
  med_carbamazepine_dose		INT,
  med_carbamazepine_dosing_unit VARCHAR(50),
  med_carbamazepine_route		VARCHAR(50),
  med_carbamazepine_frequency		VARCHAR(50),
  med_carbamazepine_duration   INT,
  med_carbamazepine_duration_units  VARCHAR(50),
  med_Phenobarbital 				varchar(255),
  med_Phenobarbital_dose		INT,
  med_Phenobarbital_dosing_unit VARCHAR(50),
  med_Phenobarbital_route		VARCHAR(50),
  med_Phenobarbital_frequency		VARCHAR(50),
  med_Phenobarbital_duration   INT,
  med_Phenobarbital_duration_units  VARCHAR(50),
  med_Phenytoin 				varchar(255),
  med_Phenytoin_dose		INT,
  med_Phenytoin_dosing_unit VARCHAR(50),
  med_Phenytoin_route		VARCHAR(50),
  med_Phenytoin_frequency		VARCHAR(50),
  med_Phenytoin_duration   INT,
  med_Phenytoin_duration_units  VARCHAR(50),
  med_Sodium_Valproate 			varchar(255),
  med_Sodium_Valproate_dose		INT,
  med_Sodium_Valproate_dosing_unit VARCHAR(50),
  med_Sodium_Valproate_route		VARCHAR(50),
  med_Sodium_Valproate_frequency		VARCHAR(50),
  med_Sodium_Valproate_duration   INT,
  med_Sodium_Valproate_duration_units  VARCHAR(50),
  med_other 					varchar(255),
  comments 					varchar(2000) ,
  next_appointment_date 			date,
  PRIMARY KEY (epilepsy_followup_visit_id)
);

INSERT INTO mw_epilepsy_followup
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_carbamazepine_frequency,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_Phenobarbital_frequency,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_sodium_valproate_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_sodium_valproate_route,
    MAX(CASE WHEN o.concept = 'Any seizure triggers present' THEN o.value_coded END) as any_triggers,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_carbamazepine_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_carbamazepine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_carbamazepine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_carbamazepine_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_carbamazepine_route,
    MAX(CASE WHEN o.concept = 'Family planning' THEN o.value_coded END) as family_planning,
    MAX(CASE WHEN o.concept = 'Height (cm)' THEN o.value_numeric END) as height,
    MAX(CASE WHEN o.concept = 'Patient hospitalized since last visit' THEN o.value_coded END) as hospitalized_since_last_visit,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Carbamazepine' THEN o.value_coded END) as med_carbamazepine,
    MAX(CASE WHEN o.concept = 'NUMBER OF SEIZURES' THEN o.value_numeric END) as number_of_seizures,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_Phenobarbital_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_Phenobarbital_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_Phenobarbital_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_Phenobarbital_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_Phenobarbital_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_Phenytoin_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_Phenytoin_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_Phenytoin_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_Phenytoin_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_Phenytoin_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_Phenytoin_route,
    MAX(CASE WHEN o.concept = 'Is patient pregnant?' THEN o.value_coded END) as pregnant,
    MAX(CASE WHEN o.concept = 'Symptoms during seizure' THEN o.value_coded END) as silent_makers,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_sodium_valproate_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_sodium_valproate_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_sodium_valproate_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_sodium_valproate_duration_units,
    MAX(CASE WHEN o.concept = 'Epilepsy trigger' AND o.value_coded = 'Alcohol trigger' THEN o.value_coded END) as alcohol_trigger,
    MAX(CASE WHEN o.concept = 'Body Mass Index, coded' THEN o.value_coded END) as bmi,
    MAX(CASE WHEN o.concept = 'Epilepsy trigger' AND o.value_coded = 'Emotional stress, anger, boredom' THEN o.value_coded END) as emotional_stress_anger_boredom_trigger,
    MAX(CASE WHEN o.concept = 'Epilepsy trigger' AND o.value_coded = 'Fever trigger' THEN o.value_coded END) as fever_trigger,
    MAX(CASE WHEN o.concept = 'Epilepsy trigger' AND o.value_coded = 'Menstruation trigger' THEN o.value_coded END) as menstruation_trigger,
    MAX(CASE WHEN o.concept = 'Epilepsy trigger' AND o.value_coded = 'Missed medication trigger' THEN o.value_coded END) as missed_medication_trigger,
    MAX(CASE WHEN o.concept = 'Any seizure occurred since last visit' THEN o.value_coded END) as seizure_since_last_visit,
    MAX(CASE WHEN o.concept = 'Epilepsy trigger' AND o.value_coded = 'Sleep deprivation and overtired' THEN o.value_coded END) as sleep_deprivation_and_overtired_trigger,
    MAX(CASE WHEN o.concept = 'Epilepsy trigger' AND o.value_coded = 'Sound, light, and touch' THEN o.value_coded END) as sound_light_and_touch_trigger,
    MAX(CASE WHEN o.concept = 'Weight (kg)' THEN o.value_numeric END) as weight,
    MAX(CASE WHEN o.concept = 'Clinical impression comments' THEN o.value_text END) as comments,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Phenobarbital' THEN o.value_coded END) as med_phenobarbital,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Phenytoin' THEN o.value_coded END) as med_phenytoin,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Sodium valproate' THEN o.value_coded END) as med_sodium_valproate,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Other' THEN o.value_coded END) as med_other,
    MAX(CASE WHEN o.concept = 'Appointment date' THEN o.value_date END) as next_appointment_date
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('EPILEPSY_FOLLOWUP')
GROUP BY e.patient_id, e.encounter_date, e.location;