-- Derivation script for mw_mental_health_initial
-- Generated from Pentaho transform: import-into-mw-mental-health-initial.ktr

DROP TABLE IF EXISTS mw_mental_health_initial;
CREATE TABLE mw_mental_health_initial (
 mental_health_initial_visit_id 			INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 patient_id 						int NOT NULL,
 visit_date 						date DEFAULT NULL,
 location						varchar(255) DEFAULT NULL,
 
 diagnosis_bipolar_mood_disorder			varchar(255) DEFAULT NULL,
 diagnosis_date_bipolar_mood_disorder			date DEFAULT NULL,
 diagnosis_stress_reactive_adjustment_disorder	varchar(255) DEFAULT NULL,
 diagnosis_date_stress_reactive_adjustment_disorder	date DEFAULT NULL,
 diagnosis_dissociative_mood_disorder			varchar(255) DEFAULT NULL,
 diagnosis_date_dissociative_mood_disorder		date DEFAULT NULL,
 diagnosis_hyperkinetic_disorder			varchar(255) DEFAULT NULL,
 diagnosis_date_hyperkinetic_disorder			date DEFAULT NULL,
 diagnosis_puerperal_mental_disorder			varchar(255) DEFAULT NULL,
 diagnosis_date_puerperal_mental_disorder		date DEFAULT NULL,
 diagnosis_schizophrenia 				varchar(255) DEFAULT NULL,
 diagnosis_date_schizophrenia 			date DEFAULT NULL,
 diagnosis_mood_affective_disorder_manic 		varchar(255) DEFAULT NULL,
 diagnosis_date_mood_affective_disorder_manic 	date DEFAULT NULL,
 diagnosis_mood_affective_disorder_depression 	varchar(255) DEFAULT NULL,
 diagnosis_date_mood_affective_disorder_depression 	date DEFAULT NULL,
 diagnosis_acute_and_transient_psychotic 		varchar(255) DEFAULT NULL,
 diagnosis_date_acute_and_transient_psychotic 	date DEFAULT NULL,
 
 diagnosis_schizoaffective_disorder 		varchar(255) DEFAULT NULL,
 diagnosis_date_schizoaffective_disorder 	date DEFAULT NULL,
 diagnosis_anxiety_disorder 			varchar(255) DEFAULT NULL,
 diagnosis_date_anxiety_disorder 		date DEFAULT NULL,
 diagnosis_organic_mental_disorder_acute 	varchar(255) DEFAULT NULL,
 diagnosis_date_organic_mental_disorder_acute date DEFAULT NULL,
 diagnosis_organic_mental_disorder_chronic	 varchar(255) DEFAULT NULL,
 diagnosis_date_organic_mental_disorder_chronic date DEFAULT NULL,
 diagnosis_drug_use_mental_disorder 		varchar(255) DEFAULT NULL,
 diagnosis_date_drug_use_mental_disorder 	date DEFAULT NULL,
 diagnosis_alcohol_use_mental_disorder 	varchar(255) DEFAULT NULL,
 diagnosis_date_alcohol_use_mental_disorder	date DEFAULT NULL,
 diagnosis_other_1 				varchar(255) DEFAULT NULL,
 diagnosis_date_other_1 			date DEFAULT NULL,
 diagnosis_other_2 				varchar(255) DEFAULT NULL,
 diagnosis_date_other_2 			date DEFAULT NULL,
 diagnosis_other_3 				varchar(255) DEFAULT NULL,
 diagnosis_date_other_3 			date DEFAULT NULL,
 diagnosis_somatoform_disorder			varchar(255) DEFAULT NULL,
 diagnosis_date_somatoform_disorder			date DEFAULT NULL,
 diagnosis_personality_disorder			varchar(255) DEFAULT NULL,
 diagnosis_date_personality_disorder			date DEFAULT NULL,
 diagnosis_mental_retardation_disorder		varchar(255) DEFAULT NULL,
 diagnosis_date_mental_retardation_disorder		date DEFAULT NULL,
 diagnosis_psych_development_disorder			varchar(255) DEFAULT NULL,
 diagnosis_date_psych_development_disorder		date DEFAULT NULL,
 hiv_status 					varchar(255) DEFAULT NULL,
 hiv_test_date 				date DEFAULT NULL,
 art_start_date 				date DEFAULT NULL,
 tb_status 					varchar(255) DEFAULT NULL,
 tb_year 					decimal(10,2) DEFAULT NULL,
 hallucinations 				varchar(255) DEFAULT NULL,
 hallucinations_date 				date DEFAULT NULL,
 delusions 					varchar(255) DEFAULT NULL,
 delusions_date 				date DEFAULT NULL,
 disorganised_or_disruptive_behaviour 	varchar(255) DEFAULT NULL,
 disorganised_or_disruptive_behaviour_date 	date DEFAULT NULL,
 disorganised_speech 				varchar(255) DEFAULT NULL,
 disorganised_speech_date 			date DEFAULT NULL,
 depressive_symptoms 				varchar(255) DEFAULT NULL,
 depressive_symptoms_date 			date DEFAULT NULL,
 other_complaints 				varchar(255) DEFAULT NULL,
 other_complaints_date 			date DEFAULT NULL,
 alcohol_exposure 				varchar(255) DEFAULT NULL,
 alcohol_years_exposed 			decimal(10,2) DEFAULT NULL,
 alcohol_date_last_used 			date DEFAULT NULL,
 marijuana_exposure 				varchar(255) DEFAULT NULL,
 marijuana_years_exposed			decimal(10,2) DEFAULT NULL,
 marijuana_date_last_used 			date DEFAULT NULL,
 other_drugs_exposure 				varchar(255) DEFAULT NULL,
 other_drugs_years_exposed 			decimal(10,2) DEFAULT NULL,
 other_drugs_date_last_used 			date DEFAULT NULL,
 traditional_med_exposure 			varchar(255) DEFAULT NULL,
 traditional_med_years_exposed 		decimal(10,2) DEFAULT NULL,
 traditional_med_date_last_used 		date DEFAULT NULL,
 epilepsy_family_history 			varchar(255) DEFAULT NULL,
 mental_family_history 			varchar(255) DEFAULT NULL,
 behavior_problems_family_history 		varchar(255) DEFAULT NULL
) ;

INSERT INTO mw_mental_health_initial
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_mood_affective_disorder_depression,
    MAX(CASE WHEN o.concept = 'Date of exposure' THEN o.value_date END) as alcohol_date_last_used,
    MAX(CASE WHEN o.concept = 'History of alcohol use' THEN o.value_coded END) as alcohol_exposure,
    MAX(CASE WHEN o.concept = 'Duration in years' THEN o.value_numeric END) as alcohol_years_exposed,
    MAX(CASE WHEN o.concept = 'Family history of behavioral problems' THEN o.value_coded END) as behavior_problems_family_history,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as delusions_date,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint' AND o.value_coded = 'Depressive Disorder' THEN o.value_coded END) as depressive_symptoms,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as depressive_symptoms_date,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Schizophrenia' THEN o.value_coded END) as diagnosis_schizophrenia,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_stress_reactive_adjustment_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Acute Psychotic disorder' THEN o.value_coded END) as diagnosis_acute_and_transient_psychotic,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Anxiety disorder' THEN o.value_coded END) as diagnosis_anxiety_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Mood Affective Disorder (Bipolar)' THEN o.value_coded END) as diagnosis_bipolar_mood_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_schizophrenia,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_acute_and_transient_psychotic,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_anxiety_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_bipolar_mood_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_dissociative_mood_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_drug_use_mental_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_hyperkinetic_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_mood_affective_disorder_manic,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_organic_mental_disorder_acute,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_organic_mental_disorder_chronic,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_puerperal_mental_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_schizoaffective_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Dissociative Conversion Disorder' THEN o.value_coded END) as diagnosis_dissociative_mood_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Drug-induced mental and behavior disorder' THEN o.value_coded END) as diagnosis_drug_use_mental_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Hyperkinetic Conductal Disorder (ADHD)' THEN o.value_coded END) as diagnosis_hyperkinetic_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Depression' THEN o.value_coded END) as diagnosis_mood_affective_disorder_depression,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Bipolar Affective Disorder, Manic' THEN o.value_coded END) as diagnosis_mood_affective_disorder_manic,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Organic mental disorder (acute)' THEN o.value_coded END) as diagnosis_organic_mental_disorder_acute,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Organic mental disorder (chronic)' THEN o.value_coded END) as diagnosis_organic_mental_disorder_chronic,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Puerperal Mental Disorder' THEN o.value_coded END) as diagnosis_puerperal_mental_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Schizoaffective Disorder' THEN o.value_coded END) as diagnosis_schizoaffective_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Stress Reaction Adjustment Disorder' THEN o.value_coded END) as diagnosis_stress_reactive_adjustment_disorder,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint' AND o.value_coded = 'Disruptive Behavior Disorder' THEN o.value_coded END) as disorganised_or_disruptive_behaviour,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint' AND o.value_coded = 'Abnormal speech' THEN o.value_coded END) as disorganised_speech,
    MAX(CASE WHEN o.concept = 'Family history of epilepsy' THEN o.value_coded END) as epilepsy_family_history,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as hallucinations_date,
    MAX(CASE WHEN o.concept = 'Date of exposure' THEN o.value_date END) as marijuana_date_last_used,
    MAX(CASE WHEN o.concept = 'History of exposure' THEN o.value_coded END) as marijuana_exposure,
    MAX(CASE WHEN o.concept = 'Duration in years' THEN o.value_numeric END) as marijuana_years_exposed,
    MAX(CASE WHEN o.concept = 'Family history of mental illness' THEN o.value_coded END) as mental_family_history,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint' AND o.value_coded = 'Other non-coded' THEN o.value_coded END) as other_complaints,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as other_complaints_date,
    MAX(CASE WHEN o.concept = 'Date of exposure' THEN o.value_date END) as other_drugs_date_last_used,
    MAX(CASE WHEN o.concept = 'History of exposure' THEN o.value_coded END) as other_drugs_exposure,
    MAX(CASE WHEN o.concept = 'Duration in years' THEN o.value_numeric END) as other_drugs_years_exposed,
    MAX(CASE WHEN o.concept = 'Date of exposure' THEN o.value_date END) as traditional_med_date_last_used,
    MAX(CASE WHEN o.concept = 'History of exposure' THEN o.value_coded END) as traditional_med_exposure,
    MAX(CASE WHEN o.concept = 'Duration in years' THEN o.value_numeric END) as traditional_med_years_exposed,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' THEN o.value_coded END) as diagnosis_other_3,
    MAX(CASE WHEN o.concept = 'Date antiretrovirals started' THEN o.value_date END) as art_start_date,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint' AND o.value_coded = 'Delusions' THEN o.value_coded END) as delusions,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Alcohol-induced mental and behavior disorder' THEN o.value_coded END) as diagnosis_alcohol_use_mental_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_alcohol_use_mental_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_mental_retardation_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_other_1,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_other_2,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_other_3,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_personality_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_psych_development_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as diagnosis_date_somatoform_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Mental retardation' THEN o.value_coded END) as diagnosis_mental_retardation_disorder,
    MAX(CASE WHEN o.concept = 'Other non-coded (text)' THEN o.value_text END) as diagnosis_other_1,
    MAX(CASE WHEN o.concept = 'Other non-coded (text)' THEN o.value_text END) as diagnosis_other_2,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Personality Disorder' THEN o.value_coded END) as diagnosis_personality_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Psychological development disorder' THEN o.value_coded END) as diagnosis_psych_development_disorder,
    MAX(CASE WHEN o.concept = 'Chronic care diagnosis' AND o.value_coded = 'Somatoform Disorder' THEN o.value_coded END) as diagnosis_somatoform_disorder,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as disorganised_or_disruptive_behaviour_date,
    MAX(CASE WHEN o.concept = 'Diagnosis date' THEN o.value_date END) as disorganised_speech_date,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint' AND o.value_coded = 'Hallucinations' THEN o.value_coded END) as hallucinations,
    MAX(CASE WHEN o.concept = 'HIV status' THEN o.value_coded END) as hiv_status,
    MAX(CASE WHEN o.concept = 'HIV test date' THEN o.value_date END) as hiv_test_date,
    MAX(CASE WHEN o.concept = 'TB status' THEN o.value_coded END) as tb_status,
    MAX(CASE WHEN o.concept = 'Year of Tuberculosis diagnosis' THEN o.value_numeric END) as tb_year
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('MENTAL_HEALTH_INITIAL')
GROUP BY e.patient_id, e.encounter_date, e.location;