-- Derivation script for mw_mental_health_followup
-- Generated from Pentaho transform: import-into-mw-mental-health-followup.ktr

DROP TABLE IF EXISTS mw_mental_health_followup;
CREATE TABLE mw_mental_health_followup (
  mental_health_followup_visit_id 	int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  height 				int DEFAULT NULL,
  weight 				int DEFAULT NULL,
  phq_nine_score 		        int DEFAULT NULL,
  mse_depressed_mood 			varchar(255) DEFAULT NULL,
  mse_elevated_mood 			varchar(255) DEFAULT NULL,
  mse_disruptive_behaviour 		varchar(255) DEFAULT NULL,
  mse_disorganized_speech 		varchar(255) DEFAULT NULL,
  mse_delusions 			varchar(255) DEFAULT NULL,
  mse_hallucinations 			varchar(255) DEFAULT NULL,
  mse_Lack_of_insight 			varchar(255) DEFAULT NULL,
  mse_other 				varchar(255) DEFAULT NULL,
  patient_stable 			varchar(255) DEFAULT NULL,
  able_to_do_daily_activities  	varchar(255) DEFAULT NULL,
  current_use_marijuana 		varchar(255) DEFAULT NULL,
  current_use_alcohol 			varchar(255) DEFAULT NULL,
  current_use_other 			varchar(255) DEFAULT NULL,
  pregnant 				varchar(255) DEFAULT NULL,
  on_family_planning 			varchar(255) DEFAULT NULL,
  suicide_risk 			varchar(255) DEFAULT NULL,
  medications_side_effects 		varchar(255) DEFAULT NULL,
  hospitalized_since_last_visit 	varchar(255) DEFAULT NULL,
  counselling_provided			varchar(255) DEFAULT NULL,
  med_chloropromazine 			varchar(255) DEFAULT NULL,
  med_chloropromazine_dose		INT,
  med_chloropromazine_dosing_unit VARCHAR(50),
  med_chloropromazine_route		VARCHAR(50),
  med_chloropromazine_frequency		VARCHAR(50),
  med_chloropromazine_duration   INT,
  med_chloropromazine_duration_units  VARCHAR(50),
  med_haloperidol 			varchar(255) DEFAULT NULL,
  med_haloperidolp_dose		INT,
  med_haloperidol_dosing_unit VARCHAR(50),
  med_haloperidol_route		VARCHAR(50),
  med_haloperidol_frequency		VARCHAR(50),
  med_haloperidol_duration   INT,
  med_haloperidol_duration_units  VARCHAR(50),
  med_risperidone			varchar(255) DEFAULT NULL,
  med_risperidone_dose		INT,
  med_risperidone_dosing_unit VARCHAR(50),
  med_risperidone_route		VARCHAR(50),
  med_risperidone_frequency		VARCHAR(50),
  med_risperidone_duration   INT,
  med_risperidone_duration_units  VARCHAR(50),
  med_fluphenazine 			varchar(255) DEFAULT NULL,
  med_fluphenazine_dose		INT,
  med_fluphenazine_dosing_unit VARCHAR(50),
  med_fluphenazine_route		VARCHAR(50),
   med_fluphenazine_frequency		VARCHAR(50),
   med_fluphenazine_duration   INT,
   med_fluphenazine_duration_units  VARCHAR(50),
  med_carbamazepine 			varchar(255) DEFAULT NULL,
  med_carbamazepine_dose		INT,
  med_carbamazepine_dosing_unit VARCHAR(50),
  med_carbamazepine_route		VARCHAR(50),
  med_carbamazepine_frequency		VARCHAR(50),
  med_carbamazepine_duration   INT,
  med_carbamazepine_duration_units  VARCHAR(50),
  med_sodium_valproate 		varchar(255) DEFAULT NULL,
  med_sodium_valproate_dose		INT,
  med_sodium_valproate_dosing_unit VARCHAR(50),
  med_sodium_valproate_route		VARCHAR(50),
  med_sodium_valproate_frequency		VARCHAR(50),
  med_sodium_valproate_duration   INT,
  med_sodium_valproate_duration_units  VARCHAR(50),
  med_fluoxetine 			varchar(255) DEFAULT NULL,
  med_fluoxetine_dose		INT,
  med_fluoxetine_dosing_unit VARCHAR(50),
  med_fluoxetine_route		VARCHAR(50),
  med_fluoxetine_frequency		VARCHAR(50),
  med_fluoxetine_duration   INT,
  med_fluoxetine_duration_units  VARCHAR(50),
  med_olanzapine 			varchar(255) DEFAULT NULL,
  med_olanzapine_dose		INT,
  med_olanzapine_dosing_unit VARCHAR(50),
  med_olanzapine_route		VARCHAR(50),
  med_olanzapine_frequency		VARCHAR(50),
  med_olanzapine_duration   INT,
  med_olanzapine_duration_units  VARCHAR(50),
  med_clozapine 			varchar(255) DEFAULT NULL,
  med_clozapine_dose		INT,
  med_clozapine_dosing_unit VARCHAR(50),
  med_clozapine_route		VARCHAR(50),
  med_clozapine_frequency		VARCHAR(50),
  med_clozapine_duration   INT,
  med_clozapine_duration_units  VARCHAR(50),
  med_trifluoperazine 			varchar(255) DEFAULT NULL,
  med_trifluoperazine_dose		INT,
  med_trifluoperazine_dosing_unit VARCHAR(50),
  med_trifluoperazine_route		VARCHAR(50),
  med_trifluoperazine_frequency		VARCHAR(50),
  med_trifluoperazine_duration   INT,
  med_trifluoperazine_duration_units  VARCHAR(50),
  med_clopixol 			varchar(255) DEFAULT NULL,
  med_clopixol_dose		INT,
  med_clopixol_dosing_unit VARCHAR(50),
  med_clopixol_route		VARCHAR(50),
  med_clopixol_frequency		VARCHAR(50),
  med_clopixol_duration   INT,
  med_clopixol_duration_units  VARCHAR(50),
  med_amitriptyline                    varchar(255) DEFAULT NULL,
  med_amitriptyline_dose		INT,
  med_amitriptyline_dosing_unit VARCHAR(50),
  med_amitriptyline_route		VARCHAR(50),
  med_amitriptyline_frequency		VARCHAR(50),
  med_amitriptyline_duration   INT,
  med_amitriptyline_duration_units  VARCHAR(50),
  med_other 				varchar(255) DEFAULT NULL,
  comments 				varchar(2000) DEFAULT NULL,
  next_appointment_date 		date DEFAULT NULL,
  PRIMARY KEY (mental_health_followup_visit_id)
) ;

INSERT INTO mw_mental_health_followup
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_carbamazepine_frequency,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_clopixol_frequency,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_clozapine_frequency,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_fluphenazine_frequency,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_haloperidol_frequency,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_sodium_valproate_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_sodium_valproate_route,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_trifluoperazine_frequency,
    MAX(CASE WHEN o.concept = 'Able to perform daily activities' THEN o.value_coded END) as able_to_do_daily_activities,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_amitriptyline_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_amitriptyline_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_amitriptyline_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_amitriptyline_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_amitriptyline_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_amitriptyline_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_carbamazepine_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_carbamazepine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_carbamazepine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_carbamazepine_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_carbamazepine_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_chloropromazine_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_chloropromazine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_chloropromazine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_chloropromazine_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_chloropromazine_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_chloropromazine_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_clopixol_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_clopixol_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_clopixol_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_clopixol_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_clopixol_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_clozapine_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_clozapine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_clozapine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_clozapine_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_clozapine_route,
    MAX(CASE WHEN o.concept = 'History of alcohol use' THEN o.value_coded END) as current_use_alcohol,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_fluoxetine_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_fluoxetine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_fluoxetine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_fluoxetine_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_fluoxetine_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_fluoxetine_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_fluphenazine_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_fluphenazine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_fluphenazine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_fluphenazine_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_fluphenazine_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_haloperidolp_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_haloperidol_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_haloperidol_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_haloperidol_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_haloperidol_route,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint absent' AND o.value_coded = 'Depressive Disorder' THEN o.value_coded END) as mse_depressed_mood,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint absent' AND o.value_coded = 'Abnormal speech' THEN o.value_coded END) as mse_disorganized_speech,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint absent' AND o.value_coded = 'Disruptive Behavior Disorder' THEN o.value_coded END) as mse_disruptive_behaviour,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint absent' AND o.value_coded = 'Hypomania' THEN o.value_coded END) as mse_elevated_mood,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint absent' AND o.value_coded = 'Lack of insight' THEN o.value_coded END) as mse_lack_of_insight,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint absent' AND o.value_coded = 'Delusions' THEN o.value_coded END) as mse_delusions,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint absent' AND o.value_coded = 'Hallucinations' THEN o.value_coded END) as mse_hallucinations,
    MAX(CASE WHEN o.concept = 'Mental health chief complaint absent' AND o.value_coded = 'Other non-coded' THEN o.value_coded END) as mse_other,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_olanzapine_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_olanzapine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_olanzapine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_olanzapine_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_olanzapine_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_olanzapine_route,
    MAX(CASE WHEN o.concept = 'Family planning' THEN o.value_coded END) as on_family_planning,
    MAX(CASE WHEN o.concept = 'PHQ 9 Score' THEN o.value_numeric END) as phq_nine_score,
    MAX(CASE WHEN o.concept = 'Stable' THEN o.value_coded END) as patient_stable,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_risperidone_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_risperidone_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_risperidone_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_risperidone_duration_units,
    MAX(CASE WHEN o.concept = 'Drug frequency coded' THEN o.value_coded END) as med_risperidone_frequency,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_risperidone_route,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_sodium_valproate_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_sodium_valproate_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_sodium_valproate_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_sodium_valproate_duration_units,
    MAX(CASE WHEN o.concept = 'Suicide risk' THEN o.value_coded END) as suicide_risk,
    MAX(CASE WHEN o.concept = 'Quantity of medication prescribed per dose' THEN o.value_numeric END) as med_trifluoperazine_dose,
    MAX(CASE WHEN o.concept = 'Dosing unit' THEN o.value_coded END) as med_trifluoperazine_dosing_unit,
    MAX(CASE WHEN o.concept = 'Medication duration' THEN o.value_numeric END) as med_trifluoperazine_duration,
    MAX(CASE WHEN o.concept = 'Time units' THEN o.value_coded END) as med_trifluoperazine_duration_units,
    MAX(CASE WHEN o.concept = 'Routes of administration (coded)' THEN o.value_coded END) as med_trifluoperazine_route,
    MAX(CASE WHEN o.concept = 'Clinical impression comments' THEN o.value_text END) as comments,
    MAX(CASE WHEN o.concept = 'Height (cm)' THEN o.value_numeric END) as height,
    MAX(CASE WHEN o.concept = 'Is patient pregnant?' THEN o.value_coded END) as pregnant,
    MAX(CASE WHEN o.concept = 'Weight (kg)' THEN o.value_numeric END) as weight,
    MAX(CASE WHEN o.concept = 'Group Counselling' THEN o.value_coded END) as counselling_provided,
    MAX(CASE WHEN o.concept = 'Hospitalized for mental health since last visit' THEN o.value_coded END) as hospitalized_since_last_visit,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Carbamazepine' THEN o.value_coded END) as med_carbamazepine,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Chlorpromazine' THEN o.value_coded END) as med_chloropromazine,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Clopixol' THEN o.value_coded END) as med_clopixol,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Clozapine' THEN o.value_coded END) as med_clozapine,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Fluoxetine' THEN o.value_coded END) as med_fluoxetine,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Fluphenazine' THEN o.value_coded END) as med_fluphenazine,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Haloperidol' THEN o.value_coded END) as med_haloperidol,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Olanzapine' THEN o.value_coded END) as med_olanzapine,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Risperidone' THEN o.value_coded END) as med_risperidone,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Sodium valproate' THEN o.value_coded END) as med_sodium_valproate,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Trifluoperazine' THEN o.value_coded END) as med_trifluoperazine,
    MAX(CASE WHEN o.concept = 'Current drugs used' AND o.value_coded = 'Amitriptyline' THEN o.value_coded END) as med_amitriptyline,
    MAX(CASE WHEN o.concept = '' AND o.value_coded = 'Other' THEN o.value_coded END) as med_other,
    MAX(CASE WHEN o.concept = 'Does patient have adverse effects' THEN o.value_coded END) as medications_side_effects,
    MAX(CASE WHEN o.concept = 'Appointment date' THEN o.value_date END) as next_appointment_date,
    MAX(CASE WHEN og.concept = 'Marijuana use construct' THEN o.value_coded END) as current_use_marijuana,
    MAX(CASE WHEN og.concept = 'Drug use construct' THEN o.value_coded END) as current_use_other
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
LEFT JOIN omrs_obs_group og ON og.obs_group_id = o.obs_group_id
WHERE e.encounter_type IN ('MENTAL_HEALTH_FOLLOWUP')
GROUP BY e.patient_id, e.encounter_date, e.location;
