-- Derivation script for mw_mental_health_followup
-- Generated from Pentaho transform: import-into-mw-mental-health-followup.ktr

drop table if exists mw_mental_health_followup;
create table mw_mental_health_followup (
  mental_health_followup_visit_id 	int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  height 				int default null,
  weight 				int default null,
  phq_nine_score 		        int default null,
  mse_depressed_mood 			varchar(255) default null,
  mse_elevated_mood 			varchar(255) default null,
  mse_disruptive_behaviour 		varchar(255) default null,
  mse_disorganized_speech 		varchar(255) default null,
  mse_delusions 			varchar(255) default null,
  mse_hallucinations 			varchar(255) default null,
  mse_Lack_of_insight 			varchar(255) default null,
  mse_other 				varchar(255) default null,
  patient_stable 			varchar(255) default null,
  able_to_do_daily_activities  	varchar(255) default null,
  current_use_marijuana 		varchar(255) default null,
  current_use_alcohol 			varchar(255) default null,
  current_use_other 			varchar(255) default null,
  pregnant 				varchar(255) default null,
  on_family_planning 			varchar(255) default null,
  suicide_risk 			varchar(255) default null,
  medications_side_effects 		varchar(255) default null,
  hospitalized_since_last_visit 	varchar(255) default null,
  counselling_provided			varchar(255) default null,
  med_chloropromazine 			varchar(255) default null,
  med_chloropromazine_dose		int,
  med_chloropromazine_dosing_unit varchar(50),
  med_chloropromazine_route		varchar(50),
  med_chloropromazine_frequency		varchar(50),
  med_chloropromazine_duration   int,
  med_chloropromazine_duration_units  varchar(50),
  med_haloperidol 			varchar(255) default null,
  med_haloperidolp_dose		int,
  med_haloperidol_dosing_unit varchar(50),
  med_haloperidol_route		varchar(50),
  med_haloperidol_frequency		varchar(50),
  med_haloperidol_duration   int,
  med_haloperidol_duration_units  varchar(50),
  med_risperidone			varchar(255) default null,
  med_risperidone_dose		int,
  med_risperidone_dosing_unit varchar(50),
  med_risperidone_route		varchar(50),
  med_risperidone_frequency		varchar(50),
  med_risperidone_duration   int,
  med_risperidone_duration_units  varchar(50),
  med_fluphenazine 			varchar(255) default null,
  med_fluphenazine_dose		int,
  med_fluphenazine_dosing_unit varchar(50),
  med_fluphenazine_route		varchar(50),
   med_fluphenazine_frequency		varchar(50),
   med_fluphenazine_duration   int,
   med_fluphenazine_duration_units  varchar(50),
  med_carbamazepine 			varchar(255) default null,
  med_carbamazepine_dose		int,
  med_carbamazepine_dosing_unit varchar(50),
  med_carbamazepine_route		varchar(50),
  med_carbamazepine_frequency		varchar(50),
  med_carbamazepine_duration   int,
  med_carbamazepine_duration_units  varchar(50),
  med_sodium_valproate 		varchar(255) default null,
  med_sodium_valproate_dose		int,
  med_sodium_valproate_dosing_unit varchar(50),
  med_sodium_valproate_route		varchar(50),
  med_sodium_valproate_frequency		varchar(50),
  med_sodium_valproate_duration   int,
  med_sodium_valproate_duration_units  varchar(50),
  med_fluoxetine 			varchar(255) default null,
  med_fluoxetine_dose		int,
  med_fluoxetine_dosing_unit varchar(50),
  med_fluoxetine_route		varchar(50),
  med_fluoxetine_frequency		varchar(50),
  med_fluoxetine_duration   int,
  med_fluoxetine_duration_units  varchar(50),
  med_olanzapine 			varchar(255) default null,
  med_olanzapine_dose		int,
  med_olanzapine_dosing_unit varchar(50),
  med_olanzapine_route		varchar(50),
  med_olanzapine_frequency		varchar(50),
  med_olanzapine_duration   int,
  med_olanzapine_duration_units  varchar(50),
  med_clozapine 			varchar(255) default null,
  med_clozapine_dose		int,
  med_clozapine_dosing_unit varchar(50),
  med_clozapine_route		varchar(50),
  med_clozapine_frequency		varchar(50),
  med_clozapine_duration   int,
  med_clozapine_duration_units  varchar(50),
  med_trifluoperazine 			varchar(255) default null,
  med_trifluoperazine_dose		int,
  med_trifluoperazine_dosing_unit varchar(50),
  med_trifluoperazine_route		varchar(50),
  med_trifluoperazine_frequency		varchar(50),
  med_trifluoperazine_duration   int,
  med_trifluoperazine_duration_units  varchar(50),
  med_clopixol 			varchar(255) default null,
  med_clopixol_dose		int,
  med_clopixol_dosing_unit varchar(50),
  med_clopixol_route		varchar(50),
  med_clopixol_frequency		varchar(50),
  med_clopixol_duration   int,
  med_clopixol_duration_units  varchar(50),
  med_amitriptyline                    varchar(255) default null,
  med_amitriptyline_dose		int,
  med_amitriptyline_dosing_unit varchar(50),
  med_amitriptyline_route		varchar(50),
  med_amitriptyline_frequency		varchar(50),
  med_amitriptyline_duration   int,
  med_amitriptyline_duration_units  varchar(50),
  med_other 				varchar(255) default null,
  comments 				varchar(2000) default null,
  next_appointment_date 		date default null,
  primary key (mental_health_followup_visit_id)
) ;

insert into mw_mental_health_followup
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_carbamazepine_frequency,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_clopixol_frequency,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_clozapine_frequency,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_fluphenazine_frequency,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_haloperidol_frequency,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_sodium_valproate_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_sodium_valproate_route,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_trifluoperazine_frequency,
    max(case when o.concept = 'Able to perform daily activities' then o.value_coded end) as able_to_do_daily_activities,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_amitriptyline_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_amitriptyline_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_amitriptyline_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_amitriptyline_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_amitriptyline_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_amitriptyline_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_carbamazepine_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_carbamazepine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_carbamazepine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_carbamazepine_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_carbamazepine_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_chloropromazine_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_chloropromazine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_chloropromazine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_chloropromazine_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_chloropromazine_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_chloropromazine_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_clopixol_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_clopixol_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_clopixol_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_clopixol_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_clopixol_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_clozapine_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_clozapine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_clozapine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_clozapine_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_clozapine_route,
    max(case when o.concept = 'History of alcohol use' then o.value_coded end) as current_use_alcohol,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_fluoxetine_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_fluoxetine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_fluoxetine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_fluoxetine_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_fluoxetine_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_fluoxetine_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_fluphenazine_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_fluphenazine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_fluphenazine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_fluphenazine_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_fluphenazine_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_haloperidolp_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_haloperidol_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_haloperidol_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_haloperidol_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_haloperidol_route,
    max(case when o.concept = 'Mental health chief complaint absent' and o.value_coded = 'Depressive Disorder' then o.value_coded end) as mse_depressed_mood,
    max(case when o.concept = 'Mental health chief complaint absent' and o.value_coded = 'Abnormal speech' then o.value_coded end) as mse_disorganized_speech,
    max(case when o.concept = 'Mental health chief complaint absent' and o.value_coded = 'Disruptive Behavior Disorder' then o.value_coded end) as mse_disruptive_behaviour,
    max(case when o.concept = 'Mental health chief complaint absent' and o.value_coded = 'Hypomania' then o.value_coded end) as mse_elevated_mood,
    max(case when o.concept = 'Mental health chief complaint absent' and o.value_coded = 'Lack of insight' then o.value_coded end) as mse_lack_of_insight,
    max(case when o.concept = 'Mental health chief complaint absent' and o.value_coded = 'Delusions' then o.value_coded end) as mse_delusions,
    max(case when o.concept = 'Mental health chief complaint absent' and o.value_coded = 'Hallucinations' then o.value_coded end) as mse_hallucinations,
    max(case when o.concept = 'Mental health chief complaint absent' and o.value_coded = 'Other non-coded' then o.value_coded end) as mse_other,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_olanzapine_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_olanzapine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_olanzapine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_olanzapine_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_olanzapine_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_olanzapine_route,
    max(case when o.concept = 'Family planning' then o.value_coded end) as on_family_planning,
    max(case when o.concept = 'PHQ 9 Score' then o.value_numeric end) as phq_nine_score,
    max(case when o.concept = 'Stable' then o.value_coded end) as patient_stable,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_risperidone_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_risperidone_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_risperidone_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_risperidone_duration_units,
    max(case when o.concept = 'Drug frequency coded' then o.value_coded end) as med_risperidone_frequency,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_risperidone_route,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_sodium_valproate_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_sodium_valproate_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_sodium_valproate_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_sodium_valproate_duration_units,
    max(case when o.concept = 'Suicide risk' then o.value_coded end) as suicide_risk,
    max(case when o.concept = 'Quantity of medication prescribed per dose' then o.value_numeric end) as med_trifluoperazine_dose,
    max(case when o.concept = 'Dosing unit' then o.value_coded end) as med_trifluoperazine_dosing_unit,
    max(case when o.concept = 'Medication duration' then o.value_numeric end) as med_trifluoperazine_duration,
    max(case when o.concept = 'Time units' then o.value_coded end) as med_trifluoperazine_duration_units,
    max(case when o.concept = 'Routes of administration (coded)' then o.value_coded end) as med_trifluoperazine_route,
    max(case when o.concept = 'Clinical impression comments' then o.value_text end) as comments,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = 'Is patient pregnant?' then o.value_coded end) as pregnant,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight,
    max(case when o.concept = 'Group Counselling' then o.value_coded end) as counselling_provided,
    max(case when o.concept = 'Hospitalized for mental health since last visit' then o.value_coded end) as hospitalized_since_last_visit,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Carbamazepine' then o.value_coded end) as med_carbamazepine,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Chlorpromazine' then o.value_coded end) as med_chloropromazine,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Clopixol' then o.value_coded end) as med_clopixol,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Clozapine' then o.value_coded end) as med_clozapine,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Fluoxetine' then o.value_coded end) as med_fluoxetine,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Fluphenazine' then o.value_coded end) as med_fluphenazine,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Haloperidol' then o.value_coded end) as med_haloperidol,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Olanzapine' then o.value_coded end) as med_olanzapine,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Risperidone' then o.value_coded end) as med_risperidone,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Sodium valproate' then o.value_coded end) as med_sodium_valproate,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Trifluoperazine' then o.value_coded end) as med_trifluoperazine,
    max(case when o.concept = 'Current drugs used' and o.value_coded = 'Amitriptyline' then o.value_coded end) as med_amitriptyline,
    max(case when o.concept = '' and o.value_coded = 'Other' then o.value_coded end) as med_other,
    max(case when o.concept = 'Does patient have adverse effects' then o.value_coded end) as medications_side_effects,
    max(case when o.concept = 'Appointment date' then o.value_date end) as next_appointment_date,
    max(case when og.concept = 'Marijuana use construct' then o.value_coded end) as current_use_marijuana,
    max(case when og.concept = 'Drug use construct' then o.value_coded end) as current_use_other
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
left join omrs_obs_group og on og.obs_group_id = o.obs_group_id
where e.encounter_type in ('MENTAL_HEALTH_FOLLOWUP')
group by e.patient_id, e.encounter_date, e.location;
