-- Derivation script for mw_mental_health_initial
-- Generated from Pentaho transform: import-into-mw-mental-health-initial.ktr

drop table if exists mw_mental_health_initial;
create table mw_mental_health_initial (
 mental_health_initial_visit_id 			int not null auto_increment primary key,
 patient_id 						int not null,
 visit_date 						date default null,
 location						varchar(255) default null,
 
 diagnosis_bipolar_mood_disorder			varchar(255) default null,
 diagnosis_date_bipolar_mood_disorder			date default null,
 diagnosis_stress_reactive_adjustment_disorder	varchar(255) default null,
 diagnosis_date_stress_reactive_adjustment_disorder	date default null,
 diagnosis_dissociative_mood_disorder			varchar(255) default null,
 diagnosis_date_dissociative_mood_disorder		date default null,
 diagnosis_hyperkinetic_disorder			varchar(255) default null,
 diagnosis_date_hyperkinetic_disorder			date default null,
 diagnosis_puerperal_mental_disorder			varchar(255) default null,
 diagnosis_date_puerperal_mental_disorder		date default null,
 diagnosis_schizophrenia 				varchar(255) default null,
 diagnosis_date_schizophrenia 			date default null,
 diagnosis_mood_affective_disorder_manic 		varchar(255) default null,
 diagnosis_date_mood_affective_disorder_manic 	date default null,
 diagnosis_mood_affective_disorder_depression 	varchar(255) default null,
 diagnosis_date_mood_affective_disorder_depression 	date default null,
 diagnosis_acute_and_transient_psychotic 		varchar(255) default null,
 diagnosis_date_acute_and_transient_psychotic 	date default null,
 
 diagnosis_schizoaffective_disorder 		varchar(255) default null,
 diagnosis_date_schizoaffective_disorder 	date default null,
 diagnosis_anxiety_disorder 			varchar(255) default null,
 diagnosis_date_anxiety_disorder 		date default null,
 diagnosis_organic_mental_disorder_acute 	varchar(255) default null,
 diagnosis_date_organic_mental_disorder_acute date default null,
 diagnosis_organic_mental_disorder_chronic	 varchar(255) default null,
 diagnosis_date_organic_mental_disorder_chronic date default null,
 diagnosis_drug_use_mental_disorder 		varchar(255) default null,
 diagnosis_date_drug_use_mental_disorder 	date default null,
 diagnosis_alcohol_use_mental_disorder 	varchar(255) default null,
 diagnosis_date_alcohol_use_mental_disorder	date default null,
 diagnosis_other_1 				varchar(255) default null,
 diagnosis_date_other_1 			date default null,
 diagnosis_other_2 				varchar(255) default null,
 diagnosis_date_other_2 			date default null,
 diagnosis_other_3 				varchar(255) default null,
 diagnosis_date_other_3 			date default null,
 diagnosis_somatoform_disorder			varchar(255) default null,
 diagnosis_date_somatoform_disorder			date default null,
 diagnosis_personality_disorder			varchar(255) default null,
 diagnosis_date_personality_disorder			date default null,
 diagnosis_mental_retardation_disorder		varchar(255) default null,
 diagnosis_date_mental_retardation_disorder		date default null,
 diagnosis_psych_development_disorder			varchar(255) default null,
 diagnosis_date_psych_development_disorder		date default null,
 hiv_status 					varchar(255) default null,
 hiv_test_date 				date default null,
 art_start_date 				date default null,
 tb_status 					varchar(255) default null,
 tb_year 					decimal(10,2) default null,
 hallucinations 				varchar(255) default null,
 hallucinations_date 				date default null,
 delusions 					varchar(255) default null,
 delusions_date 				date default null,
 disorganised_or_disruptive_behaviour 	varchar(255) default null,
 disorganised_or_disruptive_behaviour_date 	date default null,
 disorganised_speech 				varchar(255) default null,
 disorganised_speech_date 			date default null,
 depressive_symptoms 				varchar(255) default null,
 depressive_symptoms_date 			date default null,
 other_complaints 				varchar(255) default null,
 other_complaints_date 			date default null,
 alcohol_exposure 				varchar(255) default null,
 alcohol_years_exposed 			decimal(10,2) default null,
 alcohol_date_last_used 			date default null,
 marijuana_exposure 				varchar(255) default null,
 marijuana_years_exposed			decimal(10,2) default null,
 marijuana_date_last_used 			date default null,
 other_drugs_exposure 				varchar(255) default null,
 other_drugs_years_exposed 			decimal(10,2) default null,
 other_drugs_date_last_used 			date default null,
 traditional_med_exposure 			varchar(255) default null,
 traditional_med_years_exposed 		decimal(10,2) default null,
 traditional_med_date_last_used 		date default null,
 epilepsy_family_history 			varchar(255) default null,
 mental_family_history 			varchar(255) default null,
 behavior_problems_family_history 		varchar(255) default null
) ;

insert into mw_mental_health_initial
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_mood_affective_disorder_depression,
    max(case when o.concept = 'Date of exposure' then o.value_date end) as alcohol_date_last_used,
    max(case when o.concept = 'History of alcohol use' then o.value_coded end) as alcohol_exposure,
    max(case when o.concept = 'Duration in years' then o.value_numeric end) as alcohol_years_exposed,
    max(case when o.concept = 'Family history of behavioral problems' then o.value_coded end) as behavior_problems_family_history,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as delusions_date,
    max(case when o.concept = 'Mental health chief complaint' and o.value_coded = 'Depressive Disorder' then o.value_coded end) as depressive_symptoms,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as depressive_symptoms_date,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Schizophrenia' then o.value_coded end) as diagnosis_schizophrenia,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_stress_reactive_adjustment_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Acute Psychotic disorder' then o.value_coded end) as diagnosis_acute_and_transient_psychotic,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Anxiety disorder' then o.value_coded end) as diagnosis_anxiety_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Mood Affective Disorder (Bipolar)' then o.value_coded end) as diagnosis_bipolar_mood_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_schizophrenia,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_acute_and_transient_psychotic,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_anxiety_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_bipolar_mood_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_dissociative_mood_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_drug_use_mental_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_hyperkinetic_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_mood_affective_disorder_manic,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_organic_mental_disorder_acute,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_organic_mental_disorder_chronic,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_puerperal_mental_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_schizoaffective_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Dissociative Conversion Disorder' then o.value_coded end) as diagnosis_dissociative_mood_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Drug-induced mental and behavior disorder' then o.value_coded end) as diagnosis_drug_use_mental_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Hyperkinetic Conductal Disorder (ADHD)' then o.value_coded end) as diagnosis_hyperkinetic_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Depression' then o.value_coded end) as diagnosis_mood_affective_disorder_depression,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Bipolar Affective Disorder, Manic' then o.value_coded end) as diagnosis_mood_affective_disorder_manic,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Organic mental disorder (acute)' then o.value_coded end) as diagnosis_organic_mental_disorder_acute,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Organic mental disorder (chronic)' then o.value_coded end) as diagnosis_organic_mental_disorder_chronic,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Puerperal Mental Disorder' then o.value_coded end) as diagnosis_puerperal_mental_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Schizoaffective Disorder' then o.value_coded end) as diagnosis_schizoaffective_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Stress Reaction Adjustment Disorder' then o.value_coded end) as diagnosis_stress_reactive_adjustment_disorder,
    max(case when o.concept = 'Mental health chief complaint' and o.value_coded = 'Disruptive Behavior Disorder' then o.value_coded end) as disorganised_or_disruptive_behaviour,
    max(case when o.concept = 'Mental health chief complaint' and o.value_coded = 'Abnormal speech' then o.value_coded end) as disorganised_speech,
    max(case when o.concept = 'Family history of epilepsy' then o.value_coded end) as epilepsy_family_history,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as hallucinations_date,
    max(case when o.concept = 'Date of exposure' then o.value_date end) as marijuana_date_last_used,
    max(case when o.concept = 'History of exposure' then o.value_coded end) as marijuana_exposure,
    max(case when o.concept = 'Duration in years' then o.value_numeric end) as marijuana_years_exposed,
    max(case when o.concept = 'Family history of mental illness' then o.value_coded end) as mental_family_history,
    max(case when o.concept = 'Mental health chief complaint' and o.value_coded = 'Other non-coded' then o.value_coded end) as other_complaints,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as other_complaints_date,
    max(case when o.concept = 'Date of exposure' then o.value_date end) as other_drugs_date_last_used,
    max(case when o.concept = 'History of exposure' then o.value_coded end) as other_drugs_exposure,
    max(case when o.concept = 'Duration in years' then o.value_numeric end) as other_drugs_years_exposed,
    max(case when o.concept = 'Date of exposure' then o.value_date end) as traditional_med_date_last_used,
    max(case when o.concept = 'History of exposure' then o.value_coded end) as traditional_med_exposure,
    max(case when o.concept = 'Duration in years' then o.value_numeric end) as traditional_med_years_exposed,
    max(case when o.concept = 'Chronic care diagnosis' then o.value_coded end) as diagnosis_other_3,
    max(case when o.concept = 'Date antiretrovirals started' then o.value_date end) as art_start_date,
    max(case when o.concept = 'Mental health chief complaint' and o.value_coded = 'Delusions' then o.value_coded end) as delusions,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Alcohol-induced mental and behavior disorder' then o.value_coded end) as diagnosis_alcohol_use_mental_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_alcohol_use_mental_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_mental_retardation_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_other_1,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_other_2,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_other_3,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_personality_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_psych_development_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as diagnosis_date_somatoform_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Mental retardation' then o.value_coded end) as diagnosis_mental_retardation_disorder,
    max(case when o.concept = 'Other non-coded (text)' then o.value_text end) as diagnosis_other_1,
    max(case when o.concept = 'Other non-coded (text)' then o.value_text end) as diagnosis_other_2,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Personality Disorder' then o.value_coded end) as diagnosis_personality_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Psychological development disorder' then o.value_coded end) as diagnosis_psych_development_disorder,
    max(case when o.concept = 'Chronic care diagnosis' and o.value_coded = 'Somatoform Disorder' then o.value_coded end) as diagnosis_somatoform_disorder,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as disorganised_or_disruptive_behaviour_date,
    max(case when o.concept = 'Diagnosis date' then o.value_date end) as disorganised_speech_date,
    max(case when o.concept = 'Mental health chief complaint' and o.value_coded = 'Hallucinations' then o.value_coded end) as hallucinations,
    max(case when o.concept = 'HIV status' then o.value_coded end) as hiv_status,
    max(case when o.concept = 'HIV test date' then o.value_date end) as hiv_test_date,
    max(case when o.concept = 'TB status' then o.value_coded end) as tb_status,
    max(case when o.concept = 'Year of Tuberculosis diagnosis' then o.value_numeric end) as tb_year
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('MENTAL_HEALTH_INITIAL')
group by e.patient_id, e.encounter_date, e.location;