-- Derivation script for mw_pdc_initial
-- Generated from Pentaho transform: import-into-mw-pdc-initial.ktr

DROP TABLE IF EXISTS mw_pdc_initial;
CREATE TABLE mw_pdc_initial (
  pdc_initial_visit_id 				int NOT NULL AUTO_INCREMENT,
  patient_id 					int NOT NULL,
  visit_date 					date DEFAULT NULL,
  location 					varchar(255) DEFAULT NULL,
  transfer_in_date				date DEFAULT NULL,
  phone_number					int DEFAULT NULL,
  relation_to_patient				varchar(255) DEFAULT NULL,
  agrees_to_fup					varchar(10) DEFAULT NULL,
  guardian_name 				varchar(255) DEFAULT NULL,
  guardian_age					varchar(255) DEFAULT NULL,
  marital_status				varchar(255) DEFAULT NULL,
  level_of_education				varchar(255) DEFAULT NULL,
  number_of_children				int DEFAULT NULL,
  income_source					varchar(255) DEFAULT NULL,
  source_of_referral				varchar(255) DEFAULT NULL,
  mother_hiv_reactive				varchar(255) DEFAULT NULL,
  mother_on_art					varchar(255) DEFAULT NULL,
  child_hiv_reactive				varchar(255) DEFAULT NULL,
  child_on_art					varchar(255) DEFAULT NULL,
  eligible_for_poser				varchar(10) DEFAULT NULL,
  referral_form_filled				varchar(10) DEFAULT NULL,
  birth_site					varchar(255) DEFAULT NULL,
  birth_history_svd				varchar(255) DEFAULT NULL,
  birth_history_cs				varchar(255) DEFAULT NULL,
  birth_history_agpar				varchar(255) DEFAULT NULL,
  birth_history_bwt				varchar(255) DEFAULT NULL,
  perinatal_infection				varchar(255) DEFAULT NULL,
  perinatal_infection_specify			varchar(255) DEFAULT NULL,
  antibiotics					varchar(10) DEFAULT NULL,
  antibiotics_duration				varchar(255) DEFAULT NULL,
  currently_on_medication			varchar(255) DEFAULT NULL,
  currently_on_medication_specify		varchar(255) DEFAULT NULL,
  type_of_feed_breast_milk			varchar(255) DEFAULT NULL,
  type_of_feed_infant_formula			varchar(255) DEFAULT NULL,
  type_of_feed_mixed_feeding			varchar(255) DEFAULT NULL,
  type_of_feed_solids				varchar(255) DEFAULT NULL,
  feeding_method_bf				varchar(255) DEFAULT NULL,
  feeding_method_cup				varchar(255) DEFAULT NULL,
  feeding_method_ogt				varchar(255) DEFAULT NULL,
  feeding_method_other				varchar(255) DEFAULT NULL,
  notes						varchar(255) DEFAULT NULL,
  reason_for_referral_premature_birth  		varchar(255) DEFAULT NULL,
  reason_for_referral_hie			varchar(255) DEFAULT NULL,
  reason_for_referral_low_birth_weight 		varchar(255) DEFAULT NULL,
  reason_for_referral_hydrocephalus		varchar(255) DEFAULT NULL,
  reason_for_referral_cleft_lip			varchar(255) DEFAULT NULL,
  reason_for_referral_cleft_palate		varchar(255) DEFAULT NULL,
  reason_for_referral_cns_infection		varchar(255) DEFAULT NULL,
  reason_for_referral_cns_infection_specify 	varchar(255) DEFAULT NULL,
  reason_for_referral_other			varchar(255) DEFAULT NULL,
  reason_for_referral_other_specify		varchar(255) DEFAULT NULL,
  reason_for_referral_trisomy_21		varchar(255) DEFAULT NULL,
  reason_for_referral_severe_malnutrition 	varchar(255) DEFAULT NULL,
  reason_for_referral_epilepsy 			varchar(255) DEFAULT NULL,
  enrolled_in_pdc		 		varchar(255) DEFAULT NULL,
  premature_birth 				varchar(255) DEFAULT NULL,
  hie						varchar(255) DEFAULT NULL,
  low_birth_weight				varchar(255) DEFAULT NULL,
  hydrocephalus					varchar(255) DEFAULT NULL,
  cleft_lip					varchar(255) DEFAULT NULL,
  cleft_palate					varchar(255) DEFAULT NULL,
  cns_infection					varchar(255) DEFAULT NULL,
  cns_infection_specify				varchar(255) DEFAULT NULL,
  diagnosis_other				varchar(255) DEFAULT NULL,
  diagnosis_other_specify			varchar(255) DEFAULT NULL,
  trisomy_21					varchar(255) DEFAULT NULL,
  severe_malnutrition 				varchar(255) DEFAULT NULL,
  epilepsy 					varchar(255) DEFAULT NULL,
  care_linked					varchar(255) DEFAULT NULL,
  clinical_care					varchar(255) DEFAULT NULL,
  nru						varchar(255) DEFAULT NULL,
  ic3						varchar(255) DEFAULT NULL,
  advanced_ncd					varchar(255) DEFAULT NULL,
  mental_health_clinic				varchar(255) DEFAULT NULL,
  palliative					varchar(255) DEFAULT NULL,
  physiotherapy					varchar(255) DEFAULT NULL,
  other_support					varchar(255) DEFAULT NULL,
  PRIMARY KEY (pdc_initial_visit_id)
) ;

INSERT INTO mw_pdc_initial
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Care Linked Type' AND o.value_coded = 'Advanced NCD clinic' THEN o.value_coded END) as advanced_ncd,
    MAX(CASE WHEN o.concept = 'Follow up agreement' THEN o.value_coded END) as agrees_to_fup,
    MAX(CASE WHEN o.concept = 'Currently (or in the last week) taking antibiotics' THEN o.value_coded END) as antibiotics,
    MAX(CASE WHEN o.concept = 'Duration (coded)' THEN o.value_coded END) as antibiotics_duration,
    MAX(CASE WHEN o.concept = 'Method of delivery' AND o.value_coded = 'Appearance, Grimace, Pulse rate, Activity, Respirations' THEN o.value_coded END) as birth_history_agpar,
    MAX(CASE WHEN o.concept = 'Method of delivery' AND o.value_coded = 'Caesarean section' THEN o.value_coded END) as birth_history_cs,
    MAX(CASE WHEN o.concept = 'Method of delivery' AND o.value_coded = 'Spontaneous vaginal delivery' THEN o.value_coded END) as birth_history_svd,
    MAX(CASE WHEN o.concept = 'Birth location type' THEN o.value_coded END) as birth_site,
    MAX(CASE WHEN o.concept = 'Method of delivery' AND o.value_coded = 'Birth weight' THEN o.value_coded END) as birth_history_bwt,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Nervous system diagnosis' THEN o.value_coded END) as cns_infection,
    MAX(CASE WHEN o.concept = 'Care Linked' THEN o.value_coded END) as care_linked,
    MAX(CASE WHEN o.concept = 'HIV status' THEN o.value_coded END) as child_hiv_reactive,
    MAX(CASE WHEN o.concept = 'Childs current HIV status' THEN o.value_coded END) as child_on_art,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Cleft Lip' THEN o.value_coded END) as cleft_lip,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Cleft Palate' THEN o.value_coded END) as cleft_palate,
    MAX(CASE WHEN o.concept = 'Care Linked Type' AND o.value_coded = 'Clinical' THEN o.value_coded END) as clinical_care,
    MAX(CASE WHEN o.concept = 'drugs' THEN o.value_text END) as currently_on_medication_specify,
    MAX(CASE WHEN o.concept = 'Current drugs used' THEN o.value_coded END) as currently_on_medication,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Diagnosis, non-coded' THEN o.value_coded END) as diagnosis_other,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Premature Birth' THEN o.value_coded END) as premature_birth,
    MAX(CASE WHEN o.concept = 'Poser Support' THEN o.value_coded END) as eligible_for_poser,
    MAX(CASE WHEN o.concept = 'Enrolled in PDC' THEN o.value_coded END) as enrolled_in_pdc,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Epilepsy' THEN o.value_coded END) as epilepsy,
    MAX(CASE WHEN o.concept = 'Infant feeding method' AND o.value_coded = 'Breast feeding' THEN o.value_coded END) as feeding_method_bf,
    MAX(CASE WHEN o.concept = 'Infant feeding method' AND o.value_coded = 'Cup-feeding' THEN o.value_coded END) as feeding_method_cup,
    MAX(CASE WHEN o.concept = 'Infant feeding method' AND o.value_coded = 'Orogastric tube' THEN o.value_coded END) as feeding_method_ogt,
    MAX(CASE WHEN o.concept = 'Other non-coded (text)' THEN o.value_text END) as feeding_method_other,
    MAX(CASE WHEN o.concept = 'Age of guardian' THEN o.value_numeric END) as guardian_age,
    MAX(CASE WHEN o.concept = 'Guardian; name and first names' THEN o.value_text END) as guardian_name,
    MAX(CASE WHEN o.concept = 'Next of kin telephone' THEN o.value_text END) as guardian_phone,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Hypoxic Ischemic Encephalopathy' THEN o.value_coded END) as hie,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Hydrocephalus' THEN o.value_coded END) as hydrocephalus,
    MAX(CASE WHEN o.concept = 'Care Linked Type' AND o.value_coded = 'IC3' THEN o.value_coded END) as ic3,
    MAX(CASE WHEN o.concept = 'Income Source' THEN o.value_text END) as income_source,
    MAX(CASE WHEN o.concept = 'Highest level of school completed' THEN o.value_coded END) as level_of_education,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Low birth weight' THEN o.value_coded END) as low_birth_weight,
    MAX(CASE WHEN o.concept = 'Civil status' THEN o.value_coded END) as marital_status,
    MAX(CASE WHEN o.concept = 'Care Linked Type' AND o.value_coded = 'Mental Health Clinic' THEN o.value_coded END) as mental_health_clinic,
    MAX(CASE WHEN o.concept = 'HIV status' THEN o.value_coded END) as mother_hiv_reactive,
    MAX(CASE WHEN o.concept = 'Mother HIV Status' THEN o.value_coded END) as mother_on_art,
    MAX(CASE WHEN o.concept = 'Care Linked Type' AND o.value_coded = 'Nutrition Rehabilitation Unit' THEN o.value_coded END) as nru,
    MAX(CASE WHEN o.concept = 'Clinical impression comments' THEN o.value_text END) as notes,
    MAX(CASE WHEN o.concept = 'Number of children' THEN o.value_numeric END) as number_of_children,
    MAX(CASE WHEN o.concept = 'Type of support' THEN o.value_text END) as other_support,
    MAX(CASE WHEN o.concept = 'Care Linked Type' AND o.value_coded = 'Paliative linked care' THEN o.value_coded END) as palliative,
    MAX(CASE WHEN o.concept = 'Perinatal infection' THEN o.value_coded END) as perinatal_infection,
    MAX(CASE WHEN o.concept = 'Other non-coded (text)' THEN o.value_text END) as perinatal_infection_specify,
    MAX(CASE WHEN o.concept = 'Telephone number' THEN o.value_numeric END) as phone_number,
    MAX(CASE WHEN o.concept = 'Care Linked Type' AND o.value_coded = 'Physiotherapy linked care' THEN o.value_coded END) as physiotherapy,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Hypoxic Ischemic Encephalopathy' THEN o.value_coded END) as reason_for_referral_hie,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Nervous system diagnosis' THEN o.value_coded END) as reason_for_referral_cns_infection,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Cleft Lip' THEN o.value_coded END) as reason_for_referral_cleft_lip,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Cleft Palate' THEN o.value_coded END) as reason_for_referral_cleft_palate,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Epilepsy' THEN o.value_coded END) as reason_for_referral_epilepsy,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Hydrocephalus' THEN o.value_coded END) as reason_for_referral_hydrocephalus,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Low birth weight' THEN o.value_coded END) as reason_for_referral_low_birth_weight,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Diagnosis, non-coded' THEN o.value_coded END) as reason_for_referral_other,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Premature Birth' THEN o.value_coded END) as reason_for_referral_premature_birth,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Severe malnutrition' THEN o.value_coded END) as reason_for_referral_severe_malnutrition,
    MAX(CASE WHEN o.concept = 'PDC Reasons for referral' AND o.value_coded = 'Trisomy 21' THEN o.value_coded END) as reason_for_referral_trisomy_21,
    MAX(CASE WHEN o.concept = 'Referral Form Filled' THEN o.value_coded END) as referral_form_filled,
    MAX(CASE WHEN o.concept = 'Relationships of contact' THEN o.value_text END) as relation_to_patient,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Severe malnutrition' THEN o.value_coded END) as severe_malnutrition,
    MAX(CASE WHEN o.concept = 'Referral Source' THEN o.value_coded END) as source_of_referral,
    MAX(CASE WHEN o.concept = 'Transfer in date' THEN o.value_date END) as transfer_in_date,
    MAX(CASE WHEN o.concept = 'Diagnosis' AND o.value_coded = 'Trisomy 21' THEN o.value_coded END) as trisomy_21,
    MAX(CASE WHEN o.concept = 'Type of Feed' AND o.value_coded = 'Breast Milk' THEN o.value_coded END) as type_of_feed_breast_milk,
    MAX(CASE WHEN o.concept = 'Type of Feed' AND o.value_coded = 'Infant Formula' THEN o.value_coded END) as type_of_feed_infant_formula,
    MAX(CASE WHEN o.concept = 'Type of Feed' AND o.value_coded = 'Food Package' THEN o.value_coded END) as type_of_feed_solids,
    MAX(CASE WHEN o.concept = 'Type of Feed' AND o.value_coded = 'Mixed feeding' THEN o.value_coded END) as type_of_feed_mixed_feeding
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('PDC_INITIAL')
GROUP BY e.patient_id, e.encounter_date, e.location;