-- Derivation script for mw_pdc_initial
-- Generated from Pentaho transform: import-into-mw-pdc-initial.ktr

drop table if exists mw_pdc_initial;
create table mw_pdc_initial
(
    pdc_initial_visit_id                      int not null auto_increment,
    patient_id                                int not null,
    visit_date                                date         default null,
    location                                  varchar(255) default null,
    transfer_in_date                          date         default null,
    phone_number                              int          default null,
    relation_to_patient                       varchar(255) default null,
    agrees_to_fup                             varchar(10)  default null,
    guardian_name                             varchar(255) default null,
    guardian_age                              varchar(255) default null,
    guardian_phone                            varchar(255),
    marital_status                            varchar(255) default null,
    level_of_education                        varchar(255) default null,
    number_of_children                        int          default null,
    income_source                             varchar(255) default null,
    source_of_referral                        varchar(255) default null,
    mother_hiv_reactive                       varchar(255) default null,
    mother_on_art                             varchar(255) default null,
    child_hiv_reactive                        varchar(255) default null,
    child_on_art                              varchar(255) default null,
    eligible_for_poser                        varchar(10)  default null,
    referral_form_filled                      varchar(10)  default null,
    birth_site                                varchar(255) default null,
    birth_history_svd                         varchar(255) default null,
    birth_history_cs                          varchar(255) default null,
    birth_history_agpar                       varchar(255) default null,
    birth_history_bwt                         varchar(255) default null,
    perinatal_infection                       varchar(255) default null,
    perinatal_infection_specify               varchar(255) default null,
    antibiotics                               varchar(10)  default null,
    antibiotics_duration                      varchar(255) default null,
    currently_on_medication                   varchar(255) default null,
    currently_on_medication_specify           varchar(255) default null,
    type_of_feed_breast_milk                  varchar(255) default null,
    type_of_feed_infant_formula               varchar(255) default null,
    type_of_feed_mixed_feeding                varchar(255) default null,
    type_of_feed_solids                       varchar(255) default null,
    feeding_method_bf                         varchar(255) default null,
    feeding_method_cup                        varchar(255) default null,
    feeding_method_ogt                        varchar(255) default null,
    feeding_method_other                      varchar(255) default null,
    notes                                     varchar(255) default null,
    reason_for_referral_premature_birth       varchar(255) default null,
    reason_for_referral_hie                   varchar(255) default null,
    reason_for_referral_low_birth_weight      varchar(255) default null,
    reason_for_referral_hydrocephalus         varchar(255) default null,
    reason_for_referral_cleft_lip             varchar(255) default null,
    reason_for_referral_cleft_palate          varchar(255) default null,
    reason_for_referral_cns_infection         varchar(255) default null,
    reason_for_referral_cns_infection_specify varchar(255) default null,
    reason_for_referral_other                 varchar(255) default null,
    reason_for_referral_other_specify         varchar(255) default null,
    reason_for_referral_trisomy_21            varchar(255) default null,
    reason_for_referral_severe_malnutrition   varchar(255) default null,
    reason_for_referral_epilepsy              varchar(255) default null,
    enrolled_in_pdc                           varchar(255) default null,
    premature_birth                           varchar(255) default null,
    hie                                       varchar(255) default null,
    low_birth_weight                          varchar(255) default null,
    hydrocephalus                             varchar(255) default null,
    cleft_lip                                 varchar(255) default null,
    cleft_palate                              varchar(255) default null,
    cns_infection                             varchar(255) default null,
    cns_infection_specify                     varchar(255) default null,
    diagnosis_other                           varchar(255) default null,
    diagnosis_other_specify                   varchar(255) default null,
    trisomy_21                                varchar(255) default null,
    severe_malnutrition                       varchar(255) default null,
    epilepsy                                  varchar(255) default null,
    care_linked                               varchar(255) default null,
    clinical_care                             varchar(255) default null,
    nru                                       varchar(255) default null,
    ic3                                       varchar(255) default null,
    advanced_ncd                              varchar(255) default null,
    mental_health_clinic                      varchar(255) default null,
    palliative                                varchar(255) default null,
    physiotherapy                             varchar(255) default null,
    other_support                             varchar(255) default null,
    primary key (pdc_initial_visit_id)
);

drop temporary table if exists temp_pdc_initial_obs;
create temporary table temp_pdc_initial_obs as
select encounter_id, obs_group_id, concept, value_coded, value_numeric, value_date, value_text
from omrs_obs
where encounter_type = 'PDC_INITIAL';
alter table temp_pdc_initial_obs add index temp_pdc_initial_obs_concept_idx (concept);
alter table temp_pdc_initial_obs add index temp_pdc_initial_obs_encounter_idx (encounter_id);
alter table temp_pdc_initial_obs add index temp_pdc_initial_obs_group_idx (obs_group_id);

drop temporary table if exists temp_single_values;
create temporary table temp_single_values as
select
    encounter_id,
    -- Care Linked Type (multi-value: pivoted by specific value)
    max(case when concept = 'Care Linked Type' and value_coded = 'Advanced NCD clinic'          then value_coded end) as advanced_ncd,
    max(case when concept = 'Care Linked Type' and value_coded = 'Clinical'                     then value_coded end) as clinical_care,
    max(case when concept = 'Care Linked Type' and value_coded = 'IC3'                          then value_coded end) as ic3,
    max(case when concept = 'Care Linked Type' and value_coded = 'Mental Health Clinic'         then value_coded end) as mental_health_clinic,
    max(case when concept = 'Care Linked Type' and value_coded = 'Nutrition Rehabilitation Unit' then value_coded end) as nru,
    max(case when concept = 'Care Linked Type' and value_coded = 'Paliative linked care'        then value_coded end) as palliative,
    max(case when concept = 'Care Linked Type' and value_coded = 'Physiotherapy linked care'    then value_coded end) as physiotherapy,
    -- Single-value obs
    max(case when concept = 'Follow up agreement'                                               then value_coded   end) as agrees_to_fup,
    max(case when concept = 'Currently (or in the last week) taking antibiotics'                then value_coded   end) as antibiotics,
    max(case when concept = 'Duration (coded)'                                                  then value_coded   end) as antibiotics_duration,
    max(case when concept = 'Birth location type'                                               then value_coded   end) as birth_site,
    max(case when concept = 'Care Linked'                                                       then value_coded   end) as care_linked,
    max(case when concept = 'HIV status'                                                        then value_coded   end) as child_hiv_reactive,
    max(case when concept = 'Childs current HIV status'                                         then value_coded   end) as child_on_art,
    max(case when concept = 'Clinical impression comments'                                      then value_text    end) as notes,
    max(case when concept = 'Current drugs used'                                                then value_coded   end) as currently_on_medication,
    max(case when concept = 'drugs'                                                             then value_text    end) as currently_on_medication_specify,
    -- Diagnosis (multi-value: pivoted by specific value)
    max(case when concept = 'Diagnosis' and value_coded = 'Nervous system diagnosis'            then value_coded   end) as cns_infection,
    max(case when concept = 'Diagnosis' and value_coded = 'Cleft Lip'                          then value_coded   end) as cleft_lip,
    max(case when concept = 'Diagnosis' and value_coded = 'Cleft Palate'                       then value_coded   end) as cleft_palate,
    max(case when concept = 'Diagnosis' and value_coded = 'Diagnosis, non-coded'               then value_coded   end) as diagnosis_other,
    max(case when concept = 'Diagnosis' and value_coded = 'Premature Birth'                    then value_coded   end) as premature_birth,
    max(case when concept = 'Diagnosis' and value_coded = 'Epilepsy'                           then value_coded   end) as epilepsy,
    max(case when concept = 'Diagnosis' and value_coded = 'Hypoxic Ischemic Encephalopathy'    then value_coded   end) as hie,
    max(case when concept = 'Diagnosis' and value_coded = 'Hydrocephalus'                      then value_coded   end) as hydrocephalus,
    max(case when concept = 'Diagnosis' and value_coded = 'Low birth weight'                   then value_coded   end) as low_birth_weight,
    max(case when concept = 'Diagnosis' and value_coded = 'Severe malnutrition'                then value_coded   end) as severe_malnutrition,
    max(case when concept = 'Diagnosis' and value_coded = 'Trisomy 21'                         then value_coded   end) as trisomy_21,
    max(case when concept = 'Enrolled in PDC'                                                  then value_coded   end) as enrolled_in_pdc,
    -- Infant feeding method (multi-value: pivoted by specific value)
    max(case when concept = 'Infant feeding method' and value_coded = 'Breast feeding'         then value_coded   end) as feeding_method_bf,
    max(case when concept = 'Infant feeding method' and value_coded = 'Cup-feeding'            then value_coded   end) as feeding_method_cup,
    max(case when concept = 'Infant feeding method' and value_coded = 'Orogastric tube'        then value_coded   end) as feeding_method_ogt,
    max(case when concept = 'Age of guardian'                                                  then value_numeric end) as guardian_age,
    max(case when concept = 'Guardian; name and first names'                                   then value_text    end) as guardian_name,
    max(case when concept = 'Next of kin telephone'                                            then value_text    end) as guardian_phone,
    max(case when concept = 'Income Source'                                                    then value_text    end) as income_source,
    max(case when concept = 'Highest level of school completed'                                then value_coded   end) as level_of_education,
    max(case when concept = 'Civil status'                                                     then value_coded   end) as marital_status,
    -- Method of delivery (multi-value: pivoted by specific value)
    max(case when concept = 'Method of delivery' and value_coded = 'Appearance, Grimace, Pulse rate, Activity, Respirations' then value_coded end) as birth_history_agpar,
    max(case when concept = 'Method of delivery' and value_coded = 'Caesarean section'         then value_coded   end) as birth_history_cs,
    max(case when concept = 'Method of delivery' and value_coded = 'Spontaneous vaginal delivery' then value_coded end) as birth_history_svd,
    max(case when concept = 'Method of delivery' and value_coded = 'Birth weight'              then value_coded   end) as birth_history_bwt,
    max(case when concept = 'Mother HIV Status'                                                then value_coded   end) as mother_on_art,
    max(case when concept = 'Number of children'                                               then value_numeric end) as number_of_children,
    max(case when concept = 'Other non-coded (text)'                                           then value_text    end) as feeding_method_other,
    max(case when concept = 'Perinatal infection'                                              then value_coded   end) as perinatal_infection,
    max(case when concept = 'Telephone number'                                                 then value_numeric end) as phone_number,
    max(case when concept = 'Poser Support'                                                    then value_coded   end) as eligible_for_poser,
    -- PDC Reasons for referral (multi-value: pivoted by specific value)
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Hypoxic Ischemic Encephalopathy' then value_coded end) as reason_for_referral_hie,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Nervous system diagnosis'        then value_coded end) as reason_for_referral_cns_infection,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Cleft Lip'                       then value_coded end) as reason_for_referral_cleft_lip,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Cleft Palate'                    then value_coded end) as reason_for_referral_cleft_palate,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Epilepsy'                        then value_coded end) as reason_for_referral_epilepsy,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Hydrocephalus'                   then value_coded end) as reason_for_referral_hydrocephalus,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Low birth weight'                then value_coded end) as reason_for_referral_low_birth_weight,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Diagnosis, non-coded'            then value_coded end) as reason_for_referral_other,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Premature Birth'                 then value_coded end) as reason_for_referral_premature_birth,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Severe malnutrition'             then value_coded end) as reason_for_referral_severe_malnutrition,
    max(case when concept = 'PDC Reasons for referral' and value_coded = 'Trisomy 21'                      then value_coded end) as reason_for_referral_trisomy_21,
    max(case when concept = 'Referral Form Filled'                                             then value_coded   end) as referral_form_filled,
    max(case when concept = 'Relationships of contact'                                         then value_text    end) as relation_to_patient,
    max(case when concept = 'Referral Source'                                                  then value_coded   end) as source_of_referral,
    max(case when concept = 'Transfer in date'                                                 then value_date    end) as transfer_in_date,
    -- Type of Feed (multi-value: pivoted by specific value)
    max(case when concept = 'Type of Feed' and value_coded = 'Breast Milk'                    then value_coded   end) as type_of_feed_breast_milk,
    max(case when concept = 'Type of Feed' and value_coded = 'Infant Formula'                 then value_coded   end) as type_of_feed_infant_formula,
    max(case when concept = 'Type of Feed' and value_coded = 'Food Package'                   then value_coded   end) as type_of_feed_solids,
    max(case when concept = 'Type of Feed' and value_coded = 'Mixed feeding'                  then value_coded   end) as type_of_feed_mixed_feeding,
    max(case when concept = 'Type of support'                                                  then value_text    end) as other_support
from temp_pdc_initial_obs
group by encounter_id;
alter table temp_single_values add index temp_single_values_encounter_idx (encounter_id);

insert into mw_pdc_initial (patient_id, visit_date, location, advanced_ncd, agrees_to_fup, antibiotics, antibiotics_duration, birth_history_agpar, birth_history_cs, birth_history_svd, birth_site, birth_history_bwt, cns_infection, care_linked, child_hiv_reactive, child_on_art, cleft_lip, cleft_palate, clinical_care, currently_on_medication_specify, currently_on_medication, diagnosis_other, premature_birth, eligible_for_poser, enrolled_in_pdc, epilepsy, feeding_method_bf, feeding_method_cup, feeding_method_ogt, feeding_method_other, guardian_age, guardian_name, guardian_phone, hie, hydrocephalus, ic3, income_source, level_of_education, low_birth_weight, marital_status, mental_health_clinic, mother_hiv_reactive, mother_on_art, nru, notes, number_of_children, other_support, palliative, perinatal_infection, perinatal_infection_specify, phone_number, physiotherapy, reason_for_referral_hie, reason_for_referral_cns_infection, reason_for_referral_cleft_lip, reason_for_referral_cleft_palate, reason_for_referral_epilepsy, reason_for_referral_hydrocephalus, reason_for_referral_low_birth_weight, reason_for_referral_other, reason_for_referral_premature_birth, reason_for_referral_severe_malnutrition, reason_for_referral_trisomy_21, referral_form_filled, relation_to_patient, severe_malnutrition, source_of_referral, transfer_in_date, trisomy_21, type_of_feed_breast_milk, type_of_feed_infant_formula, type_of_feed_solids, type_of_feed_mixed_feeding)
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    sv.advanced_ncd,
    sv.agrees_to_fup,
    sv.antibiotics,
    sv.antibiotics_duration,
    sv.birth_history_agpar,
    sv.birth_history_cs,
    sv.birth_history_svd,
    sv.birth_site,
    sv.birth_history_bwt,
    sv.cns_infection,
    sv.care_linked,
    sv.child_hiv_reactive,
    sv.child_on_art,
    sv.cleft_lip,
    sv.cleft_palate,
    sv.clinical_care,
    sv.currently_on_medication_specify,
    sv.currently_on_medication,
    sv.diagnosis_other,
    sv.premature_birth,
    sv.eligible_for_poser,
    sv.enrolled_in_pdc,
    sv.epilepsy,
    sv.feeding_method_bf,
    sv.feeding_method_cup,
    sv.feeding_method_ogt,
    sv.feeding_method_other,
    sv.guardian_age,
    sv.guardian_name,
    sv.guardian_phone,
    sv.hie,
    sv.hydrocephalus,
    sv.ic3,
    sv.income_source,
    sv.level_of_education,
    sv.low_birth_weight,
    sv.marital_status,
    sv.mental_health_clinic,
    sv.child_hiv_reactive,
    sv.mother_on_art,
    sv.nru,
    sv.notes,
    sv.number_of_children,
    sv.other_support,
    sv.palliative,
    sv.perinatal_infection,
    sv.feeding_method_other,
    sv.phone_number,
    sv.physiotherapy,
    sv.reason_for_referral_hie,
    sv.reason_for_referral_cns_infection,
    sv.reason_for_referral_cleft_lip,
    sv.reason_for_referral_cleft_palate,
    sv.reason_for_referral_epilepsy,
    sv.reason_for_referral_hydrocephalus,
    sv.reason_for_referral_low_birth_weight,
    sv.reason_for_referral_other,
    sv.reason_for_referral_premature_birth,
    sv.reason_for_referral_severe_malnutrition,
    sv.reason_for_referral_trisomy_21,
    sv.referral_form_filled,
    sv.relation_to_patient,
    sv.severe_malnutrition,
    sv.source_of_referral,
    sv.transfer_in_date,
    sv.trisomy_21,
    sv.type_of_feed_breast_milk,
    sv.type_of_feed_infant_formula,
    sv.type_of_feed_solids,
    sv.type_of_feed_mixed_feeding
from omrs_encounter e
left join temp_single_values sv on sv.encounter_id = e.encounter_id
where e.encounter_type in ('PDC_INITIAL')
group by e.patient_id, e.encounter_date, e.location;

drop temporary table if exists temp_pdc_initial_obs;
drop temporary table if exists temp_single_values;
