-- Derivation script for mw_poc
-- Generated from Pentaho transform: import-into-mw-poc.ktr

drop table if exists mw_poc;
create table mw_poc (
    poc_visit_id int not null auto_increment,
    patient_id int not null,
    visit_date date,
    location varchar(255),
    sample_taken_for_viral_load varchar(255),
    lower_than_detection_limit varchar(255),
    reason_for_testing varchar(255),
    lab_location varchar(255),
    less_than_limit varchar(255),
    reason_for_no_result varchar(255),
    viral_load_sample_id varchar(255),
    reason_for_no_sample varchar(255),
    lab_id varchar(255),
    symptom_present varchar(255),
    symptom_absent varchar(255),
    adherence_session_number varchar(255),
    name_of_support_provider varchar(255),
    number_of_missed_medication_doses_in_past_week varchar(255),
    viral_load_counseling varchar(255),
    medication_adherence_percent varchar(255),
    adherence_counselling varchar(255),
    date_of_blood_sample date,
    hiv_test_type varchar(255),
    reason_for_no_sample_eid varchar(255),
    result_of_hiv_test varchar(255),
    hiv_test_time_period varchar(255),
    age varchar(13),
    units_of_age_of_child varchar(255),
    lab_test_serial_number varchar(255),
    date_of_returned_result varchar(255),
    date_result_to_guardian date,
    reason_for_testing_coded varchar(255),
    height decimal(10,2),
    is_patient_preg varchar(255),
    muac varchar(255),
    weight decimal(10,2),
    diastolic_blood_pressure decimal(10,2),
    pulse decimal(10,2),
    systolic_blood_pressure decimal(10,2),
    result_of_hiv_test_htc varchar(255),
    hiv_test_type_htc varchar(255),
    colposcopy_of_cervix_with_acetic_acid varchar(255),
    appointment_date date,
    qualitative_time varchar(255),
    outcome varchar(255),
    clinical_impression_comments varchar(300),
    refer_to_screening_station varchar(255),
    transfer_out_to varchar(255),
    reason_to_stop_care varchar(255),
    primary key (poc_visit_id)
);

insert into mw_poc
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Colposcopy of cervix with acetic acid' then o.value_coded end) as colposcopy_of_cervix_with_acetic_acid,
    max(case when o.concept = 'Sample taken for Viral Load' then o.value_coded end) as sample_taken_for_viral_Load,
    max(case when o.concept = 'Adherence counseling (coded)' then o.value_coded end) as adherence_counselling,
    max(case when o.concept = 'Adherence session number' then o.value_coded end) as adherence_session_number,
    max(case when o.concept = 'Age' then o.value_numeric end) as age,
    max(case when o.concept = 'Appointment date' then o.value_date end) as appointment_date,
    max(case when o.concept = 'Clinical impression comments' then o.value_text end) as clinical_impression_comments,
    max(case when o.concept = 'Date of blood sample' then o.value_date end) as date_of_blood_sample,
    max(case when o.concept = 'Date of returned result' then o.value_date end) as date_of_returned_result,
    max(case when o.concept = 'Date result to guardian' then o.value_date end) as date_result_to_guardian,
    max(case when o.concept = 'Diastolic blood pressure' then o.value_numeric end) as diastolic_blood_pressure,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = 'HIV test time period' then o.value_coded end) as hiv_test_time_period,
    max(case when o.concept = 'HIV test type' then o.value_coded end) as hiv_test_type,
    max(case when o.concept = 'HIV test type' then o.value_coded end) as hiv_test_type_htc,
    max(case when o.concept = 'Lab ID' then o.value_text end) as lab_id,
    max(case when o.concept = 'Location of laboratory' then o.value_coded end) as lab_location,
    max(case when o.concept = 'Lab test serial number' then o.value_text end) as lab_test_serial_number,
    max(case when o.concept = 'Less than limit' then o.value_numeric end) as less_than_limit,
    max(case when o.concept = 'Lower than Detection limit' then o.value_coded end) as lower_than_detection_limit,
    max(case when o.concept = 'Medication Adherence percent' then o.value_numeric end) as medication_adherence_percent,
    max(case when o.concept = 'Middle upper arm circumference (cm)' then o.value_numeric end) as muac,
    max(case when o.concept = 'Name of support provider' then o.value_text end) as name_of_support_provider,
    max(case when o.concept = 'Number of missed medication doses in past 7 days' then o.value_numeric end) as number_of_missed_medication_doses_in_past_week,
    max(case when o.concept = 'Outcome' then o.value_coded end) as outcome,
    max(case when o.concept = 'Is patient pregnant?' then o.value_coded end) as is_patient_preg,
    max(case when o.concept = 'Pulse' then o.value_numeric end) as pulse,
    max(case when o.concept = 'Qualitative time' then o.value_coded end) as qualitative_time,
    max(case when o.concept = 'Reason for no result' then o.value_coded end) as reason_for_no_result,
    max(case when o.concept = 'Reason for no sample' then o.value_coded end) as reason_for_no_sample,
    max(case when o.concept = 'Reason for no sample' then o.value_coded end) as reason_for_no_sample_eid,
    max(case when o.concept = 'Reason for testing (coded)' then o.value_coded end) as reason_for_testing,
    max(case when o.concept = 'Reason for testing (coded)' then o.value_coded end) as reason_for_testing_coded,
    max(case when o.concept = 'Reason to stop care (text)' then o.value_text end) as reason_to_stop_care,
    max(case when o.concept = 'Refer to screening station' then o.value_coded end) as refer_to_screening_station,
    max(case when o.concept = 'Result of HIV test' then o.value_coded end) as result_of_hiv_test,
    max(case when o.concept = 'Result of HIV test' then o.value_coded end) as result_of_hiv_test_htc,
    max(case when o.concept = 'Viral Load Sample ID' then o.value_text end) as viral_load_sample_id,
    max(case when o.concept = 'Symptom absent' then o.value_coded end) as symptom_absent,
    max(case when o.concept = 'Symptom present' then o.value_coded end) as symptom_present,
    max(case when o.concept = 'Systolic blood pressure' then o.value_numeric end) as systolic_blood_pressure,
    max(case when o.concept = 'Transfer out to' then o.value_text end) as transfer_out_to,
    max(case when o.concept = 'Units of age of child' then o.value_coded end) as units_of_age_of_child,
    max(case when o.concept = 'Viral load counseling' then o.value_coded end) as viral_load_counseling,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('Check-in')
group by e.patient_id, e.encounter_date, e.location;