-- Derivation script for mw_pdc_initial
-- Generated from Pentaho transform: import-into-mw-pdc-initial.ktr

drop table if exists mw_pdc_initial;
create table mw_pdc_initial (
  pdc_initial_visit_id 				int not null auto_increment,
  patient_id 					int not null,
  visit_date 					date default null,
  location 					varchar(255) default null,
  transfer_in_date				date default null,
  phone_number					int default null,
  relation_to_patient				varchar(255) default null,
  agrees_to_fup					varchar(10) default null,
  guardian_name 				varchar(255) default null,
  guardian_age					varchar(255) default null,
  marital_status				varchar(255) default null,
  level_of_education				varchar(255) default null,
  number_of_children				int default null,
  income_source					varchar(255) default null,
  source_of_referral				varchar(255) default null,
  mother_hiv_reactive				varchar(255) default null,
  mother_on_art					varchar(255) default null,
  child_hiv_reactive				varchar(255) default null,
  child_on_art					varchar(255) default null,
  eligible_for_poser				varchar(10) default null,
  referral_form_filled				varchar(10) default null,
  birth_site					varchar(255) default null,
  birth_history_svd				varchar(255) default null,
  birth_history_cs				varchar(255) default null,
  birth_history_agpar				varchar(255) default null,
  birth_history_bwt				varchar(255) default null,
  perinatal_infection				varchar(255) default null,
  perinatal_infection_specify			varchar(255) default null,
  antibiotics					varchar(10) default null,
  antibiotics_duration				varchar(255) default null,
  currently_on_medication			varchar(255) default null,
  currently_on_medication_specify		varchar(255) default null,
  type_of_feed_breast_milk			varchar(255) default null,
  type_of_feed_infant_formula			varchar(255) default null,
  type_of_feed_mixed_feeding			varchar(255) default null,
  type_of_feed_solids				varchar(255) default null,
  feeding_method_bf				varchar(255) default null,
  feeding_method_cup				varchar(255) default null,
  feeding_method_ogt				varchar(255) default null,
  feeding_method_other				varchar(255) default null,
  notes						varchar(255) default null,
  reason_for_referral_premature_birth  		varchar(255) default null,
  reason_for_referral_hie			varchar(255) default null,
  reason_for_referral_low_birth_weight 		varchar(255) default null,
  reason_for_referral_hydrocephalus		varchar(255) default null,
  reason_for_referral_cleft_lip			varchar(255) default null,
  reason_for_referral_cleft_palate		varchar(255) default null,
  reason_for_referral_cns_infection		varchar(255) default null,
  reason_for_referral_cns_infection_specify 	varchar(255) default null,
  reason_for_referral_other			varchar(255) default null,
  reason_for_referral_other_specify		varchar(255) default null,
  reason_for_referral_trisomy_21		varchar(255) default null,
  reason_for_referral_severe_malnutrition 	varchar(255) default null,
  reason_for_referral_epilepsy 			varchar(255) default null,
  enrolled_in_pdc		 		varchar(255) default null,
  premature_birth 				varchar(255) default null,
  hie						varchar(255) default null,
  low_birth_weight				varchar(255) default null,
  hydrocephalus					varchar(255) default null,
  cleft_lip					varchar(255) default null,
  cleft_palate					varchar(255) default null,
  cns_infection					varchar(255) default null,
  cns_infection_specify				varchar(255) default null,
  diagnosis_other				varchar(255) default null,
  diagnosis_other_specify			varchar(255) default null,
  trisomy_21					varchar(255) default null,
  severe_malnutrition 				varchar(255) default null,
  epilepsy 					varchar(255) default null,
  care_linked					varchar(255) default null,
  clinical_care					varchar(255) default null,
  nru						varchar(255) default null,
  ic3						varchar(255) default null,
  advanced_ncd					varchar(255) default null,
  mental_health_clinic				varchar(255) default null,
  palliative					varchar(255) default null,
  physiotherapy					varchar(255) default null,
  other_support					varchar(255) default null,
  primary key (pdc_initial_visit_id)
) ;

insert into mw_pdc_initial
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Care Linked Type' and o.value_coded = 'Advanced NCD clinic' then o.value_coded end) as advanced_ncd,
    max(case when o.concept = 'Follow up agreement' then o.value_coded end) as agrees_to_fup,
    max(case when o.concept = 'Currently (or in the last week) taking antibiotics' then o.value_coded end) as antibiotics,
    max(case when o.concept = 'Duration (coded)' then o.value_coded end) as antibiotics_duration,
    max(case when o.concept = 'Method of delivery' and o.value_coded = 'Appearance, Grimace, Pulse rate, Activity, Respirations' then o.value_coded end) as birth_history_agpar,
    max(case when o.concept = 'Method of delivery' and o.value_coded = 'Caesarean section' then o.value_coded end) as birth_history_cs,
    max(case when o.concept = 'Method of delivery' and o.value_coded = 'Spontaneous vaginal delivery' then o.value_coded end) as birth_history_svd,
    max(case when o.concept = 'Birth location type' then o.value_coded end) as birth_site,
    max(case when o.concept = 'Method of delivery' and o.value_coded = 'Birth weight' then o.value_coded end) as birth_history_bwt,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Nervous system diagnosis' then o.value_coded end) as cns_infection,
    max(case when o.concept = 'Care Linked' then o.value_coded end) as care_linked,
    max(case when o.concept = 'HIV status' then o.value_coded end) as child_hiv_reactive,
    max(case when o.concept = 'Childs current HIV status' then o.value_coded end) as child_on_art,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Cleft Lip' then o.value_coded end) as cleft_lip,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Cleft Palate' then o.value_coded end) as cleft_palate,
    max(case when o.concept = 'Care Linked Type' and o.value_coded = 'Clinical' then o.value_coded end) as clinical_care,
    max(case when o.concept = 'drugs' then o.value_text end) as currently_on_medication_specify,
    max(case when o.concept = 'Current drugs used' then o.value_coded end) as currently_on_medication,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Diagnosis, non-coded' then o.value_coded end) as diagnosis_other,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Premature Birth' then o.value_coded end) as premature_birth,
    max(case when o.concept = 'Poser Support' then o.value_coded end) as eligible_for_poser,
    max(case when o.concept = 'Enrolled in PDC' then o.value_coded end) as enrolled_in_pdc,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Epilepsy' then o.value_coded end) as epilepsy,
    max(case when o.concept = 'Infant feeding method' and o.value_coded = 'Breast feeding' then o.value_coded end) as feeding_method_bf,
    max(case when o.concept = 'Infant feeding method' and o.value_coded = 'Cup-feeding' then o.value_coded end) as feeding_method_cup,
    max(case when o.concept = 'Infant feeding method' and o.value_coded = 'Orogastric tube' then o.value_coded end) as feeding_method_ogt,
    max(case when o.concept = 'Other non-coded (text)' then o.value_text end) as feeding_method_other,
    max(case when o.concept = 'Age of guardian' then o.value_numeric end) as guardian_age,
    max(case when o.concept = 'Guardian; name and first names' then o.value_text end) as guardian_name,
    max(case when o.concept = 'Next of kin telephone' then o.value_text end) as guardian_phone,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Hypoxic Ischemic Encephalopathy' then o.value_coded end) as hie,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Hydrocephalus' then o.value_coded end) as hydrocephalus,
    max(case when o.concept = 'Care Linked Type' and o.value_coded = 'IC3' then o.value_coded end) as ic3,
    max(case when o.concept = 'Income Source' then o.value_text end) as income_source,
    max(case when o.concept = 'Highest level of school completed' then o.value_coded end) as level_of_education,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Low birth weight' then o.value_coded end) as low_birth_weight,
    max(case when o.concept = 'Civil status' then o.value_coded end) as marital_status,
    max(case when o.concept = 'Care Linked Type' and o.value_coded = 'Mental Health Clinic' then o.value_coded end) as mental_health_clinic,
    max(case when o.concept = 'HIV status' then o.value_coded end) as mother_hiv_reactive,
    max(case when o.concept = 'Mother HIV Status' then o.value_coded end) as mother_on_art,
    max(case when o.concept = 'Care Linked Type' and o.value_coded = 'Nutrition Rehabilitation Unit' then o.value_coded end) as nru,
    max(case when o.concept = 'Clinical impression comments' then o.value_text end) as notes,
    max(case when o.concept = 'Number of children' then o.value_numeric end) as number_of_children,
    max(case when o.concept = 'Type of support' then o.value_text end) as other_support,
    max(case when o.concept = 'Care Linked Type' and o.value_coded = 'Paliative linked care' then o.value_coded end) as palliative,
    max(case when o.concept = 'Perinatal infection' then o.value_coded end) as perinatal_infection,
    max(case when o.concept = 'Other non-coded (text)' then o.value_text end) as perinatal_infection_specify,
    max(case when o.concept = 'Telephone number' then o.value_numeric end) as phone_number,
    max(case when o.concept = 'Care Linked Type' and o.value_coded = 'Physiotherapy linked care' then o.value_coded end) as physiotherapy,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Hypoxic Ischemic Encephalopathy' then o.value_coded end) as reason_for_referral_hie,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Nervous system diagnosis' then o.value_coded end) as reason_for_referral_cns_infection,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Cleft Lip' then o.value_coded end) as reason_for_referral_cleft_lip,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Cleft Palate' then o.value_coded end) as reason_for_referral_cleft_palate,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Epilepsy' then o.value_coded end) as reason_for_referral_epilepsy,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Hydrocephalus' then o.value_coded end) as reason_for_referral_hydrocephalus,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Low birth weight' then o.value_coded end) as reason_for_referral_low_birth_weight,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Diagnosis, non-coded' then o.value_coded end) as reason_for_referral_other,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Premature Birth' then o.value_coded end) as reason_for_referral_premature_birth,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Severe malnutrition' then o.value_coded end) as reason_for_referral_severe_malnutrition,
    max(case when o.concept = 'PDC Reasons for referral' and o.value_coded = 'Trisomy 21' then o.value_coded end) as reason_for_referral_trisomy_21,
    max(case when o.concept = 'Referral Form Filled' then o.value_coded end) as referral_form_filled,
    max(case when o.concept = 'Relationships of contact' then o.value_text end) as relation_to_patient,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Severe malnutrition' then o.value_coded end) as severe_malnutrition,
    max(case when o.concept = 'Referral Source' then o.value_coded end) as source_of_referral,
    max(case when o.concept = 'Transfer in date' then o.value_date end) as transfer_in_date,
    max(case when o.concept = 'Diagnosis' and o.value_coded = 'Trisomy 21' then o.value_coded end) as trisomy_21,
    max(case when o.concept = 'Type of Feed' and o.value_coded = 'Breast Milk' then o.value_coded end) as type_of_feed_breast_milk,
    max(case when o.concept = 'Type of Feed' and o.value_coded = 'Infant Formula' then o.value_coded end) as type_of_feed_infant_formula,
    max(case when o.concept = 'Type of Feed' and o.value_coded = 'Food Package' then o.value_coded end) as type_of_feed_solids,
    max(case when o.concept = 'Type of Feed' and o.value_coded = 'Mixed feeding' then o.value_coded end) as type_of_feed_mixed_feeding
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('PDC_INITIAL')
group by e.patient_id, e.encounter_date, e.location;