-- Derivation script for mw_pdc_other_diagnosis_followup
-- Generated from Pentaho transform: import-into-mw-pdc-other-diagnosis-followup.ktr

drop table if exists mw_pdc_other_diagnosis_followup;
create table mw_pdc_other_diagnosis_followup (
  pdc_other_diagnosis_visit_id 		int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  age_adjusted				int default null,
  age_non_adjusted			int default null,
  weight 				int default null,
  height				int default null,
  muac 					int default null,
  weight_against_age			int default null,
  weight_against_height			int default null,
  complications_since_last_visit	varchar(255) default null,
  malnutrition				varchar(255) default null,
  head_circumference			int default null,
  convulsions_any_since_last_visit	varchar(255) default null,
  anticonvulsant			varchar(255) default null,
  drug_and_dose				varchar(255) default null,
  adjust_dose				varchar(255) default null,
  poor_suck				varchar(255) default null,
  refs_to_feed				varchar(255) default null,
  less_feed_concerns			varchar(255) default null,
  individual_counseling			varchar(255) default null, 
  feeding_counseling			varchar(255) default null,
  group_counselling			varchar(255) default null,
  play_therapy				varchar(255) default null,
  continue_followup			varchar(255) default null,
  physiotherapy				varchar(255) default null,
  poser					varchar(255) default null,
  referred_out				varchar(255) default null,
  referred_out_specify			varchar(255) default null,
  if_referred_out			varchar(255) default null,
  if_referred_out_specify		varchar(255) default null,
  mdat					varchar(255) default null,
  clinical_plan			varchar(255) default null,
  next_appointment_date 		date default null,
  primary key (pdc_other_diagnosis_visit_id)
) ;

insert into mw_pdc_other_diagnosis_followup
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Adjust dose' then o.value_coded end) as adjust_dose,
    max(case when o.concept = 'Age of child' then o.value_numeric end) as age_adjusted,
    max(case when o.concept = 'Age' then o.value_numeric end) as age_non_adjusted,
    max(case when o.concept = 'Anticonvulsant' then o.value_coded end) as anticonvulsant,
    max(case when o.concept = 'Any since last visit' then o.value_coded end) as convulsions_any_since_last_visit,
    max(case when o.concept = 'Complications since last visit' then o.value_coded end) as complications_since_last_visit,
    max(case when o.concept = 'Continue followup' then o.value_coded end) as continue_followup,
    max(case when o.concept = 'Medications dispensed' then o.value_text end) as drug_and_dose,
    max(case when o.concept = 'Food supplement' then o.value_coded end) as feeding_Counseling,
    max(case when o.concept = 'Group Counselling' then o.value_coded end) as group_counselling,
    max(case when o.concept = 'Head circumference' then o.value_numeric end) as head_circumference,
    max(case when o.concept = 'Height (cm)' then o.value_numeric end) as height,
    max(case when o.concept = 'Referred out' then o.value_coded end) as if_referred_out,
    max(case when o.concept = 'Other non-coded (text)' then o.value_text end) as if_referred_out_specify,
    max(case when o.concept = 'Counseling' then o.value_coded end) as individual_counseling,
    max(case when o.concept = 'Less feed' then o.value_coded end) as less_feed_concerns,
    max(case when o.concept = 'Middle upper arm circumference (cm)' then o.value_numeric end) as muac,
    max(case when o.concept = 'Malawi Developmental Assessment Tool Summary (Normal)-(Coded)' then o.value_coded end) as mdat,
    max(case when o.concept = 'Wasting/malnutrition' then o.value_coded end) as malnutrition,
    max(case when o.concept = 'Appointment date' then o.value_date end) as next_appointment_date,
    max(case when o.concept = 'Poor Growth' then o.value_coded end) as poser,
    max(case when o.concept = 'Physiotherapy' then o.value_coded end) as physiotherapy,
    max(case when o.concept = 'Clinical impression comments' then o.value_text end) as clinical_plan,
    max(case when o.concept = 'Play therapy' then o.value_coded end) as play_therapy,
    max(case when o.concept = 'Poor Suck' then o.value_coded end) as poor_suck,
    max(case when o.concept = 'Referred out' then o.value_coded end) as referred_out,
    max(case when o.concept = 'Other non-coded (text)' then o.value_text end) as referred_out_specify,
    max(case when o.concept = 'Refs to feed' then o.value_coded end) as refs_to_feed,
    max(case when o.concept = 'Weight (kg)' then o.value_numeric end) as weight,
    max(case when o.concept = 'Numeric value or result' then o.value_numeric end) as weight_against_age,
    max(case when o.concept = 'Numeric value or result' then o.value_numeric end) as weight_against_height
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('PDC_OTHER_DIAGNOSIS_FOLLOWUP')
group by e.patient_id, e.encounter_date, e.location;