-- Derivation script for mw_poc
-- Generated from Pentaho transform: import-into-mw-poc.ktr

DROP TABLE IF EXISTS mw_poc;
CREATE TABLE mw_poc (
    poc_visit_id INT NOT NULL AUTO_INCREMENT,
    patient_id INT NOT NULL,
    visit_date DATE,
    location VARCHAR(255),
    sample_taken_for_viral_load VARCHAR(255),
    lower_than_detection_limit VARCHAR(255),
    reason_for_testing VARCHAR(255),
    lab_location VARCHAR(255),
    less_than_limit VARCHAR(255),
    reason_for_no_result VARCHAR(255),
    viral_load_sample_id VARCHAR(255),
    reason_for_no_sample VARCHAR(255),
    lab_id VARCHAR(255),
    symptom_present VARCHAR(255),
    symptom_absent VARCHAR(255),
    adherence_session_number VARCHAR(255),
    name_of_support_provider VARCHAR(255),
    number_of_missed_medication_doses_in_past_week VARCHAR(255),
    viral_load_counseling VARCHAR(255),
    medication_adherence_percent VARCHAR(255),
    adherence_counselling VARCHAR(255),
    date_of_blood_sample DATE,
    hiv_test_type VARCHAR(255),
    reason_for_no_sample_eid VARCHAR(255),
    result_of_hiv_test VARCHAR(255),
    hiv_test_time_period VARCHAR(255),
    age VARCHAR(13),
    units_of_age_of_child VARCHAR(255),
    lab_test_serial_number VARCHAR(255),
    date_of_returned_result VARCHAR(255),
    date_result_to_guardian DATE,
    reason_for_testing_coded VARCHAR(255),
    height DECIMAL(10,2),
    is_patient_preg VARCHAR(255),
    muac VARCHAR(255),
    weight DECIMAL(10,2),
    diastolic_blood_pressure DECIMAL(10,2),
    pulse DECIMAL(10,2),
    systolic_blood_pressure DECIMAL(10,2),
    result_of_hiv_test_htc VARCHAR(255),
    hiv_test_type_htc VARCHAR(255),
    colposcopy_of_cervix_with_acetic_acid VARCHAR(255),
    appointment_date DATE,
    qualitative_time VARCHAR(255),
    outcome VARCHAR(255),
    clinical_impression_comments VARCHAR(300),
    refer_to_screening_station VARCHAR(255),
    transfer_out_to VARCHAR(255),
    reason_to_stop_care VARCHAR(255),
    PRIMARY KEY (poc_visit_id)
);

INSERT INTO mw_poc
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Colposcopy of cervix with acetic acid' THEN o.value_coded END) as colposcopy_of_cervix_with_acetic_acid,
    MAX(CASE WHEN o.concept = 'Sample taken for Viral Load' THEN o.value_coded END) as sample_taken_for_viral_Load,
    MAX(CASE WHEN o.concept = 'Adherence counseling (coded)' THEN o.value_coded END) as adherence_counselling,
    MAX(CASE WHEN o.concept = 'Adherence session number' THEN o.value_coded END) as adherence_session_number,
    MAX(CASE WHEN o.concept = 'Age' THEN o.value_numeric END) as age,
    MAX(CASE WHEN o.concept = 'Appointment date' THEN o.value_date END) as appointment_date,
    MAX(CASE WHEN o.concept = 'Clinical impression comments' THEN o.value_text END) as clinical_impression_comments,
    MAX(CASE WHEN o.concept = 'Date of blood sample' THEN o.value_date END) as date_of_blood_sample,
    MAX(CASE WHEN o.concept = 'Date of returned result' THEN o.value_date END) as date_of_returned_result,
    MAX(CASE WHEN o.concept = 'Date result to guardian' THEN o.value_date END) as date_result_to_guardian,
    MAX(CASE WHEN o.concept = 'Diastolic blood pressure' THEN o.value_numeric END) as diastolic_blood_pressure,
    MAX(CASE WHEN o.concept = 'Height (cm)' THEN o.value_numeric END) as height,
    MAX(CASE WHEN o.concept = 'HIV test time period' THEN o.value_coded END) as hiv_test_time_period,
    MAX(CASE WHEN o.concept = 'HIV test type' THEN o.value_coded END) as hiv_test_type,
    MAX(CASE WHEN o.concept = 'HIV test type' THEN o.value_coded END) as hiv_test_type_htc,
    MAX(CASE WHEN o.concept = 'Lab ID' THEN o.value_text END) as lab_id,
    MAX(CASE WHEN o.concept = 'Location of laboratory' THEN o.value_coded END) as lab_location,
    MAX(CASE WHEN o.concept = 'Lab test serial number' THEN o.value_text END) as lab_test_serial_number,
    MAX(CASE WHEN o.concept = 'Less than limit' THEN o.value_numeric END) as less_than_limit,
    MAX(CASE WHEN o.concept = 'Lower than Detection limit' THEN o.value_coded END) as lower_than_detection_limit,
    MAX(CASE WHEN o.concept = 'Medication Adherence percent' THEN o.value_numeric END) as medication_adherence_percent,
    MAX(CASE WHEN o.concept = 'Middle upper arm circumference (cm)' THEN o.value_numeric END) as muac,
    MAX(CASE WHEN o.concept = 'Name of support provider' THEN o.value_text END) as name_of_support_provider,
    MAX(CASE WHEN o.concept = 'Number of missed medication doses in past 7 days' THEN o.value_numeric END) as number_of_missed_medication_doses_in_past_week,
    MAX(CASE WHEN o.concept = 'Outcome' THEN o.value_coded END) as outcome,
    MAX(CASE WHEN o.concept = 'Is patient pregnant?' THEN o.value_coded END) as is_patient_preg,
    MAX(CASE WHEN o.concept = 'Pulse' THEN o.value_numeric END) as pulse,
    MAX(CASE WHEN o.concept = 'Qualitative time' THEN o.value_coded END) as qualitative_time,
    MAX(CASE WHEN o.concept = 'Reason for no result' THEN o.value_coded END) as reason_for_no_result,
    MAX(CASE WHEN o.concept = 'Reason for no sample' THEN o.value_coded END) as reason_for_no_sample,
    MAX(CASE WHEN o.concept = 'Reason for no sample' THEN o.value_coded END) as reason_for_no_sample_eid,
    MAX(CASE WHEN o.concept = 'Reason for testing (coded)' THEN o.value_coded END) as reason_for_testing,
    MAX(CASE WHEN o.concept = 'Reason for testing (coded)' THEN o.value_coded END) as reason_for_testing_coded,
    MAX(CASE WHEN o.concept = 'Reason to stop care (text)' THEN o.value_text END) as reason_to_stop_care,
    MAX(CASE WHEN o.concept = 'Refer to screening station' THEN o.value_coded END) as refer_to_screening_station,
    MAX(CASE WHEN o.concept = 'Result of HIV test' THEN o.value_coded END) as result_of_hiv_test,
    MAX(CASE WHEN o.concept = 'Result of HIV test' THEN o.value_coded END) as result_of_hiv_test_htc,
    MAX(CASE WHEN o.concept = 'Viral Load Sample ID' THEN o.value_text END) as viral_load_sample_id,
    MAX(CASE WHEN o.concept = 'Symptom absent' THEN o.value_coded END) as symptom_absent,
    MAX(CASE WHEN o.concept = 'Symptom present' THEN o.value_coded END) as symptom_present,
    MAX(CASE WHEN o.concept = 'Systolic blood pressure' THEN o.value_numeric END) as systolic_blood_pressure,
    MAX(CASE WHEN o.concept = 'Transfer out to' THEN o.value_text END) as transfer_out_to,
    MAX(CASE WHEN o.concept = 'Units of age of child' THEN o.value_coded END) as units_of_age_of_child,
    MAX(CASE WHEN o.concept = 'Viral load counseling' THEN o.value_coded END) as viral_load_counseling,
    MAX(CASE WHEN o.concept = 'Weight (kg)' THEN o.value_numeric END) as weight
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('Check-in')
GROUP BY e.patient_id, e.encounter_date, e.location;