-- Derivation script for mw_teen_club_intake_survey
-- Generated from Pentaho transform: import-into-mw-teen-club-intake-survey.ktr

DROP TABLE IF EXISTS mw_teen_club_intake_survey;
CREATE TABLE mw_teen_club_intake_survey (
  teen_club_intake_surevy_visit_id int NOT NULL AUTO_INCREMENT,
  patient_id int NOT NULL,
  visit_date date DEFAULT NULL,
  location varchar(255) DEFAULT NULL,
  interview_date date DEFAULT NULL,
  interviewer_name varchar(255),
  village_name varchar(255),
  health_facility varchar(255),
  gender varchar(10),
  literate varchar(10),
  in_school varchar(10),
  dropout_class varchar(255),
  current_class varchar(255),
  plans_after_school varchar(255),
  primary_guardian varchar(255),
  parents_location varchar(255),
  staying_with_single_paren_reason varchar(255),
  num_of_household_members int,
  radio varchar(255),
  television varchar(255),
  mobile_phone varchar(255),
  fridge varchar(255),
  bicycle varchar(255),
  motorcycle varchar(255),
  animal_drawn_cart varchar(255),
  car varchar(255),
  source_of_lighting varchar(255),
  source_of_drinking_water varchar(255),
  toilet_at_home varchar(255),
  kind_of_toilet varchar(255),
  cooking_fuel varchar(255),
  type_of_house_floor varchar(255), 
  type_of_house_roof varchar(255), 
  enrolled_in_teen_club varchar(255),
  teen_club_purpose varchar(255),
  teen_club_activities varchar(255),
  teen_club_topics varchar(255),
  happy_with_teen_club varchar(255),
  social_support_from_teen_club varchar(255),
  kind_of_teen_club_social_support varchar(255),
  like_most varchar(255), 
  rate_social_support varchar(255),
  rate_changes_from_social_support varchar(255),
  challenges_in_daily_life varchar(255),
  can_a_healthy_person_have_hiv varchar(255),
  should_a_positive_student_be_allowed_at_your_school varchar(255),
  is_hiv_a_punishment varchar(255),
  is_hiv_bad_luck varchar(255), 
  can_an_hiv_person_live_longer varchar(255),
  are_people_afraid_to_be_around_you varchar(255),
  injectable_drugs varchar(255),
  ever_used_elicit_drugs varchar(255),
  have_sex_under_alcohol_influence varchar(255),
  have_sex_in_exchange_for_money varchar(255),
  have_sex_with_someone_older_or_younger varchar(255),
  have_you_started_thinking_about_your_future varchar(255),
  career_after_school varchar(255),
  area_of_study_interest varchar(255),
  involed_in_extra_curricular_activities varchar(255),
  extracurricular_activities varchar(255),
  careers_or_industries_interested varchar(255),
  have_role_models varchar(255),
  role_models varchar(255),
  what_kind_of_teen_club_support varchar(255),
  got_vocational_training varchar(255),
  what_do_you_want_to_do varchar(255),
  what_exactly_do_you_want_to_do varchar(255),
  staying_with_single_parent_reason varchar(255),
  can_hiv_be_cured varchar(255),
  how_is_hiv_prevented varchar(255),
  how_is_hiv_transmitted varchar(255),
  rate_your_hiv_knowledge varchar(255),
  PRIMARY KEY (teen_club_intake_surevy_visit_id)
);

INSERT INTO mw_teen_club_intake_survey
SELECT
    e.patient_id,
    DATE(e.encounter_date) as visit_date,
    e.location,
    MAX(CASE WHEN o.concept = 'Own an animal-drawn Cart' THEN o.value_coded END) as animal_drawn_cart,
    MAX(CASE WHEN o.concept = 'Answer for Teen Club Activities' THEN o.value_text END) as ans_teen_club_activities,
    MAX(CASE WHEN o.concept = 'Answer for Teens Club Purpose' THEN o.value_text END) as ans_teen_club_purpose,
    MAX(CASE WHEN o.concept = 'Answer for Teen Club Topics' THEN o.value_text END) as ans_teen_club_topics,
    MAX(CASE WHEN o.concept = 'Are people afraid to be around you?' THEN o.value_coded END) as are_people_afraid_to_be_around_you,
    MAX(CASE WHEN o.concept = 'What subjects or areas of study interest you the most?' THEN o.value_coded END) as area_of_study_interest,
    MAX(CASE WHEN o.concept = 'Own a bicycle' THEN o.value_coded END) as bicycle,
    MAX(CASE WHEN o.concept = 'Can a healthy-looking person have HIV infection?' THEN o.value_coded END) as can_a_healthy_person_have_hiv,
    MAX(CASE WHEN o.concept = 'Can an HIV infected person live longer?' THEN o.value_coded END) as can_an_hiv_person_live_longer,
    MAX(CASE WHEN o.concept = 'Can HIV/AIDS be cured?' THEN o.value_coded END) as can_hiv_be_cured,
    MAX(CASE WHEN o.concept = 'Own an car/truck' THEN o.value_coded END) as car,
    MAX(CASE WHEN o.concept = 'What career/job would you like to do when you finish school?' THEN o.value_text END) as career_after_school,
    MAX(CASE WHEN o.concept = 'Are there any specific careers or industries that you are curious about or would like to learn more about?' THEN o.value_coded END) as careers_or_industries_interested,
    MAX(CASE WHEN o.concept = 'Challenges you face in daily life' THEN o.value_text END) as challenges_in_daily_life,
    MAX(CASE WHEN o.concept = 'Fuel for household cooking' THEN o.value_coded END) as cooking_fuel,
    MAX(CASE WHEN o.concept = 'Current School class' THEN o.value_text END) as current_class,
    MAX(CASE WHEN o.concept = 'What you don' THEN o.value_text END) as like_most_at_teen_club,
    MAX(CASE WHEN o.concept = 'Dropped out School Class' THEN o.value_text END) as dropout_class,
    MAX(CASE WHEN o.concept = 'Enrolled in teen club' THEN o.value_coded END) as enrolled_in_teen_club,
    MAX(CASE WHEN o.concept = 'Have you ever used elicit drugs?' THEN o.value_coded END) as ever_used_elicit_drugs,
    MAX(CASE WHEN o.concept = 'Extracurricular activities' THEN o.value_text END) as extracurricular_activities,
    MAX(CASE WHEN o.concept = 'Own a refrigerator' THEN o.value_coded END) as fridge,
    MAX(CASE WHEN o.concept = 'Gender of contact' THEN o.value_coded END) as gender,
    MAX(CASE WHEN o.concept = 'Have you obtained any vocational training or certifications in your desired field?' THEN o.value_coded END) as got_vocational_training,
    MAX(CASE WHEN o.concept = 'Are you happy with teen club?' THEN o.value_coded END) as happy_with_teen_club,
    MAX(CASE WHEN o.concept = 'Are there any role models or professionals in your desired field that you look up to?' THEN o.value_coded END) as have_role_models,
    MAX(CASE WHEN o.concept = 'Did you have sex in exchange for money, goods or favor?' THEN o.value_coded END) as have_sex_in_exchange_for_money,
    MAX(CASE WHEN o.concept = 'Do you have sex when you' THEN o.value_coded END) as have_sex_under_alcohol_influence,
    MAX(CASE WHEN o.concept = 'Did you ever have sex with someone who is younger or you' THEN o.value_coded END) as have_sex_with_someone_older_or_younger,
    MAX(CASE WHEN o.concept = 'Have you started thinking about your future career and job aspirations?' THEN o.value_coded END) as have_you_started_thinking_about_your_future,
    MAX(CASE WHEN o.concept = 'Health facility name' THEN o.value_text END) as health_facility,
    MAX(CASE WHEN o.concept = 'How is HIV/AIDS prevented?' THEN o.value_coded END) as how_hiv_is_prevented,
    MAX(CASE WHEN o.concept = 'Answer for How HIV is transmitted' THEN o.value_text END) as how_hiv_is_transmitted,
    MAX(CASE WHEN o.concept = 'Are you in school?' THEN o.value_coded END) as in_school,
    MAX(CASE WHEN o.concept = 'Have you ever used injectable drugs?' THEN o.value_coded END) as injectable_drugs,
    MAX(CASE WHEN o.concept = 'Data collection date' THEN o.value_date END) as interview_date,
    MAX(CASE WHEN o.concept = 'Interviewer Name' THEN o.value_text END) as interviewer_name,
    MAX(CASE WHEN o.concept = 'Are you currently involved in any extracurricular activities or clubs related to your career interests?' THEN o.value_coded END) as involed_in_extra_curricular_activities,
    MAX(CASE WHEN o.concept = 'Is HIV a punishment for bad behaviour?' THEN o.value_coded END) as is_hiv_a_punishment,
    MAX(CASE WHEN o.concept = 'Is HIV just a matter of bad luck?' THEN o.value_coded END) as is_hiv_bad_luck,
    MAX(CASE WHEN o.concept = 'Answer for Kind of teen club support' THEN o.value_text END) as kind_of_teen_club_support,
    MAX(CASE WHEN o.concept = 'Answer for Kind of teen club support would you like to get' THEN o.value_text END) as kind_of_teen_club_support_you_would_like,
    MAX(CASE WHEN o.concept = 'Kind of toilet facility used by household members' THEN o.value_coded END) as kind_of_toilet,
    MAX(CASE WHEN o.concept = 'What you like most at teen club?' THEN o.value_text END) as like_most_at_teen_club,
    MAX(CASE WHEN o.concept = 'Literate' THEN o.value_coded END) as literate,
    MAX(CASE WHEN o.concept = 'Own a mobile telephone' THEN o.value_coded END) as mobile_phone,
    MAX(CASE WHEN o.concept = 'Own a motorcycle' THEN o.value_coded END) as motorcycle,
    MAX(CASE WHEN o.concept = 'Total number of household members' THEN o.value_numeric END) as num_of_household_members,
    MAX(CASE WHEN o.concept = 'Parents location' THEN o.value_text END) as parents_location,
    MAX(CASE WHEN o.concept = 'Plans after school' THEN o.value_coded END) as plans_after_school,
    MAX(CASE WHEN o.concept = 'Primary Guardian' THEN o.value_coded END) as primary_guardian,
    MAX(CASE WHEN o.concept = 'Own a radio' THEN o.value_coded END) as radio,
    MAX(CASE WHEN o.concept = 'Can you rate the changes that happened to your life from the social support a scale of 1 to 3?' THEN o.value_coded END) as rate_changes_from_social_support,
    MAX(CASE WHEN o.concept = 'How do you rate the support on a scale of 1 to 3?' THEN o.value_coded END) as rate_social_support,
    MAX(CASE WHEN o.concept = 'Rate your HIV knowledge' THEN o.value_coded END) as rate_your_hiv_knowledge,
    MAX(CASE WHEN o.concept = 'Reason for staying with single parent' THEN o.value_coded END) as staying_with_single_paren_reason,
    MAX(CASE WHEN o.concept = 'Name of role model(s)' THEN o.value_text END) as role_models,
    MAX(CASE WHEN o.concept = 'Can a healthy-looking person have HIV infection?' THEN o.value_coded END) as should_a_positive_student_be_allowed_at_your_school,
    MAX(CASE WHEN o.concept = 'Social support from teen club' THEN o.value_coded END) as social_support_from_teen_club,
    MAX(CASE WHEN o.concept = 'Main source of drinking water for household' THEN o.value_coded END) as source_of_drinking_water,
    MAX(CASE WHEN o.concept = 'Main energy source for household lighting' THEN o.value_coded END) as source_of_lighting,
    MAX(CASE WHEN o.concept = 'Own a Tv' THEN o.value_coded END) as tv,
    MAX(CASE WHEN o.concept = 'Do you have a toilet at home?' THEN o.value_coded END) as toilet_at_home,
    MAX(CASE WHEN o.concept = 'Type of house floor' THEN o.value_coded END) as type_of_house_floor,
    MAX(CASE WHEN o.concept = 'Type of house roof' THEN o.value_coded END) as type_of_house_roof,
    MAX(CASE WHEN o.concept = 'Village' THEN o.value_text END) as village_name,
    MAX(CASE WHEN o.concept = 'What courses or what do you want to do life?' THEN o.value_text END) as what_do_you_want_to_do,
    MAX(CASE WHEN o.concept = 'What exactly do you want to do in this life?' THEN o.value_text END) as what_exactly_do_you_want_to_do,
    MAX(CASE WHEN o.concept = 'Answer for Kind of teen club support would you like to get' THEN o.value_text END) as what_kind_of_teen_club_support
FROM omrs_encounter e
LEFT JOIN omrs_obs o ON o.encounter_id = e.encounter_id
WHERE e.encounter_type IN ('TEEN_CLUB_INTAKE_SURVEY')
GROUP BY e.patient_id, e.encounter_date, e.location;