-- Derivation script for mw_teen_club_intake_survey
-- Generated from Pentaho transform: import-into-mw-teen-club-intake-survey.ktr

drop table if exists mw_teen_club_intake_survey;
create table mw_teen_club_intake_survey (
  teen_club_intake_surevy_visit_id int not null auto_increment,
  patient_id int not null,
  visit_date date default null,
  location varchar(255) default null,
  interview_date date default null,
  interviewer_name varchar(255),
  village_name varchar(255),
  health_facility varchar(255),
  gender varchar(10),
  literate varchar(10),
  in_school varchar(10),
  dropout_class varchar(255),
  current_class varchar(255),
  plans_after_school varchar(255),
  primary_guardian varchar(255),
  parents_location varchar(255),
  staying_with_single_paren_reason varchar(255),
  num_of_household_members int,
  radio varchar(255),
  television varchar(255),
  mobile_phone varchar(255),
  fridge varchar(255),
  bicycle varchar(255),
  motorcycle varchar(255),
  animal_drawn_cart varchar(255),
  car varchar(255),
  source_of_lighting varchar(255),
  source_of_drinking_water varchar(255),
  toilet_at_home varchar(255),
  kind_of_toilet varchar(255),
  cooking_fuel varchar(255),
  type_of_house_floor varchar(255), 
  type_of_house_roof varchar(255), 
  enrolled_in_teen_club varchar(255),
  teen_club_purpose varchar(255),
  teen_club_activities varchar(255),
  teen_club_topics varchar(255),
  happy_with_teen_club varchar(255),
  social_support_from_teen_club varchar(255),
  kind_of_teen_club_social_support varchar(255),
  like_most varchar(255), 
  rate_social_support varchar(255),
  rate_changes_from_social_support varchar(255),
  challenges_in_daily_life varchar(255),
  can_a_healthy_person_have_hiv varchar(255),
  should_a_positive_student_be_allowed_at_your_school varchar(255),
  is_hiv_a_punishment varchar(255),
  is_hiv_bad_luck varchar(255), 
  can_an_hiv_person_live_longer varchar(255),
  are_people_afraid_to_be_around_you varchar(255),
  injectable_drugs varchar(255),
  ever_used_elicit_drugs varchar(255),
  have_sex_under_alcohol_influence varchar(255),
  have_sex_in_exchange_for_money varchar(255),
  have_sex_with_someone_older_or_younger varchar(255),
  have_you_started_thinking_about_your_future varchar(255),
  career_after_school varchar(255),
  area_of_study_interest varchar(255),
  involed_in_extra_curricular_activities varchar(255),
  extracurricular_activities varchar(255),
  careers_or_industries_interested varchar(255),
  have_role_models varchar(255),
  role_models varchar(255),
  what_kind_of_teen_club_support varchar(255),
  got_vocational_training varchar(255),
  what_do_you_want_to_do varchar(255),
  what_exactly_do_you_want_to_do varchar(255),
  staying_with_single_parent_reason varchar(255),
  can_hiv_be_cured varchar(255),
  how_is_hiv_prevented varchar(255),
  how_is_hiv_transmitted varchar(255),
  rate_your_hiv_knowledge varchar(255),
  primary key (teen_club_intake_surevy_visit_id)
);

insert into mw_teen_club_intake_survey
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    max(case when o.concept = 'Own an animal-drawn Cart' then o.value_coded end) as animal_drawn_cart,
    max(case when o.concept = 'Answer for Teen Club Activities' then o.value_text end) as ans_teen_club_activities,
    max(case when o.concept = 'Answer for Teens Club Purpose' then o.value_text end) as ans_teen_club_purpose,
    max(case when o.concept = 'Answer for Teen Club Topics' then o.value_text end) as ans_teen_club_topics,
    max(case when o.concept = 'Are people afraid to be around you?' then o.value_coded end) as are_people_afraid_to_be_around_you,
    max(case when o.concept = 'What subjects or areas of study interest you the most?' then o.value_coded end) as area_of_study_interest,
    max(case when o.concept = 'Own a bicycle' then o.value_coded end) as bicycle,
    max(case when o.concept = 'Can a healthy-looking person have HIV infection?' then o.value_coded end) as can_a_healthy_person_have_hiv,
    max(case when o.concept = 'Can an HIV infected person live longer?' then o.value_coded end) as can_an_hiv_person_live_longer,
    max(case when o.concept = 'Can HIV/AIDS be cured?' then o.value_coded end) as can_hiv_be_cured,
    max(case when o.concept = 'Own an car/truck' then o.value_coded end) as car,
    max(case when o.concept = 'What career/job would you like to do when you finish school?' then o.value_text end) as career_after_school,
    max(case when o.concept = 'Are there any specific careers or industries that you are curious about or would like to learn more about?' then o.value_coded end) as careers_or_industries_interested,
    max(case when o.concept = 'Challenges you face in daily life' then o.value_text end) as challenges_in_daily_life,
    max(case when o.concept = 'Fuel for household cooking' then o.value_coded end) as cooking_fuel,
    max(case when o.concept = 'Current School class' then o.value_text end) as current_class,
    max(case when o.concept = 'What you don' then o.value_text end) as like_most_at_teen_club,
    max(case when o.concept = 'Dropped out School Class' then o.value_text end) as dropout_class,
    max(case when o.concept = 'Enrolled in teen club' then o.value_coded end) as enrolled_in_teen_club,
    max(case when o.concept = 'Have you ever used elicit drugs?' then o.value_coded end) as ever_used_elicit_drugs,
    max(case when o.concept = 'Extracurricular activities' then o.value_text end) as extracurricular_activities,
    max(case when o.concept = 'Own a refrigerator' then o.value_coded end) as fridge,
    max(case when o.concept = 'Gender of contact' then o.value_coded end) as gender,
    max(case when o.concept = 'Have you obtained any vocational training or certifications in your desired field?' then o.value_coded end) as got_vocational_training,
    max(case when o.concept = 'Are you happy with teen club?' then o.value_coded end) as happy_with_teen_club,
    max(case when o.concept = 'Are there any role models or professionals in your desired field that you look up to?' then o.value_coded end) as have_role_models,
    max(case when o.concept = 'Did you have sex in exchange for money, goods or favor?' then o.value_coded end) as have_sex_in_exchange_for_money,
    max(case when o.concept = 'Do you have sex when you' then o.value_coded end) as have_sex_under_alcohol_influence,
    max(case when o.concept = 'Did you ever have sex with someone who is younger or you' then o.value_coded end) as have_sex_with_someone_older_or_younger,
    max(case when o.concept = 'Have you started thinking about your future career and job aspirations?' then o.value_coded end) as have_you_started_thinking_about_your_future,
    max(case when o.concept = 'Health facility name' then o.value_text end) as health_facility,
    max(case when o.concept = 'How is HIV/AIDS prevented?' then o.value_coded end) as how_hiv_is_prevented,
    max(case when o.concept = 'Answer for How HIV is transmitted' then o.value_text end) as how_hiv_is_transmitted,
    max(case when o.concept = 'Are you in school?' then o.value_coded end) as in_school,
    max(case when o.concept = 'Have you ever used injectable drugs?' then o.value_coded end) as injectable_drugs,
    max(case when o.concept = 'Data collection date' then o.value_date end) as interview_date,
    max(case when o.concept = 'Interviewer Name' then o.value_text end) as interviewer_name,
    max(case when o.concept = 'Are you currently involved in any extracurricular activities or clubs related to your career interests?' then o.value_coded end) as involed_in_extra_curricular_activities,
    max(case when o.concept = 'Is HIV a punishment for bad behaviour?' then o.value_coded end) as is_hiv_a_punishment,
    max(case when o.concept = 'Is HIV just a matter of bad luck?' then o.value_coded end) as is_hiv_bad_luck,
    max(case when o.concept = 'Answer for Kind of teen club support' then o.value_text end) as kind_of_teen_club_support,
    max(case when o.concept = 'Answer for Kind of teen club support would you like to get' then o.value_text end) as kind_of_teen_club_support_you_would_like,
    max(case when o.concept = 'Kind of toilet facility used by household members' then o.value_coded end) as kind_of_toilet,
    max(case when o.concept = 'What you like most at teen club?' then o.value_text end) as like_most_at_teen_club,
    max(case when o.concept = 'Literate' then o.value_coded end) as literate,
    max(case when o.concept = 'Own a mobile telephone' then o.value_coded end) as mobile_phone,
    max(case when o.concept = 'Own a motorcycle' then o.value_coded end) as motorcycle,
    max(case when o.concept = 'Total number of household members' then o.value_numeric end) as num_of_household_members,
    max(case when o.concept = 'Parents location' then o.value_text end) as parents_location,
    max(case when o.concept = 'Plans after school' then o.value_coded end) as plans_after_school,
    max(case when o.concept = 'Primary Guardian' then o.value_coded end) as primary_guardian,
    max(case when o.concept = 'Own a radio' then o.value_coded end) as radio,
    max(case when o.concept = 'Can you rate the changes that happened to your life from the social support a scale of 1 to 3?' then o.value_coded end) as rate_changes_from_social_support,
    max(case when o.concept = 'How do you rate the support on a scale of 1 to 3?' then o.value_coded end) as rate_social_support,
    max(case when o.concept = 'Rate your HIV knowledge' then o.value_coded end) as rate_your_hiv_knowledge,
    max(case when o.concept = 'Reason for staying with single parent' then o.value_coded end) as staying_with_single_paren_reason,
    max(case when o.concept = 'Name of role model(s)' then o.value_text end) as role_models,
    max(case when o.concept = 'Can a healthy-looking person have HIV infection?' then o.value_coded end) as should_a_positive_student_be_allowed_at_your_school,
    max(case when o.concept = 'Social support from teen club' then o.value_coded end) as social_support_from_teen_club,
    max(case when o.concept = 'Main source of drinking water for household' then o.value_coded end) as source_of_drinking_water,
    max(case when o.concept = 'Main energy source for household lighting' then o.value_coded end) as source_of_lighting,
    max(case when o.concept = 'Own a Tv' then o.value_coded end) as tv,
    max(case when o.concept = 'Do you have a toilet at home?' then o.value_coded end) as toilet_at_home,
    max(case when o.concept = 'Type of house floor' then o.value_coded end) as type_of_house_floor,
    max(case when o.concept = 'Type of house roof' then o.value_coded end) as type_of_house_roof,
    max(case when o.concept = 'Village' then o.value_text end) as village_name,
    max(case when o.concept = 'What courses or what do you want to do life?' then o.value_text end) as what_do_you_want_to_do,
    max(case when o.concept = 'What exactly do you want to do in this life?' then o.value_text end) as what_exactly_do_you_want_to_do,
    max(case when o.concept = 'Answer for Kind of teen club support would you like to get' then o.value_text end) as what_kind_of_teen_club_support
from omrs_encounter e
left join omrs_obs o on o.encounter_id = e.encounter_id
where e.encounter_type in ('TEEN_CLUB_INTAKE_SURVEY')
group by e.patient_id, e.encounter_date, e.location;