-- Derivation script for mw_teen_club_intake_survey
-- Generated from Pentaho transform: import-into-mw-teen-club-intake-survey.ktr

drop table if exists mw_teen_club_intake_survey;
create table mw_teen_club_intake_survey (
  teen_club_intake_surevy_visit_id int not null auto_increment,
  patient_id int not null,
  visit_date date default null,
  location varchar(255) default null,
  interview_date date default null,
  interviewer_name varchar(255),
  village_name varchar(255),
  health_facility varchar(255),
  gender varchar(10),
  literate varchar(10),
  in_school varchar(10),
  dropout_class varchar(255),
  current_class varchar(255),
  plans_after_school varchar(255),
  primary_guardian varchar(255),
  parents_location varchar(255),
  staying_with_single_paren_reason varchar(255),
  num_of_household_members int,
  radio varchar(255),
  television varchar(255),
  mobile_phone varchar(255),
  fridge varchar(255),
  bicycle varchar(255),
  motorcycle varchar(255),
  animal_drawn_cart varchar(255),
  car varchar(255),
  source_of_lighting varchar(255),
  source_of_drinking_water varchar(255),
  toilet_at_home varchar(255),
  kind_of_toilet varchar(255),
  cooking_fuel varchar(255),
  type_of_house_floor varchar(255),
  type_of_house_roof varchar(255),
  enrolled_in_teen_club varchar(255),
  teen_club_purpose varchar(255),
  teen_club_activities varchar(255),
  teen_club_topics varchar(255),
  happy_with_teen_club varchar(255),
  social_support_from_teen_club varchar(255),
  kind_of_teen_club_social_support varchar(255),
  like_most varchar(255),
  rate_social_support varchar(255),
  rate_changes_from_social_support varchar(255),
  challenges_in_daily_life varchar(255),
  can_a_healthy_person_have_hiv varchar(255),
  should_a_positive_student_be_allowed_at_your_school varchar(255),
  is_hiv_a_punishment varchar(255),
  is_hiv_bad_luck varchar(255),
  can_an_hiv_person_live_longer varchar(255),
  are_people_afraid_to_be_around_you varchar(255),
  injectable_drugs varchar(255),
  ever_used_elicit_drugs varchar(255),
  have_sex_under_alcohol_influence varchar(255),
  have_sex_in_exchange_for_money varchar(255),
  have_sex_with_someone_older_or_younger varchar(255),
  have_you_started_thinking_about_your_future varchar(255),
  career_after_school varchar(255),
  area_of_study_interest varchar(255),
  involed_in_extra_curricular_activities varchar(255),
  extracurricular_activities varchar(255),
  careers_or_industries_interested varchar(255),
  have_role_models varchar(255),
  role_models varchar(255),
  what_kind_of_teen_club_support varchar(255),
  got_vocational_training varchar(255),
  what_do_you_want_to_do varchar(255),
  what_exactly_do_you_want_to_do varchar(255),
  staying_with_single_parent_reason varchar(255),
  can_hiv_be_cured varchar(255),
  how_is_hiv_prevented varchar(255),
  how_is_hiv_transmitted varchar(255),
  rate_your_hiv_knowledge varchar(255),
  primary key (teen_club_intake_surevy_visit_id)
);

drop temporary table if exists temp_teen_club_obs;
create temporary table temp_teen_club_obs as
select encounter_id, obs_group_id, concept, value_coded, value_numeric, value_date, value_text
from omrs_obs
where encounter_type = 'TEEN_CLUB_INTAKE_SURVEY';
alter table temp_teen_club_obs add index temp_teen_club_obs_concept_idx (concept);
alter table temp_teen_club_obs add index temp_teen_club_obs_encounter_idx (encounter_id);
alter table temp_teen_club_obs add index temp_teen_club_obs_group_idx (obs_group_id);

drop temporary table if exists temp_single_values;
create temporary table temp_single_values as
select
    encounter_id,
    max(case when concept = 'Own an animal-drawn Cart'                                                                                                then value_coded   end) as animal_drawn_cart,
    max(case when concept = 'Answer for Teen Club Activities'                                                                                         then value_text    end) as teen_club_activities,
    max(case when concept = 'Answer for Teens Club Purpose'                                                                                           then value_text    end) as teen_club_purpose,
    max(case when concept = 'Answer for Teen Club Topics'                                                                                             then value_text    end) as teen_club_topics,
    max(case when concept = 'Are people afraid to be around you?'                                                                                     then value_coded   end) as are_people_afraid_to_be_around_you,
    max(case when concept = 'What subjects or areas of study interest you the most?'                                                                  then value_coded   end) as area_of_study_interest,
    max(case when concept = 'Own a bicycle'                                                                                                           then value_coded   end) as bicycle,
    max(case when concept = 'Can a healthy-looking person have HIV infection?'                                                                        then value_coded   end) as can_a_healthy_person_have_hiv,
    max(case when concept = 'Can an HIV infected person live longer?'                                                                                 then value_coded   end) as can_an_hiv_person_live_longer,
    max(case when concept = 'Can HIV/AIDS be cured?'                                                                                                  then value_coded   end) as can_hiv_be_cured,
    max(case when concept = 'Own an car/truck'                                                                                                        then value_coded   end) as car,
    max(case when concept = 'What career/job would you like to do when you finish school?'                                                            then value_text    end) as career_after_school,
    max(case when concept = 'Are there any specific careers or industries that you are curious about or would like to learn more about?'              then value_coded   end) as careers_or_industries_interested,
    max(case when concept = 'Challenges you face in daily life'                                                                                       then value_text    end) as challenges_in_daily_life,
    max(case when concept = 'Fuel for household cooking'                                                                                              then value_coded   end) as cooking_fuel,
    max(case when concept = 'Current School class'                                                                                                    then value_text    end) as current_class,
    max(case when concept = 'Dropped out School Class'                                                                                                then value_text    end) as dropout_class,
    max(case when concept = 'Enrolled in teen club'                                                                                                   then value_coded   end) as enrolled_in_teen_club,
    max(case when concept = 'Have you ever used elicit drugs?'                                                                                        then value_coded   end) as ever_used_elicit_drugs,
    max(case when concept = 'Extracurricular activities'                                                                                              then value_text    end) as extracurricular_activities,
    max(case when concept = 'Own a refrigerator'                                                                                                      then value_coded   end) as fridge,
    max(case when concept = 'Gender of contact'                                                                                                       then value_coded   end) as gender,
    max(case when concept = 'Have you obtained any vocational training or certifications in your desired field?'                                      then value_coded   end) as got_vocational_training,
    max(case when concept = 'Are you happy with teen club?'                                                                                           then value_coded   end) as happy_with_teen_club,
    max(case when concept = 'Are there any role models or professionals in your desired field that you look up to?'                                   then value_coded   end) as have_role_models,
    max(case when concept = 'Did you have sex in exchange for money, goods or favor?'                                                                 then value_coded   end) as have_sex_in_exchange_for_money,
    max(case when concept = 'Do you have sex when you'                                                                                                then value_coded   end) as have_sex_under_alcohol_influence,
    max(case when concept = 'Did you ever have sex with someone who is younger or you'                                                                then value_coded   end) as have_sex_with_someone_older_or_younger,
    max(case when concept = 'Have you started thinking about your future career and job aspirations?'                                                 then value_coded   end) as have_you_started_thinking_about_your_future,
    max(case when concept = 'Health facility name'                                                                                                    then value_text    end) as health_facility,
    max(case when concept = 'How is HIV/AIDS prevented?'                                                                                              then value_coded   end) as how_is_hiv_prevented,
    max(case when concept = 'Answer for How HIV is transmitted'                                                                                       then value_text    end) as how_is_hiv_transmitted,
    max(case when concept = 'Are you in school?'                                                                                                      then value_coded   end) as in_school,
    max(case when concept = 'Have you ever used injectable drugs?'                                                                                    then value_coded   end) as injectable_drugs,
    max(case when concept = 'Data collection date'                                                                                                    then value_date    end) as interview_date,
    max(case when concept = 'Interviewer Name'                                                                                                        then value_text    end) as interviewer_name,
    max(case when concept = 'Are you currently involved in any extracurricular activities or clubs related to your career interests?'                 then value_coded   end) as involed_in_extra_curricular_activities,
    max(case when concept = 'Is HIV a punishment for bad behaviour?'                                                                                  then value_coded   end) as is_hiv_a_punishment,
    max(case when concept = 'Is HIV just a matter of bad luck?'                                                                                       then value_coded   end) as is_hiv_bad_luck,
    max(case when concept = 'Answer for Kind of teen club support'                                                                                    then value_text    end) as kind_of_teen_club_social_support,
    max(case when concept = 'Answer for Kind of teen club support would you like to get'                                                              then value_text    end) as what_kind_of_teen_club_support,
    max(case when concept = 'Kind of toilet facility used by household members'                                                                       then value_coded   end) as kind_of_toilet,
    max(case when concept = 'What you like most at teen club?'                                                                                        then value_text    end) as like_most,
    max(case when concept = 'Literate'                                                                                                                then value_coded   end) as literate,
    max(case when concept = 'Own a mobile telephone'                                                                                                  then value_coded   end) as mobile_phone,
    max(case when concept = 'Own a motorcycle'                                                                                                        then value_coded   end) as motorcycle,
    max(case when concept = 'Total number of household members'                                                                                       then value_numeric end) as num_of_household_members,
    max(case when concept = 'Parents location'                                                                                                        then value_text    end) as parents_location,
    max(case when concept = 'Plans after school'                                                                                                      then value_coded   end) as plans_after_school,
    max(case when concept = 'Primary Guardian'                                                                                                        then value_coded   end) as primary_guardian,
    max(case when concept = 'Own a radio'                                                                                                             then value_coded   end) as radio,
    max(case when concept = 'Can you rate the changes that happened to your life from the social support a scale of 1 to 3?'                         then value_coded   end) as rate_changes_from_social_support,
    max(case when concept = 'How do you rate the support on a scale of 1 to 3?'                                                                      then value_coded   end) as rate_social_support,
    max(case when concept = 'Rate your HIV knowledge'                                                                                                 then value_coded   end) as rate_your_hiv_knowledge,
    max(case when concept = 'Reason for staying with single parent'                                                                                   then value_coded   end) as staying_with_single_paren_reason,
    max(case when concept = 'Name of role model(s)'                                                                                                   then value_text    end) as role_models,
    max(case when concept = 'Social support from teen club'                                                                                           then value_coded   end) as social_support_from_teen_club,
    max(case when concept = 'Main source of drinking water for household'                                                                             then value_coded   end) as source_of_drinking_water,
    max(case when concept = 'Main energy source for household lighting'                                                                               then value_coded   end) as source_of_lighting,
    max(case when concept = 'Own a Tv'                                                                                                                then value_coded   end) as television,
    max(case when concept = 'Do you have a toilet at home?'                                                                                           then value_coded   end) as toilet_at_home,
    max(case when concept = 'Type of house floor'                                                                                                     then value_coded   end) as type_of_house_floor,
    max(case when concept = 'Type of house roof'                                                                                                      then value_coded   end) as type_of_house_roof,
    max(case when concept = 'Village'                                                                                                                 then value_text    end) as village_name,
    max(case when concept = 'What courses or what do you want to do life?'                                                                            then value_text    end) as what_do_you_want_to_do,
    max(case when concept = 'What exactly do you want to do in this life?'                                                                            then value_text    end) as what_exactly_do_you_want_to_do
from temp_teen_club_obs
group by encounter_id;
alter table temp_single_values add index temp_single_values_encounter_idx (encounter_id);

insert into mw_teen_club_intake_survey (patient_id, visit_date, location, animal_drawn_cart, teen_club_activities, teen_club_purpose, teen_club_topics, are_people_afraid_to_be_around_you, area_of_study_interest, bicycle, can_a_healthy_person_have_hiv, can_an_hiv_person_live_longer, can_hiv_be_cured, car, career_after_school, careers_or_industries_interested, challenges_in_daily_life, cooking_fuel, current_class, like_most, dropout_class, enrolled_in_teen_club, ever_used_elicit_drugs, extracurricular_activities, fridge, gender, got_vocational_training, happy_with_teen_club, have_role_models, have_sex_in_exchange_for_money, have_sex_under_alcohol_influence, have_sex_with_someone_older_or_younger, have_you_started_thinking_about_your_future, health_facility, how_is_hiv_prevented, how_is_hiv_transmitted, in_school, injectable_drugs, interview_date, interviewer_name, involed_in_extra_curricular_activities, is_hiv_a_punishment, is_hiv_bad_luck, kind_of_teen_club_social_support, what_kind_of_teen_club_support, kind_of_toilet, literate, mobile_phone, motorcycle, num_of_household_members, parents_location, plans_after_school, primary_guardian, radio, rate_changes_from_social_support, rate_social_support, rate_your_hiv_knowledge, staying_with_single_paren_reason, role_models, should_a_positive_student_be_allowed_at_your_school, social_support_from_teen_club, source_of_drinking_water, source_of_lighting, television, toilet_at_home, type_of_house_floor, type_of_house_roof, village_name, what_do_you_want_to_do, what_exactly_do_you_want_to_do)
select
    e.patient_id,
    date(e.encounter_date) as visit_date,
    e.location,
    sv.animal_drawn_cart,
    sv.teen_club_activities,
    sv.teen_club_purpose,
    sv.teen_club_topics,
    sv.are_people_afraid_to_be_around_you,
    sv.area_of_study_interest,
    sv.bicycle,
    sv.can_a_healthy_person_have_hiv,
    sv.can_an_hiv_person_live_longer,
    sv.can_hiv_be_cured,
    sv.car,
    sv.career_after_school,
    sv.careers_or_industries_interested,
    sv.challenges_in_daily_life,
    sv.cooking_fuel,
    sv.current_class,
    sv.like_most,
    sv.dropout_class,
    sv.enrolled_in_teen_club,
    sv.ever_used_elicit_drugs,
    sv.extracurricular_activities,
    sv.fridge,
    sv.gender,
    sv.got_vocational_training,
    sv.happy_with_teen_club,
    sv.have_role_models,
    sv.have_sex_in_exchange_for_money,
    sv.have_sex_under_alcohol_influence,
    sv.have_sex_with_someone_older_or_younger,
    sv.have_you_started_thinking_about_your_future,
    sv.health_facility,
    sv.how_is_hiv_prevented,
    sv.how_is_hiv_transmitted,
    sv.in_school,
    sv.injectable_drugs,
    sv.interview_date,
    sv.interviewer_name,
    sv.involed_in_extra_curricular_activities,
    sv.is_hiv_a_punishment,
    sv.is_hiv_bad_luck,
    sv.kind_of_teen_club_social_support,
    sv.what_kind_of_teen_club_support,
    sv.kind_of_toilet,
    sv.literate,
    sv.mobile_phone,
    sv.motorcycle,
    sv.num_of_household_members,
    sv.parents_location,
    sv.plans_after_school,
    sv.primary_guardian,
    sv.radio,
    sv.rate_changes_from_social_support,
    sv.rate_social_support,
    sv.rate_your_hiv_knowledge,
    sv.staying_with_single_paren_reason,
    sv.role_models,
    sv.can_a_healthy_person_have_hiv,
    sv.social_support_from_teen_club,
    sv.source_of_drinking_water,
    sv.source_of_lighting,
    sv.television,
    sv.toilet_at_home,
    sv.type_of_house_floor,
    sv.type_of_house_roof,
    sv.village_name,
    sv.what_do_you_want_to_do,
    sv.what_exactly_do_you_want_to_do
from omrs_encounter e
left join temp_single_values sv on sv.encounter_id = e.encounter_id
where e.encounter_type in ('TEEN_CLUB_INTAKE_SURVEY')
group by e.patient_id, e.encounter_date, e.location;

drop temporary table if exists temp_teen_club_obs;
drop temporary table if exists temp_single_values;
