create table mw_art_initial (
  art_initial_visit_id 			int not null auto_increment,
  patient_id    				int not null,
  visit_date            			date,
  location              			varchar(255),
  who_clinical_conditions 			varchar(255),
  clinical_stage 				varchar(255),
  presumed_hiv_severe_present			varchar(255),
  tb_status 					varchar(255),
  cd4_count					int,
  cd4_percentage				decimal(6,2),
  ks_side_effects_worsening_on_arvs  		varchar(255),
  cd4_date					date,
  link_id                                       varchar(255),
  tb_xpert                                      varchar(255),
  tb_xpert_date                                 date,
  urine_lam                                     varchar(255),
  urine_lam_date                                date,
  crag_results                                  varchar(255),
  crag_test_date                                date,
  pregnant_or_lactating			varchar(255),
  height					decimal(10,2),
  weight					decimal(10,2),
  ever_taken_arvs				varchar(255),
  age_at_initiation				int,
  last_arvs_taken				varchar(255),
  last_arvs_taken_date				varchar(255),
  confirmatory_test_location   		varchar(255),
  confirmatory_test_date			date,
  confirmatory_test_type 			varchar(255),
  art_education_done				varchar(255),
  art_education_date				date,
  tb_registration_number			varchar(255),
  tb_treatment_start_date			date,
  art_first_line_regimen			varchar(255),
  art_first_line_regimen_start_date		date,
  art_alternative_first_line_regimen		varchar(255),
  art_alternative_first_line_regimen_date	date,
  art_second_line_regimen			varchar(255),
  art_second_line_regimen_start_date		date,
  transfer_in_date				date,
  child_hcc_no					varchar(255),
     primary key (art_initial_visit_id)
);
