create table mw_asthma_initial (
  asthma_initial_visit_id 		int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  diagnosis_asthma 			varchar(255) default null,
  diagnosis_date_asthma 		date default null,
  diagnosis_copd 			varchar(255) default null,
  diagnosis_date_copd 			date default null,
  family_history_asthma 		varchar(255) default null,
  family_history_copd 			varchar(255) default null,
  hiv_status 				varchar(255) default null,
  hiv_test_date 			date default null,
  art_start_date 			date default null,
  tb_status 				varchar(255) default null,
  tb_year 				int default null,
  chronic_dry_cough 			varchar(255) default null,
  chronic_dry_cough_duration_in_months int default null,
  chronic_dry_cough_age_at_onset 	int default null,
  tb_contact 				varchar(255) default null,
  tb_contact_date 			date default null,
  cooking_indoor 			varchar(255) default null,
  smoking_history 			varchar(255) default null,
  last_smoking_history_date 		date default null,
  second_hand_smoking 			varchar(255) default null,
  second_hand_smoking_date 		date default null,
  occupation 				varchar(255) default null,
  occupation_exposure 			varchar(255) default null,
  occupation_exposure_date 		date default null,
  primary key (asthma_initial_visit_id)
);
