create table mw_asthma_followup (
  asthma_followup_visit_id 		int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  planned_visit 			varchar(255) default null,
  height 				int default null,
  weight 				int default null,
  day_symptoms 			int default null,
  night_symptoms 			int default null,
  inhaler_use_frequency_daily 	int default null,
  inhaler_use_frequency_weekly 	int default null,
  inhaler_use_frequency_monthly 	int default null,
  inhaler_use_frequency_yearly 	int default null,
  steroid_inhaler_daily 		varchar(255) default null,
  number_of_cigarettes_per_day 	int default null,
  passive_smoking 			varchar(255) default null,
  cooking_indoor 			varchar(255) default null,
  exacerbation_today 			varchar(255) default null,
  asthma_severity 			varchar(255) default null,
  copd 				varchar(255) default null,
  other_diagnosis 			varchar(255) default null,
  treatment_inhaled_b_agonist 	varchar(255) default null,
  treatment_inhaled_b_agonist_dose		int,
  treatment_inhaled_b_agonist_dosing_unit varchar(50),
  treatment_inhaled_b_agonist_route		varchar(50),
  treatment_inhaled_b_agonist_frequency		varchar(50),
  treatment_inhaled_b_agonist_duration   int,
  treatment_inhaled_b_agonist_duration_units  varchar(50),
  treatment_inhaled_steriod 		varchar(255) default null,
  treatment_inhaled_steriod_dose		int,
  treatment_inhaled_steriod_dosing_unit varchar(50),
  treatment_inhaled_steriod_route		varchar(50),
  treatment_inhaled_steriod_frequency		varchar(50),
  treatment_inhaled_steriod_duration   int,
  treatment_inhaled_steriod_duration_units  varchar(50),
  treatment_oral_steroid 		varchar(255) default null,
  treatment_oral_steroid_dose		int,
  treatment_oral_steroid_dosing_unit varchar(50),
  treatment_oral_steroid_route		varchar(50),
  treatment_oral_steroid_frequency		varchar(50),
  treatment_oral_steroid_duration   int,
  treatment_oral_steroid_duration_units  varchar(50),
  other_treatment 			varchar(255) default null,
  other_treatment_dose		int,
  other_treatment_dosing_unit varchar(50),
  other_treatment_route		varchar(50),
  other_treatment_frequency		varchar(50),
  other_treatment_duration   int,
  other_treatment_duration_units  varchar(50),
  comments 				varchar(255) default null,
  next_appointment_date		date,
  primary key (asthma_followup_visit_id)
);
