
create table mw_art_followup (
  art_followup_visit_id 			int not null auto_increment,
  patient_id    				int not null,
  visit_date            			date,
  location              			varchar(255),
  next_appointment_date 			date,
  art_drugs_received 				varchar(255),
  pregnant_or_lactating			varchar(255),
  tb_status 					varchar(255),
  doses_missed					decimal(10,2),
  pill_count					int,
  no_side_effect				varchar(255),
  peripheral_neuropathy_side_effect		varchar(255),
  hepatitis_side_effect			varchar(255),
  skin_rash_side_effect			varchar(255),
  lipodystrophy_side_effect			varchar(255),
  other_side_effect				varchar(255),
  art_regimen					varchar(255),
  height					decimal(10,2),
  weight					decimal(10,2),
  arvs_given					int,
  arvs_given_to				varchar(255),
  ctx_960					varchar(255),
  ctx_960_pills		     		decimal(10,2),
  inh_300					varchar(255),
  inh_300_pills		     		decimal(10,2),
  rfp_150					varchar(255),
  rfp_150_pills		     		decimal(10,2),
  rfp_inh					varchar(255),
  rfp_inh_pills				decimal(10,2),
  pyridoxine					varchar(255),
  pyridoxine_pills		     		decimal(10,2),
  depo_given					varchar(255),
  systolic_bp		 			varchar(255),
  diastolic_bp					varchar(255),
  condoms_given				varchar(255),
     primary key (art_followup_visit_id)
);

