create table mw_chf_followup (
  chf_followup_visit_id 			int not null auto_increment,
  patient_id 					int not null,
  visit_date 					date default null,
  location 					varchar(50) default null,
  height 					int default null,	
  weight 					int default null,
  weight_change 				varchar(50) default null,
  bp_systolic 					int default null,
  bp_diastolic 				int default null,
  heart_rate 					int default null,
  spo2 					int default null,
  orthopnea 					varchar(50) default null,
  dyspnea_on_exertion 				varchar(50) default null,
  dry_cough 					varchar(50) default null,
  fatigue			 		varchar(50) default null,
  hospitalized_since_last_visit_for_ncd 	varchar(50) default null,
  oedema 					varchar(50) default null,
  bibasilar_crackles 				varchar(50) default null,
  jvp_elevated 				varchar(50) default null,
  volume_status 				varchar(50) default null,
  nyha_stage 					varchar(50) default null,
  alcohol 					varchar(50) default null,
  tobacco 					varchar(50) default null,
  salt_or_fluid_restricted 			varchar(50) default null,
  concern_for_depression_or_anxiety 		varchar(50) default null,
  aspirin 					varchar(50) default null,
  asprin_asa_dose		int,
  asprin_asa_dosing_unit varchar(50),
  asprin_asa_route		varchar(50),
  asprin_asa_frequency		varchar(50),
  asprin_asa_duration   int,
  asprin_asa_duration_units  varchar(50),
  diuretic_hctz 				varchar(50) default null,
  diuretic_hctz_dose		int,
  diuretic_hctz_dosing_unit varchar(50),
  diuretic_hctz_route		varchar(50),
  diuretic_hctz_frequency		varchar(50),
  diuretic_hctz_duration   int,
  diuretic_hctz_duration_units  varchar(50),
  diuretic_furo 				varchar(50) default null,
  diuretic_furp_dose		int,
  diuretic_furp_dosing_unit varchar(50),
  diuretic_furp_route		varchar(50),
  diuretic_furp_frequency		varchar(50),
  diuretic_furp_duration   int,
  diuretic_furp_duration_units  varchar(50),
  diuretic_spiro			 			varchar(50),
  diuretic_spiro_dose		int,
  diuretic_spiro_dosing_unit varchar(50),
  diuretic_spiro_route		varchar(50),
  diuretic_spiro_frequency		varchar(50),
  diuretic_spiro_duration   int,
  diuretic_spiro_duration_units  varchar(50),
  ace_i_enal				 			varchar(50),
  ace_i_enal_dose		int,
  ace_i_enal_dosing_unit varchar(50),
  ace_i_enal_route		varchar(50),
  ace_i_enal_frequency		varchar(50),
  ace_i_enal_duration   int,
  ace_i_enal_duration_units  varchar(50),
  ace_i_capt				 			varchar(50),
  ace_i_capt_dose		int,
  ace_i_capt_dosing_unit varchar(50),
  ace_i_capt_route		varchar(50),
  ace_i_capt_frequency		varchar(50),
  ace_i_capt_duration   int,
  ace_i_capt_duration_units  varchar(50),
  ace_i_lisin			 				varchar(50),
  ace_i_lisin_dose		int,
  ace_i_lisin_dosing_unit varchar(50),
  ace_i_lisin_route		varchar(50),
  ace_i_lisin_frequency		varchar(50),
  ace_i_lisin_duration   int,
  ace_i_lisin_duration_units  varchar(50),
  bb_aten				 			varchar(50),
  bb_aten_dose		int,
  bb_aten_dosing_unit varchar(50),
  bb_aten_route		varchar(50),
  bb_aten_frequency		varchar(50),
  bb_aten_duration   int,
  bb_aten_duration_units  varchar(50),
  bb_bis				 			varchar(50),
  bb_bis_dose		int,
  bb_bis_dosing_unit varchar(50),
  bb_bis_route		varchar(50),
  bb_bis_frequency		varchar(50),
  bb_bis_duration   int,
  bb_bis_duration_units  varchar(50),
  bb_prop				 			varchar(50),
  bb_prop_dose		int,
  bb_prop_dosing_unit varchar(50),
  bb_prop_route		varchar(50),
  bb_prop_frequency		varchar(50),
  bb_prop_duration   int,
  bb_prop_duration_units  varchar(50),
  ccb_aml				 			varchar(50),
  ccb_aml_dose		int,
  ccb_aml_dosing_unit varchar(50),
  ccb_aml_route		varchar(50),
  ccb_aml_frequency		varchar(50),
  ccb_aml_duration   int,
  ccb_aml_duration_units  varchar(50),
  ccb_nif				 			varchar(50),
  ccb_nif_dose		int,
  ccb_nif_dosing_unit varchar(50),
  ccb_nif_route		varchar(50),
  ccb_nif_frequency		varchar(50),
  ccb_nif_duration   int,
  ccb_nif_duration_units  varchar(50),
  benzathine 					varchar(50) default null,
  benzathine_dose		int,
  benzathine_dosing_unit varchar(50),
  benzathine_route		varchar(50),
  benzathine_frequency		varchar(50),
  benzathine_duration   int,
  benzathine_duration_units  varchar(50),
  other_medications 				varchar(50) default null,
  took_medications_today 			varchar(50) default null,
  diet_salt_or_fluid 				varchar(50) default null,
  mental_health_referral 			varchar(50) default null,
  palliative_referral 				varchar(50) default null,
  request_chw_f_u 				varchar(50) default null,
  next_appointment_date 			date default null,
  primary key (chf_followup_visit_id)
) ;
