create table mw_ckd_initial (
  ckd_initial_visit_id int not null auto_increment,
  patient_id int not null,
  visit_date date default null,
  location varchar(255) default null,
  presumed_etiology_hypertension varchar(255) default null,
  presumed_etiology_diabetes varchar(255) default null,
  presumed_etiology_hiv varchar(255) default null,
  presumed_etiology_nephrotic varchar(255) default null,
  presumed_etiology_drugs varchar(255) default null,
  presumed_etiology_other varchar(255) default null,
  presumed_etiology_other_2 varchar(255) default null,
  presumed_etiology_unknown varchar(255) default null,
  presumed_etiology_diagnosis_date date default null,
  diagnosis_chf varchar(255) default null,
  diagnosis_date_chf date default null,
  diagnosis_hypertension varchar(255) default null,
  diagnosis_date_hypertension date default null,
  diagnosis_diabetes varchar(255) default null,
  diagnosis_date_diabetes date default null,
  diagnosis_other varchar(255) default null,
  diagnosis_date_other date default null,
  hiv_status varchar(255) default null,
  hiv_test_date date default null,
  art_start_date date default null,
  tb_status varchar(255) default null,
  tb_date date default null,
  history_of_dialysis varchar(255) default null,
  date_of_dialysis date default null,
  primary key (ckd_initial_visit_id)
);
