
create table mw_diabetes_hypertension_initial (
  initial_visit_id 				int not null auto_increment,
  patient_id    				int not null,
  visit_date            			date,
  location              			varchar(255),
  diagnosis_type_1_diabetes 			varchar(255),
  diagnosis_type_1_diabetes_date		date, 
  diagnosis_type_2_diabetes 			varchar(255),
  diagnosis_type_2_diabetes_date		date, 
  diagnosis_hypertension 			varchar(255),
  diagnosis_hypertension_date			date, 
  hiv_status		 			varchar(255),
  hiv_test_date				date, 
  art_start_date				date, 
  cardiovascular_disease			varchar(255),
  cardiovascular_disease_date			date,
  retinopathy					varchar(255),
  retinopathy_date				date,
  renal_disease				varchar(255),
  renal_disease_date				date,
  family_history_diabetes_mellitus		varchar(255),
  family_history_hypertension   		varchar(255),
  tb_status					varchar(255),
  tb_status_year		   		varchar(255),
  stroke_and_tia				varchar(255),
  stroke_and_tia_date				date,
  peripheral_vascular_disease			varchar(255),
  peripheral_vascular_disease_date		date,
  neuropathy					varchar(255),
  neuropathy_date				date,
  sexual_disorder				varchar(255),
  sexual_disorder_date				date,
     primary key (initial_visit_id)
);
