
create table mw_diabetes_hypertension_followup (
  followup_visit_id 						int not null auto_increment,
  patient_id    						int not null,
  visit_date            					date,
  location              					varchar(255),
  height							decimal(10,2),
  weight							decimal(10,2),
  body_mass_index 						varchar(255),
  bp_stystolic							int,
  bp_diastolic 						int,
  pulse_rate							int,
  hba1c							decimal(10,2),
  fasting_blood_sugar						decimal(10,2),
  blood_sugar_test_type					varchar(255),
  tobbacco							varchar(255),
  alcohol							varchar(255),
  number_of_fruit_and_vegetable_portions			varchar(255),
  days_per_week_with_30_min_of_exercise			int,
  cardiovascular_risk						varchar(255),
  visual_acuity						varchar(255),
  neuropathy_or_pvd						varchar(255),
  deformities							varchar(255),
  ulcers					     		varchar(255),
  hospitalized_since_last_visit				varchar(255),
  diabetes_med_long_acting		 			varchar(255),
  diabetes_med_short_acting		 			varchar(255),
  diabetes_med_metformin		 			varchar(255),
  diabetes_med_gilbenclamide		 			varchar(255),
  diuretic_hctz			 			varchar(255),
  diuretic_furp			 			varchar(255),
  diuretic_spiro			 			varchar(255),
  ccb_aml				 			varchar(255),
  ccb_nif				 			varchar(255),
  ace_i_enal				 			varchar(255),
  ace_i_capt				 			varchar(255),
  ace_i_lisin			 				varchar(255),
  bb_aten				 			varchar(255),
  bb_bis				 			varchar(255),
  bb_prop				 			varchar(255),
  asprin_asa				 			varchar(255),
  statin_simva			 				varchar(255),
  statin_prava				 			varchar(255),
  statin_atorva			 			varchar(255),
  other_hyd				 			varchar(255),
  other_issmn				 			varchar(255),
  next_appointment_date 					date,
     primary key (followup_visit_id)
);
