create table mw_epilepsy_followup (
  epilepsy_followup_visit_id 			int not null auto_increment,
  patient_id 					int not null,
  visit_date 					date not null,
  location 					varchar(255) not null,
  height 					int,
  weight 					int,
  bmi 						varchar(255),
  seizure_since_last_visit 			varchar(255),
  number_of_seizures 				int,
  any_triggers 				varchar(255),
  alcohol_trigger 				varchar(255),
  fever_trigger 				varchar(255),
  sound_light_and_touch_trigger 		varchar(255),
  emotional_stress_anger_boredom_trigger 	varchar(255),
  sleep_deprivation_and_overtired_trigger 	varchar(255),
  missed_medication_trigger 			varchar(255),
  menstruation_trigger 			varchar(255),
  silent_makers 				varchar(255),
  hospitalized_since_last_visit 		varchar(255),
  pregnant 					varchar(255),
  family_planning 				varchar(255),
  med_carbamazepine 				varchar(255),
  med_carbamazepine_dose		int,
  med_carbamazepine_dosing_unit varchar(50),
  med_carbamazepine_route		varchar(50),
  med_carbamazepine_frequency		varchar(50),
  med_carbamazepine_duration   int,
  med_carbamazepine_duration_units  varchar(50),
  med_Phenobarbital 				varchar(255),
  med_Phenobarbital_dose		int,
  med_Phenobarbital_dosing_unit varchar(50),
  med_Phenobarbital_route		varchar(50),
  med_Phenobarbital_frequency		varchar(50),
  med_Phenobarbital_duration   int,
  med_Phenobarbital_duration_units  varchar(50),
  med_Phenytoin 				varchar(255),
  med_Phenytoin_dose		int,
  med_Phenytoin_dosing_unit varchar(50),
  med_Phenytoin_route		varchar(50),
  med_Phenytoin_frequency		varchar(50),
  med_Phenytoin_duration   int,
  med_Phenytoin_duration_units  varchar(50),
  med_Sodium_Valproate 			varchar(255),
  med_Sodium_Valproate_dose		int,
  med_Sodium_Valproate_dosing_unit varchar(50),
  med_Sodium_Valproate_route		varchar(50),
  med_Sodium_Valproate_frequency		varchar(50),
  med_Sodium_Valproate_duration   int,
  med_Sodium_Valproate_duration_units  varchar(50),
  med_other 					varchar(255),
  comments 					varchar(2000) ,
  next_appointment_date 			date,
  primary key (epilepsy_followup_visit_id)
);
