create table mw_mental_health_followup (
  mental_health_followup_visit_id 	int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  height 				int default null,
  weight 				int default null,
  phq_nine_score 		        int default null,
  mse_depressed_mood 			varchar(255) default null,
  mse_elevated_mood 			varchar(255) default null,
  mse_disruptive_behaviour 		varchar(255) default null,
  mse_disorganized_speech 		varchar(255) default null,
  mse_delusions 			varchar(255) default null,
  mse_hallucinations 			varchar(255) default null,
  mse_Lack_of_insight 			varchar(255) default null,
  mse_other 				varchar(255) default null,
  patient_stable 			varchar(255) default null,
  able_to_do_daily_activities  	varchar(255) default null,
  current_use_marijuana 		varchar(255) default null,
  current_use_alcohol 			varchar(255) default null,
  current_use_other 			varchar(255) default null,
  pregnant 				varchar(255) default null,
  on_family_planning 			varchar(255) default null,
  suicide_risk 			varchar(255) default null,
  medications_side_effects 		varchar(255) default null,
  hospitalized_since_last_visit 	varchar(255) default null,
  counselling_provided			varchar(255) default null,
  med_chloropromazine 			varchar(255) default null,
  med_chloropromazine_dose		int,
  med_chloropromazine_dosing_unit varchar(50),
  med_chloropromazine_route		varchar(50),
  med_chloropromazine_frequency		varchar(50),
  med_chloropromazine_duration   int,
  med_chloropromazine_duration_units  varchar(50),
  med_haloperidol 			varchar(255) default null,
  med_haloperidolp_dose		int,
  med_haloperidol_dosing_unit varchar(50),
  med_haloperidol_route		varchar(50),
  med_haloperidol_frequency		varchar(50),
  med_haloperidol_duration   int,
  med_haloperidol_duration_units  varchar(50),
  med_risperidone			varchar(255) default null,
  med_risperidone_dose		int,
  med_risperidone_dosing_unit varchar(50),
  med_risperidone_route		varchar(50),
  med_risperidone_frequency		varchar(50),
  med_risperidone_duration   int,
  med_risperidone_duration_units  varchar(50),
  med_fluphenazine 			varchar(255) default null,
  med_fluphenazine_dose		int,
  med_fluphenazine_dosing_unit varchar(50),
  med_fluphenazine_route		varchar(50),
   med_fluphenazine_frequency		varchar(50),
   med_fluphenazine_duration   int,
   med_fluphenazine_duration_units  varchar(50),
  med_carbamazepine 			varchar(255) default null,
  med_carbamazepine_dose		int,
  med_carbamazepine_dosing_unit varchar(50),
  med_carbamazepine_route		varchar(50),
  med_carbamazepine_frequency		varchar(50),
  med_carbamazepine_duration   int,
  med_carbamazepine_duration_units  varchar(50),
  med_sodium_valproate 		varchar(255) default null,
  med_sodium_valproate_dose		int,
  med_sodium_valproate_dosing_unit varchar(50),
  med_sodium_valproate_route		varchar(50),
  med_sodium_valproate_frequency		varchar(50),
  med_sodium_valproate_duration   int,
  med_sodium_valproate_duration_units  varchar(50),
  med_fluoxetine 			varchar(255) default null,
  med_fluoxetine_dose		int,
  med_fluoxetine_dosing_unit varchar(50),
  med_fluoxetine_route		varchar(50),
  med_fluoxetine_frequency		varchar(50),
  med_fluoxetine_duration   int,
  med_fluoxetine_duration_units  varchar(50),
  med_olanzapine 			varchar(255) default null,
  med_olanzapine_dose		int,
  med_olanzapine_dosing_unit varchar(50),
  med_olanzapine_route		varchar(50),
  med_olanzapine_frequency		varchar(50),
  med_olanzapine_duration   int,
  med_olanzapine_duration_units  varchar(50),
  med_clozapine 			varchar(255) default null,
  med_clozapine_dose		int,
  med_clozapine_dosing_unit varchar(50),
  med_clozapine_route		varchar(50),
  med_clozapine_frequency		varchar(50),
  med_clozapine_duration   int,
  med_clozapine_duration_units  varchar(50),
  med_trifluoperazine 			varchar(255) default null,
  med_trifluoperazine_dose		int,
  med_trifluoperazine_dosing_unit varchar(50),
  med_trifluoperazine_route		varchar(50),
  med_trifluoperazine_frequency		varchar(50),
  med_trifluoperazine_duration   int,
  med_trifluoperazine_duration_units  varchar(50),
  med_clopixol 			varchar(255) default null,
  med_clopixol_dose		int,
  med_clopixol_dosing_unit varchar(50),
  med_clopixol_route		varchar(50),
  med_clopixol_frequency		varchar(50),
  med_clopixol_duration   int,
  med_clopixol_duration_units  varchar(50),
  med_amitriptyline                    varchar(255) default null,
  med_amitriptyline_dose		int,
  med_amitriptyline_dosing_unit varchar(50),
  med_amitriptyline_route		varchar(50),
  med_amitriptyline_frequency		varchar(50),
  med_amitriptyline_duration   int,
  med_amitriptyline_duration_units  varchar(50),
  med_other 				varchar(255) default null,
  comments 				varchar(2000) default null,
  next_appointment_date 		date default null,
  primary key (mental_health_followup_visit_id)
) ;
