create table mw_ncd_other_initial (
  ncd_other_initial_visit_id int not null auto_increment,
  patient_id int not null,
  visit_date date default null,
  location varchar(255) default null,
  diagnosis_rheumatoid_arthritis varchar(255) default null,
  diagnosis_date_rheumatoid_arthritis date default null,
  diagnosis_cirrhosis varchar(255) default null,
  diagnosis_date_cirrhosis date default null,
  diagnosis_dvt_or_pe varchar(255) default null,
  diagnosis_date_dvt_or_pe date default null,
  diagnosis_sickle_cell_disease varchar(255) default null,
  diagnosis_other varchar(255) default null,
  diagnosis_date_other date default null,
  hiv_status varchar(255) default null,
  hiv_test_date date default null,
  art_start_date date default null,
  tb_status varchar(255) default null,
  tb_start_date date default null,
  comorbidities_hypertension varchar(255) default null,
  comorbidities_diabetes varchar(255) default null,
  comorbidities_chronic_kidney_disease varchar(255) default null,
  comorbidities_other varchar(255) default null,
  echo_test_result varchar(255) default null,
  echo_test_date date default null,
  ecg_test_result varchar(255) default null,
  ecg_test_date date default null,
  primary key (ncd_other_initial_visit_id)
);

