create table mw_ncd_other_followup (
  ncd_other_followup_visit_id int not null auto_increment,
  patient_id int not null,
  visit_date date default null,
  location varchar(255) default null,
  height int default null,
  weight int default null,
  weight_change varchar(255) default null,
  bp_systolic int default null,
  bp_diastolic int default null,
  heart_rate int default null,
  spo2 int default null,
  alcohol varchar(255) default null,
  tobacco varchar(255) default null,
  fruit_and_vegetable_portions int default null,
  days_per_week_exercise int default null,
  hospitalized_since_last_visit_for_ncd varchar(255) default null,
  medications varchar(255) default null,
  medications_changed varchar(255) default null,
  comments varchar(2000) default null,
  next_appointment_date date default null,
  next_appointment_location varchar(255) default null,
  primary key (ncd_other_followup_visit_id)
);
