
create table mw_ncd_visits (
  ncd_visit_id                      int not null auto_increment primary key,
  patient_id                        int not null,
  visit_date                        date,
  location                          varchar(255),
  visit_types                       varchar(255),
  cc_initial                        boolean,
  cc_followup                       boolean,
  diabetes_htn_initial              boolean,
  diabetes_htn_followup             boolean,
  asthma_initial                    boolean,
  asthma_followup                   boolean,
  epilepsy_initial                  boolean,
  epilepsy_followup                 boolean,
  mental_health_initial             boolean,
  mental_health_followup            boolean,
  ckd_initial			     boolean,
  ckd_followup			     boolean,
  chf_initial			     boolean,
  chf_followup			     boolean,
  ncd_other_initial                 boolean,
  ncd_other_followup                boolean,
  sickle_cell_initial               boolean,
  sickle_cell_followup              boolean,
  next_appointment_date             date,
  systolic_bp                       decimal(10,2),
  diastolic_bp                      decimal(10,2),
  on_insulin                        boolean,
  asthma_classification             varchar(100),
  seizure_activity                  boolean,
  num_seizures                      decimal(10,2),
  hba1c                             decimal(10,2),
  serum_glucose                     decimal(10,2),
  foot_check                        boolean,
  suicide_risk                      varchar(255),
  proteinuria                       varchar(255),
  creatinine                        decimal(10,2),
  hiv_result                        varchar(255),
  visual_acuity                     varchar(255),
  cv_risk                           decimal(10,2),
  hospitalized_since_last_visit     varchar(255),
  mental_status_exam                varchar(255),
  mental_health_drugs               varchar(255),
  mental_health_drug_side_effect    varchar(255),
  mental_stable                     varchar(255),
  fundoscopy                        varchar(255)
);
alter table mw_ncd_visits add index mw_ncd_visit_patient_idx (patient_id);
alter table mw_ncd_visits add index mw_ncd_visit_patient_location_idx (patient_id, location);
