create table mw_pdc_cleft_lip_palate_followup (
  pdc_cleft_lip_palate_visit_id 	int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  weight 				int default null,
  height				int default null,
  muac 				int default null,
  weight_for_age			int default null,
  height_for_age			int default null,
  malnutrition				varchar(255) default null,
  feeding_problems			varchar(255) default null,
  difficult_breathing			varchar(255) default null,
  heart_murmur				varchar(255) default null,
  ear_pain				varchar(255) default null,
  ear_discharge			varchar(255) default null,
  other			        varchar(255) default null,
  surgery_scheduled			varchar(255) default null,
  surgery_date				date default null,
  continue_followup			varchar(255) default null,
  group_therapy			varchar(255) default null,
  food_supplement			varchar(255) default null,
  individual_counselling		varchar(255) default null,
  feeding_counseling			varchar(255) default null,
  mdat					varchar(255) default null,
  poser				varchar(255) default null,
  referred_out				varchar(255) default null,
  referred_out_specify			varchar(255) default null,
  if_referred_out			varchar(255) default null,
  if_referred_out_specify		varchar(255) default null,
  clinical_plan			varchar(255) default null,
  next_appointment_date		date default null,
  primary key (pdc_cleft_lip_palate_visit_id)
) ;
