
create table mw_pdc_trisomy_21_followup (
  pdc_trisomy_21_visit_id 		int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  weight 				int default null,
  height				int default null,
  muac 					int default null,
  malnutrition				varchar(255) default null,
  passage_normal			varchar(255) default null,
  diarrhea_persistent			varchar(255) default null,
  vomiting				varchar(255) default null,
  ear_pain				varchar(255) default null,
  ear_discharge				varchar(255) default null,
  sleep_apnea				varchar(255) default null,
  sleep_chocking			varchar(255) default null,
  extremities_pain			varchar(255) default null,
  extremities_weakness			varchar(255) default null,
  anticonvulsant			varchar(255) default null,
  drug_and_dose				varchar(255) default null,
  adjust_dose				varchar(255) default null,
  individual_counselling		varchar(255) default null,
  feeding_counselling			varchar(255) default null,
  continue_followup			varchar(255) default null,
  physiotherapy				varchar(255) default null,
  group_counselling_and_play_therapy	varchar(255) default null,
  mdat					varchar(255) default null,
  referred_to_poser			varchar(255) default null,
  referred_out				varchar(255) default null,
  referred_out_specify			varchar(255) default null,
  if_referred_out			varchar(255) default null,
  if_referred_out_specify		varchar(255) default null,
  next_appointment_date 		date default null,
  primary key (pdc_trisomy_21_visit_id )
) ;
