create table mw_pdc_other_diagnosis_followup (
  pdc_other_diagnosis_visit_id 		int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  age_adjusted				int default null,
  age_non_adjusted			int default null,
  weight 				int default null,
  height				int default null,
  muac 					int default null,
  weight_against_age			int default null,
  weight_against_height			int default null,
  complications_since_last_visit	varchar(255) default null,
  malnutrition				varchar(255) default null,
  head_circumference			int default null,
  convulsions_any_since_last_visit	varchar(255) default null,
  anticonvulsant			varchar(255) default null,
  drug_and_dose				varchar(255) default null,
  adjust_dose				varchar(255) default null,
  poor_suck				varchar(255) default null,
  refs_to_feed				varchar(255) default null,
  less_feed_concerns			varchar(255) default null,
  individual_counseling			varchar(255) default null, 
  feeding_counseling			varchar(255) default null,
  group_counselling			varchar(255) default null,
  play_therapy				varchar(255) default null,
  continue_followup			varchar(255) default null,
  physiotherapy				varchar(255) default null,
  poser					varchar(255) default null,
  referred_out				varchar(255) default null,
  referred_out_specify			varchar(255) default null,
  if_referred_out			varchar(255) default null,
  if_referred_out_specify		varchar(255) default null,
  mdat					varchar(255) default null,
  clinical_plan			varchar(255) default null,
  next_appointment_date 		date default null,
  primary key (pdc_other_diagnosis_visit_id)
) ;
