create table mw_poc (
    poc_visit_id int not null auto_increment,
    patient_id int not null,
    visit_date date,
    location varchar(255),
    sample_taken_for_viral_load varchar(255),
    lower_than_detection_limit varchar(255),
    reason_for_testing varchar(255),
    lab_location varchar(255),
    less_than_limit varchar(255),
    reason_for_no_result varchar(255),
    viral_load_sample_id varchar(255),
    reason_for_no_sample varchar(255),
    lab_id varchar(255),
    symptom_present varchar(255),
    symptom_absent varchar(255),
    adherence_session_number varchar(255),
    name_of_support_provider varchar(255),
    number_of_missed_medication_doses_in_past_week varchar(255),
    viral_load_counseling varchar(255),
    medication_adherence_percent varchar(255),
    adherence_counselling varchar(255),
    date_of_blood_sample date,
    hiv_test_type varchar(255),
    reason_for_no_sample_eid varchar(255),
    result_of_hiv_test varchar(255),
    hiv_test_time_period varchar(255),
    age varchar(13),
    units_of_age_of_child varchar(255),
    lab_test_serial_number varchar(255),
    date_of_returned_result varchar(255),
    date_result_to_guardian date,
    reason_for_testing_coded varchar(255),
    height decimal(10,2),
    is_patient_preg varchar(255),
    muac varchar(255),
    weight decimal(10,2),
    diastolic_blood_pressure decimal(10,2),
    pulse decimal(10,2),
    systolic_blood_pressure decimal(10,2),
    result_of_hiv_test_htc varchar(255),
    hiv_test_type_htc varchar(255),
    colposcopy_of_cervix_with_acetic_acid varchar(255),
    appointment_date date,
    qualitative_time varchar(255),
    outcome varchar(255),
    clinical_impression_comments varchar(300),
    refer_to_screening_station varchar(255),
    transfer_out_to varchar(255),
    reason_to_stop_care varchar(255),
    primary key (poc_visit_id)
);
