create table mw_pdc_developmental_delay_followup (
  pdc_developmenta_delay_visit_id 	int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  height				int default null,
  weight 				int default null,
  muac 					int default null,
  weight_against_age			int default null,
  weight_against_height			int default null,
  malnutrition				varchar(255) default null,
  mdat					varchar(255) default null,
  tone_normal				varchar(255) default null,
  tone_hypo				varchar(255) default null,
  tone_hyper				varchar(255) default null,
  feeding_sucking			varchar(255) default null,
  feeding_cup				varchar(255) default null,
  feeding_tube				varchar(255) default null,
  signs_of_cerebral_palsy		varchar(255) default null,
  under_mental_health_care_program	varchar(255) default null,
  anticonvulsant			varchar(255) default null,
  dose_and_drug				varchar(255) default null,
  dose_adjusted				varchar(255) default null,
  continue_followup			varchar(255) default null,
  feeding_counselling			varchar(255) default null,
  group_counselling_and_play_therapy	varchar(255) default null,
  referred_to_poser			varchar(255) default null,
  referred_out				varchar(255) default null,
  referred_out_specify			varchar(255) default null,
  if_referred_out			varchar(255) default null,
  if_referred_out_specify		varchar(255) default null,
  next_appointment_date 		date default null,
  primary key (pdc_developmenta_delay_visit_id)
) ;
