create table mw_sickle_cell_disease_followup (
  sickle_cell_disease_followup_visit_id int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  height 				int default null,
  weight 				int default null,
  bmi_muac				int default null,
  bp_systolic 				int default null,
  bp_diastolic		 		int default null,
  hr			 		int default null,
  hb			 		int default null,
  spo2				 	int default null,
  temperature				int default null,
  hospitalized_since_last_visit		varchar(255) default null,
  absence_from_school 			varchar(255) default null,
  pain		 			varchar(255) default null,
  fever		 			varchar(255) default null,
  medication_rx				varchar(255) default null,
  antibiotics_rx			varchar(255) default null,
  medication_side_effects		varchar(255) default null,
  Jaundice			 	varchar(255) default null,
  irregular_conjunctiva 		varchar(255) default null,
  abnormal_lungs_exam 			varchar(255) default null,
  ascites	 			varchar(255) default null,
  enlarged_liver 			varchar(255) default null,
  enlarged_spleen			varchar(255) default null,
  next_appointment_date			date,
  primary key (sickle_cell_disease_followup_visit_id));
