create table mw_sickle_cell_disease_initial (
  sickle_cell_disease__initial_visit_id int not null auto_increment,
  patient_id 				int not null,
  visit_date 				date default null,
  location 				varchar(255) default null,
  diagnosis_date	 		date default null,
  microscopy				varchar(255) default null,
  microscopy_test_date 			date default null,
  rapid_test				varchar(255) default null,
  rapid_test_date 			date default null,
  hb_electrophoresis			varchar(255) default null,
  hb_electrophoresis_test_date 		date default null,
  hiv_status 				varchar(255) default null,
  hiv_test_date 			date default null,
  art_start_date 			date default null,
  parent 				varchar(255) default null,
  sibling				varchar(255) default null,
  referral_history_inpatient 		varchar(255) default null,
  referral_history_ic3 			varchar(255) default null,
  referral_history_opd 			varchar(255) default null,
  referral_history_other 		varchar(255) default null,
  referral_history_other_specify 	varchar(255) default null,
  primary key (sickle_cell_disease__initial_visit_id)
);
