create table mw_teen_club_followup (
    teen_club_followup_visit_id int not null auto_increment,
    patient_id int not null,
    visit_date date,
    location varchar(255),
    height decimal(10 , 2 ),
    weight decimal(10 , 2 ),
    muac_bmi decimal(10 , 2 ),
    tb_status varchar(255),
    tb_screening_outcome varchar(255),
    sputum_collected varchar(255),
    nutrition_screening_for_normal_muac varchar(255),
    nutrition_referred varchar(255),
    mental_health_screened varchar(255),
    adolescent_referred varchar(255),
    adolescent_registered varchar(255),
    sti_screening_outcome varchar(255),
    referred_to_sti_clinic varchar(255),
    hospitalized varchar(255),
    next_appointment date,
    primary key (teen_club_followup_visit_id)
);
