create table mw_tb_initial (
  tb_initial_visit_id 			int not null auto_increment,
  patient_id    				int not null,
  visit_date            		date,
  location              		varchar(255),
  disease_classification 		varchar(255),
  patient_category 				varchar(255),
  diagnosis						varchar(255),
  arv_start_date 				date,
  ctx_start_date 				date,
  hiv_test_history  			varchar(255),
  regimen_rhze					int,
  initiation_month_weight		int,
  dot_option  					varchar(255),
  source_of_referral  			varchar(255),
  dst_result  					varchar(255),
  ptld_date_registered          date,
  date_started_prp              date,
     primary key (tb_initial_visit_id)
);
